### ISSUE TITLE
Report and Edit Links in Related Resources

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#1007]
Remove Report and Edit link in Related Resource model

![Image](https://github.com/user-attachments/assets/f9ddfd23-e95c-4a2b-a5b5-46f8599941d9)

**Comment by bferguso** [comment]
The user information doesn't seem to be readily available here so have just removed the links for everyone. If internal users want access to these links in the future we can dig into making the user information available.

**Comment by emjohnst** [comment]
Done in test
