### ISSUE TITLE
Details Page No Data

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#1009]
Hide labels for data fields with no data in them on Details Page. Example: Power Block - DhRs-47

Specifically:

- [x] Heritage Theme
- [x] Significance Type
- [x] Description
- [x] Heritage value
- [x] Character defining elements
- [x] Document Location

![Image](https://github.com/user-attachments/assets/5bb5f0ae-f31e-449d-ad3f-8e20dbe474db)

**Comment by bferguso** [comment]
Also hid sections without any data in them

**Comment by emjohnst** [comment]
Done in test
