### ISSUE TITLE
Conduct Search of .gif file types in image

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#1010]
Some documents that were .gif or .pdf file type ended up in the images section of records.

Please do a search for .gif and .pdf file types in images section (or all non .jpg types) 

Please include the following attributes with search:
borden number
file type
file name (sometimes the file name ended up in Images Features section)

**Comment by bferguso** [comment]
Sent by email. Query used:
```
select  bn.borden_number->'en'->>'value' borden_number, site_images->0->>'name' file_name, site_images->0->>'type' file_type
from heritage_site.site_images i
join heritage_site.borden_number bn on i.resourceinstanceid = bn.resourceinstanceid
where lower(site_images->0->>'name') ~ '.(gif|pdf)$'
order by 1;
```

**Comment by emjohnst** [comment]
Done, .gif files removed from images if they were more internal documents
