### ISSUE TITLE
Sandcastle RM Issue

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#1019]
In Test, Geometry for Sandcastle Resource is not displaying on the map. If the geometry doesn't display on the map it can't be selected for analysis of sites within or around its boundaries. Verified that sandcastle map overlay is turned on and still not displaying.

Example of Test Sandcastle resource: 2024-07-17 Translink Stations

Attached image of where sandscastle resource should display in search
Attached image of editing sandcastle resource and what geometry should look like

![Image](https://github.com/user-attachments/assets/d0b4f43d-36ed-4ed1-bd1f-68ef27b6f033)
![Image](https://github.com/user-attachments/assets/2a9b2d3e-4833-4798-bf89-e95407227bda)

**Comment by bferguso** [comment]
This actually affected all resource models with permissions associated with them. Prior to Arches Core 7.6, MVT tiles were not cached on a user-by-user bases so the most restrictive permissions were always applied to them. To resolve this the following was done:
1. Copied the MVT class back from 7.6 to our release
2. Ignored the restrictions for superusers
3. Added a management command to clear the MVT tile cache
4. Added a management command to reset the resource instance permissions based on the business rules.

Right now the view is an all-or-nothing (ie - you either get everything for superusers or the anonymous limited view for the rest of the world). This should be corrected if/when local governments are given access.

Also - the temporary fix in the `views/mvt_core.py` file should be removed once we move to 7.6.x.

**Comment by emjohnst** [comment]
Done in test
