### ISSUE TITLE
Filter By Feature Issue

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#1021]
When trying to filter by a feature on the Municipal or Regional District Map overlay in TEST as PUBLIC USER, i get an error message (attached console pic). Note that when authenticated in Test logged in as IDIR user I can perform this search.

Steps to replicate:
Turn on Muncipal Boundaries
Zoom into municipality, example Penticton
Click on feature name "Penticton" to open map card
Go to map filter tab
Select a filter: Search by feature
Map card should now display "Fllter by Feature" button
Click Button
Expected result: sites within search feature should appear in search results
Actual results: error message

![Image](https://github.com/user-attachments/assets/d607099a-64e8-4c87-b255-40bdcaca2578)

**Comment by bferguso** [comment]
@emjohnst  - Were you using a private browser tab when you got this? I'm seeing the same thing when I use a private browser, but it's fine as the public if I use a regular browser window.

**Comment by emjohnst** [comment]
This is only an issue when viewing in private browser

**Comment by bferguso** [comment]
This should be sorted out - it could also happen for users that don't allow cookies or otherwise have tighter browser security set.

**Comment by bferguso** [comment]
This was caused by the CSRF token not being available with tighter browser security. Added the token to the search page and added it to the search ajax request.

**Comment by emjohnst** [comment]
Done in test
