### ISSUE TITLE
Display Multiple SoSs

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#1024]
- [x] -Display multiple SoSs on details page
- [x] - Update PDF print out to handle multiple SoSs

**Comment by bferguso** [comment]
@emjohnst - This could make the details page quite long. Do you want the SoS section to be hidden by default?

**Comment by emjohnst** [comment]
@bferguso That's okay, please do not hide the SoS section. I think there will only be a couple cases where this applies.
