### ISSUE TITLE
Mobile Landing Page

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#1025]
- [ ] top bar covers images/text
- [ ] text appears too big for screen

![Image](https://github.com/user-attachments/assets/a9ce94da-c2d8-4316-89fb-1247186aba1e)
![Image](https://github.com/user-attachments/assets/e46bd10c-3e81-4150-9ba9-22ff7511d34b)

**Comment by bferguso** [comment]
@emjohnst - What kind of phone & browser are you using? Fix the wrapping image issue. Works with Firefox & Brave (Chrome engine) browsers. Safari is messed up though - can't even click on the hamburger.

**Comment by emjohnst** [comment]
Ah I'm using an iPhone on Safari.

**Comment by emjohnst** [comment]
Done in test
