### ISSUE TITLE
Define Attribute Data for Shapefile Export 

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#1036]
- [ ] Define attribute data for shapefiles (similar to BCGW data export) and re-implement for public and internal users
- [ ] Re-implement ability to export shapefiles

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/emjohnst/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/emjohnst/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Field | Shapefile Name
-- | --
Name | SITE_NAME
Name Type | ST_NM_TYP
Construction Actor | BLDR_NMS
Construction Actor Type | BLDR_TYP
Event Start Year | EVNT_ST_YR
Event End Year | EVNT_ND_YR
Event Qualified | CIRCA
Function Category | FUNCTION
Function State | FNCT_ERA
Spatial | BOUNDARY
Location Description | LOC_DESC
Locality | LOCALITY
Province | PROVINCE
City | CITY
Street Address | STRT_DDRSS
PID | PRCL_DSCRN
Officially Recognized | OFFCLLY_RD
Registry Type | RGSTRY_TYP
Registration Status | RGSTRTN_SS
Recognition Government | RCGNTN_GVT
Reference Number | RFRNC_NMBR
Recognition Start | RCGNTN_ST
Recognition End | RCGNTN_END
Legislative Act | LEG_ACT
Borden Number | BRDNNMBR

</body>

</html>

**Comment by bferguso** [comment]
Most of the work required will be in defining the attributes by the business. At this point it might be a similar process to adding help text. If this was completed at the same time as the help text update, the development effort may be shared between this and the help text issue.

**Comment by emjohnst** [comment]
@bferguso I've updated the ticket to include the attributes and their names. Can you please instruct how you would like this to be updated? In Test or Prod? Should this be done before our other updates this release?

**Comment by bferguso** [comment]
@emjohnst  - Can we leave this issue to be part of the 7.6.0 Arches Core release?

**Comment by emjohnst** [comment]
@bferguso we are really hoping to get this functionality soon, what is the reason for waiting for the release?

**Comment by bferguso** [comment]
Some of these settings may be able to be updated directly in the database. Need to figure out how we log those changes, and how to keep the resource models and the database in sync if we do a stright DB update.

**Comment by emjohnst** [comment]
@bferguso I specified what fields to export and gave them the column names in Delivery but I don't think it's having the desired result because when I deselect a field to export that means it removes it from all CSV exports as well, not just shapefiles correct? I noticed the internal CSV export limited the fields to what I specified - but we just want to limit the fields for shapefiles, limit fields for external csv reports and want to be able to export on all fields for internal user csv reports.

**Comment by emjohnst** [comment]
@bferguso I'm noticing the CSV export for Internal Users in Test is different than the CSV export for Internal Users in Delivery. Are these different because of the changes I applied to define the shapefile export or were the environments different before? Excels attached below

[Heritage Site Delivery Internal User.csv](https://github.com/user-attachments/files/17482167/Heritage.Site.Delivery.Internal.User.csv)
[Heritage Site Test Internal User.csv](https://github.com/user-attachments/files/17482166/Heritage.Site.Test.Internal.User.csv)

**Comment by bferguso** [comment]
@emjohnst - The custom CSV export for Heritage Site is only configured to be used by anonymous users, so internal CSV export of `Heritage Site` resources is driven by the `Export via Search Results` switch you've been updating.

I believe the original CSV export requirement was for internal users to have a larger set of fields than anonymous users which is why the custom export is only implemented for anonymous users.

If this needs to be changed please create a separate ticket as it's unrelated to the Shapefile export.

**Comment by bferguso** [comment]
Updated the JSON file using the extracted Resource Model from DLVR. Created a script to update the database NODES table with the values in DLVR, using the current TEST state for rollback values (which matches PROD).

Enabled the Shapefile export option in the `Export Search Results` page. NB - still have the Tile Excel and GeoJSON URL export options commented out.

**Comment by bferguso** [comment]
Updated the CSV export for internal (authenticated) users so that all of the Heritage Site attributes are exported.

**Comment by emjohnst** [comment]
@bferguso Internal CSV is not exporting on all Heritage Site attributes, can you try again? Shapefile is working - I've realized it would probably best to flatten the data like how we send it out to DataBC because the shapefiles with multiple data points under the attributes is difficult to read - I will make a new ticket for this to address later as the functionality is fine as is.

**Comment by bferguso** [comment]
I just tried TEST and it seems like they're all exporting. Can you please tell me which fields are missing?

**Comment by emjohnst** [comment]
@bferguso There are 41 attributes missing 

[CSVINTERNALPRODTEST.xlsx](https://github.com/user-attachments/files/17560717/CSVINTERNALPRODTEST.xlsx)
