### ISSUE TITLE
Recognition End Date not Displaying on Details Page

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#1040]
The details page is not displaying end dates for official recognition information. Please update the details page for both INTERNAL and EXTERNAL users.

Example record: FgRm-1 

Expected result:
Recognition Type Provincial, Provincial Park 
Recognition Government Government of BC
Under Provincial Park should display:
Recognition Date 1963-06-27 - 1999-06-28

Actual Result:
Recognition Type Provincial, Provincial Park 
Recognition Government Government of BC
Recognition Date 1963-06-27
Reference Number OIC 1654

**Comment by bferguso** [comment]
@emjohnst - Is this in the details tab?

**Comment by emjohnst** [comment]
@bferguso yes, i'll specify that in the ticket title
