### ISSUE TITLE
Details page "None"

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#1041]
*Please make details page the same for both public and internal users
Several fields for the details section display "none" when there is no data. 

When there is no data please set these fields to not appear:

IMAGE CAPTION
- [x] Image Type
- [x] Image view
- [x] Images features
- [x] Comma before Date (do not display comma before date if there is no date)
- [x] Copyright

HERITAGE SITE LOCATION

- [x] Street Address
- [x] City
- [x] Locality

**Comment by bferguso** [comment]
Also:
1. fixed the comma spacing in the address fields
2. Added a button to allow internal users to view all the fields on the Heritage Site details tab.

**Comment by emjohnst** [comment]
@bferguso I think the button was added to the public users page and it needs to be for the internal user page. I'm not seeing the changes to the details page made for internal users.

**Comment by bferguso** [comment]
@emjohnst - Sorry, I missed hiding for the public when I refactored the javascript. It seems to be available for both. Hiding it for the public now.

**Comment by emjohnst** [comment]
@bferguso Please remove "none" and add comma after or before date if there is no data in "Image Features"
![Image](https://github.com/user-attachments/assets/8ee8b6cb-d608-48ed-acdc-741ae15fe50e)

**Comment by bferguso** [comment]
Done. Fixed a logic error in the template.
