### ISSUE TITLE
Get simplified geology layer from GeoBC

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#106]
To replace WHSE_MINERAL_TENURE.GEOL_BEDROCK_UNIT_POLY_SVW layer when located.

**Comment by bferguso** [comment]
The WHSE_MINERAL_TENURE.GEOL_BEDROCK_UNIT_POLY_SVW layer to be maintained, but additional styling required for clarity. Additional layers to be added.

**Comment by elisabethdeom** [comment]
Hi Brett,

Still having problems with GitHub; I don’t get to the place where the sprints and tickets are.
So I piggy-backed on your ticket notification to develop a new one for the BCGS rock formation layer.  Did it go in the right place as a new ticket?

If not, this is what the new ticket is for:
Title: Updating the BCGS rock formation layer to add colour-coding to formations to highlight fossil potential ranking
Description: working with BCGS staff to get approval to proceed with work and develop maintenance schedule for updates of the layer in the BCGW.

Elisabeth

**Comment by bferguso** [comment]
There is no simplified layer
