### ISSUE TITLE
Update Record Public Site Permissions

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#1061]
If records have no Site Admin data card then the record should not be available to the public. 

Issue: when creating a new record the last data card for entry is the Site Admin Card. The Site Admin Card automatically selects "In progress" under BCRHP Submission Status but this status does not save (and thus make the record non-public) until the card is saved. We need a way for records to not be visible to the public until they have a Site Admin Card status.

**Comment by bferguso** [comment]
@emjohnst - Wondering if the records you're seeing with disrepancies are all from the initial import. Saw an issue that might cause that. Checked the data and there is only one site without a site admin record, which is totally empty so I believe the update you made should have fixed any existing issues.

**Comment by emjohnst** [comment]
@bferguso I tried to recreate this with new sites added in production but I could not replicate the issue. It appears to be resolved, or perhaps I was logged in when I initially saw this issue. Closing ticket for now unless we encounter the issue again.
