### ISSUE TITLE
Fix issue causing some resource model data export to fail

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#1075]
There is a bug in the Arches Designer Resource Model editor that causes the widget sort oder to be null. This causes an error when exporting the data via CSV when the node order is sorted.
This is an issue for the following Models/Nodes:
Government:
- Government Type (Should be 1)

Government Person:
- First Name (Should be 0)
- Last Name  (Should be 1)

Need to:
1. Manually update the graph JSON values in the source code so that apps built with them in the future don't have this issue.
2. Update the values in the cards_x_nodes_x_widgets.sortorder column

**Comment by emjohnst** [comment]
Government Person is not public so it might not need a fix. FYI internal users can't download everything - it fails because I believe Heritage Site Submission and Sandcastle do not have csv exports made for them.

**Comment by bferguso** [comment]
Govenment Person needed to be fixed to avoid issues when internal users perform a CSV export. The internal export was failing due to an issue identified iin #1108 .

**Comment by bferguso** [comment]
Also related: #1111
