### ISSUE TITLE
500 error when CSV export happens for resource types that have no exportable attributes

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#1108]
When performing a CSV export that includes resources that don't have any exportable fields a HTTP 500 error message occurs. Need to fix this by either 
1.  fixing the arches core issue causing this to happen or 
2. making sure all resource types have at least one exportable attribute (or all of them exportable)

From the previous ticket:
1. Internal users get an error message. This is likely because heritage site submission and sandcastle don't have define csv exports - can we make them have csv exports just simply on all fields?
![Image](https://github.com/user-attachments/assets/b484aebe-ba7c-4fe6-b546-f42876b7f603)

**Comment by bferguso** [comment]
This appears to be because there are cards in the Site Submission and Sandcastle resource models that have null sort orders. There is also one card in Heritage Site resource model, but that won't cause problems as we have an alternate mechanism to create CSV from that resource model.

**Comment by bferguso** [comment]
@emjohnst  - I'm seeing an issue with Site Submissions that if there is a card for the Submission Documents, but there are no documents it is raising an export error. Let's log that issue and handle it after 7.6.x? Created an issue here: #1112

The fix is to either add a file or delete the card without any associated files.

**Comment by emjohnst** [comment]
@bferguso Another minor issue - there is a time difference between download time stamp and actual time. Is this an easy fix to set proper time zone or an arches core bug?
 ![Image](https://github.com/user-attachments/assets/15e20556-65cb-4311-93fa-3bc2fdb10b23)

**Comment by bferguso** [comment]
This is unrelatd to the 500 error. Can you please raise as a separate issue? I'll need to look into that seperately. If the 500 error is fixed this ticket can be move to Done.

**Comment by emjohnst** [comment]
@KatieMcEvoy can you test the export on more than 2000 records (internally, and as public user) and see if you get an email? In one of my tests I still got an email but I can't seem to replicate it. Make sure to delete cache/browser history before testing. Thanks!

**Comment by KatieMcEvoy** [comment]
It works normally as long as the "Report Link" is not selected.
When it is selected I received the following error message
![Capture](https://github.com/user-attachments/assets/e5dc69d4-031e-480c-b690-b3449b0431a3)

**Comment by bferguso** [comment]
Fixed so selecting the report link doesn't break the export. This is only available to internal users for Heritage Site. Currently the link is not correct, which should probably be fixed. This should be addressed as a separate issue, and perhaps it should wait until after 7.6.x as this has always been the case due to it being configured due the the reverse proxy.

**Comment by emjohnst** [comment]
@bferguso This issue is  happening in PROD for internal issues - I've tested all the resource models and I think its just Site Submission causing the issue - when trying to export I get a 500 Server Error

**Comment by bferguso** [comment]
The above issue was caused by data described by #1112 . Closing this issue as it has been resolved.
