### ISSUE TITLE
Review and provide final list of attributes for bedrock geology layer

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#118]
Available options are:
AGE_GROUP: "205_intrusive rocks"
AUTHOR_NAMES: "<Author Names>"
​​BEDROCK_UNIT_ID: "4227"
​​DATA_SOURCE_ID: "1007"
​​FEATURE_AREA_SQM: "7016150171.4004"
​​FEATURE_LENGTH_M: "4758974.9978"
​​GEOLOGICAL_ERA: "Mesozoic"
​​GEOLOGICAL_PERIOD: "Jurassic"
​​GEOLOGY_UNIT_CODE: "JI_V"
​​GROUP_SUITE_NAME: "Island Plutonic Suite"
​​LITHOLOGY_CODE: "83"
​​MAXIMUM_AGE_NAME: "Early Jurassic"
​​MAXIMUM_AGE_VALUE: "208"
​​MINIMUM_AGE_NAME: "Middle Jurassic"
​​MINIMUM_AGE_VALUE: "157.1"
​​MORPHOTECTONIC_BELT: "Insular"
​​OBJECTID: "1547"
​​ORIGINAL_DESCRIPTION: "Granodiorite, quartz diorite, quartz monzonite, diorite, agmatite, feldspar porphyry, minor gabbro and aplite (170 - 185 Ma)."
​​PROJECT_NAME: "Vancouver Island"
​​ROCK_CLASS: "intrusive rocks"
​​ROCK_TYPE_CODE: "gd"
​​ROCK_TYPE_DESCRIPTION: "granodioritic intrusive rocks"
​​STRATIGRAPHIC_AGE_CODE: "20540"
​​STRATIGRAPHIC_AGE_NAME: "Early Jurassic to Middle Jurassic"
​​STRATIGRAPHIC_NAME: "Island Plutonic Suite"
​​STRATIGRAPHIC_UNIT_CODE: "EMJIgd"
​​STRATIGRAPHIC_UNIT_CODE_1M: "EMJgd"
​​TECTONIC_ASSEMBLAGE_CODE: "MJgV"
​​TECTONIC_ASSEMBLAGE_NAME: "Middle Jurassic - Vancouver Island"
​​TERRANE_CODE: "Wr"
​​TERRANE_NAME: "Wrangellia"
​​UNIT: "EMJIgd - Mesozoic - Early Jurassic to Middle Jurassic granodioritic intrusive rocks"

**Comment by LeannePyle** [comment]
Just as the display shows in MapPlace2, we want users to see:
Strat unit
Strat Name
Strat Age
Rock Type

**Comment by bferguso** [comment]
@LeannePyle - Updated as per your direction. I also included a list of all the possible values in case there is other information that you want presented.
