### ISSUE TITLE
Load Fossil Sample / Storage Location relationship data

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#125]
- [x] One sample in two places, need to add alternate place as a note in the sample
- [x] "Discarded collection" name needs to be moved to the notes
- [x] At university level, departments go in notes
- [x] Set "Uncertain" flag

**Comment by bferguso** [comment]
@LeannePyle, @elisabethdeom - For the first in the list, I'm seeing some additional locations omitted from the list in the target. Can look at Institution# TMP1979.022.0001 as an example.

**Comment by bferguso** [comment]
There are two repositories values that don't have associated storage location notes. They are:
- "TMP= Royal Tyrrell Museum of Palaeontology, Drumheller, AB; National Museum of Natural Sciences, Paleobiology Division, Ottawa, ON; University of Calgary, Calgary, AB"
- "TMP=Royal Tyrrell Museum of Palaeontology, Drumheller, AB; National Museum of Natural Sciences, Paleobiology Division, Ottawa, ON; University of Calgary, Calgary, AB"

Is this correct or should the additional locations be in the notes fields?

**Comment by LeannePyle** [comment]
For multiple locations, let's put all additional locations in the notes field

**Comment by bferguso** [comment]
Updated the source Excel file and associated ETL source table (cleaned_storage_locations) to move the additional locations above into the notes field a prefix of "Additional Locations: ".
