### ISSUE TITLE
Obtain correct data from original spreadsheets

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#128]
Issues with the BCGW spreadsheet:
- [x] Truncated data in Significant fossils
- [x] Truncated data in Non-significant fossils
- [x] Truncated data in Common names (?)
- [x] Special characters not being displayed properly (?) +/-

@LeannePyle and @elisabethdeom to:
- [x] talk to Data BC to see if non-truncated version can be obtained
- [x] talk to Data BC about the model changes that were supposed to done in 2020 and previous remodel excercise
- [x] identify columns and types of issues encountered with BCGW spreadsheet
- [x] provide the original spreadsheets
- [x] provide the rules when multiple versions of a row are found
- [x] determine what to do with 2 lists with the same GSC number - identify list of columns that make the row unique

**Comment by LeannePyle** [comment]
emailed 3 excel files May 24

**Comment by bferguso** [comment]
@LeannePyle  - I'm seeing data in columns after the "ADDITIONAL NOTES" field in the 2019 dataset. Can those be safely ignored?

**Comment by bferguso** [comment]
@LeannePyle , @elisabethdeom - 2019 file, special characters seem to have been mangled. All the unicode characters like ° turn into �. Is there another way we can get the data?

**Comment by bferguso** [comment]
OK, so I've had a look at the data and there is no decent unique column combination we can use to connect the separate spreadsheets. So far I'm thinking the best approach is to look for long values (> 249 characters) in the latest spreadsheet and to work our way backwards to try to fill in the blanks. I think it's going to be a potentially manual process, but I'll try to match the values up the best I can.

So far I'm seeing potential truncation as follows:
- 166 long significant_fossil_list values
- 330 long non_significant_fossil_list values
- 0 long common_names values
- 130 long detailed_location values
- 94 long location_description values
- >500 long reference_title values (106 distinct values)
- >500 long additional_notes values (125 distinct values)

In addition to that I'm seeing the following character conversion issues (as per the above comment):

**Comment by LeannePyle** [comment]
Yes, ignore columns beyond
