### ISSUE TITLE
Define attributes for fossil samples

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#129]
- [x] Taxonomic Information
- [x] Additional Identification
- [x] Fossil Part or Trace Fossil
- [x] Condition
- [x] Preservation
- [x] Quantity

**Comment by LeannePyle** [comment]
Definitions or Instructions for various notes

Taxonomic Information - Assign formal higher taxonomic name, especially if specimen is not identifiable to Genus and species name (e.g., Actinopterygii).

Additional Identification - Note any alternate scientific names (e.g., if taxon name changed over time such as Alnus crispoides = Alnus hollandiana) or informal taxonomic designation of a name (e.g., actinopterygian). Do not repeat common names here. 

Fossil Part or Trace Fossil - Note the type of fossil part or type of trace fossil (tooth, bone, fish scale, shell, leaf, needle, burrow, track, gastrolith, coprolite).

Condition - Note if specimen is complete, fragment or unidentifiable.

Preservation - Note preservation (original material, mineralization, mold, cast, imprint, compression, carbonized impression, recrystallization).

Quantity - Note how many specimens or if an assemblage is present.
