### ISSUE TITLE
Loss of special characters such as plus or minus symbol

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#130]
Check Geological Age and Detailed Location columns for loss of plus or minus symbol and degrees symbol, both changed to a symbol of "?" in a black diamond - see examples sample GSC 4046 for plus/minus and GSC Loc. C-102853 for degree

- [x] Identify columns/rows with mangled special characters
- [x] Fix special characters by applying original columns to 2022 data
- [x] Look in all columns to confirm complete
- [x] Review updated rows to verify updates (@LeannePyle)
- [x] delete double arrows symbol as it is enclosing a genus species name
- [x] em dashes can be changed to hyphens
- [x] one occurrence of 1/2 could be changed to read 4.5 miles rather than 4 1/2
- [x] could delete the ...... in the author list before "and 22 others" - changed it to .; and 22 others to maintain the semicolon separator

**Comment by bferguso** [comment]
@LeannePyle, @elisabethdeom  - I think I've been able to fix them. We just need to review to see if you want to keep the original special characters or if we should convert some of them to regular ASCII characters.

**Comment by bferguso** [comment]
In addition to that I'm seeing the following character conversion issues (as per the above comment):
- 1731 detailed_location rows with special characters
- 13 location_description values with special characters
- 0 significant_fossil_list with special characters
- 1 non_significant_fossil_list with special characters
- 155 reference_author values (1 distinct value)
- 95 reference_title values (6 distinct values)
- 0 positional_precision
- 33 additional_notes values (16 distinct values)

**Comment by LeannePyle** [comment]
let's discuss, converting symbol degree to word degree is a potential fix. Can you provide an example of the issue in the author and title value?

**Comment by bferguso** [comment]
Old values replaced with the following
additional_notes,°,29,176
additional_notes,!,1,33
additional_notes,–,2,8211
additional_notes,éè,1,233
detailed_location,°,1624,176
detailed_location,°°,2,176
detailed_location,‘’,5,8216
detailed_location,‘’‘’,3,8216
detailed_location,’’,1,8217
detailed_location,“,1,8220
detailed_location,«»,1,171
detailed_location,±,2,177
detailed_location,–,10,8211
detailed_location,½,1,189
detailed_location,é,4,233
location_description,’,2,8217
location_description,“”,1,8220
location_description,±,3,177
location_description,–,2,8211
location_description,—,5,8212
non_significant_fossil_list,·,1,183
non_significant_fossil_list,},1,125
non_significant_fossil_list,$,2,36
reference_author,…,155,8230
reference_title,’,1,8217
reference_title,’—,2,8217
reference_title,–,83,8211
reference_title,–“”,9,8211

**Comment by bferguso** [comment]
Updated script to check all columns, generated spreadsheet and sent to @LeannePyle & @elisabethdeom

**Comment by LeannePyle** [comment]
symbol translation replacements all look good, can we make the following changes: 
delete double arrows symbol as it is enclosing a genus species name
em dashes can be changed to hyphens
one occurrence of 1/2 could be changed to read 4.5 miles rather than 4 1/2 
could delete the ...... in the author list before "and 22 others"

**Comment by bferguso** [comment]
@elisabethdeom @LeannePyle  - I'd like to have a quick conversation about this today if possible so we can close this ticket.

**Comment by bferguso** [comment]
Data on Legacy. Any other issues to be handled as separate issue.
