### ISSUE TITLE
Rules for fossil name clean up Phase 1

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#131]
Pre-split cleaning
- [x] Where a colon separates “Agenus aspecies: Bgenus bspecies” treat colons like semicolons to split the values into individual entries from the main spreadsheet.  Example Gunnera superbus: Liliacidites textus
- [x] Remove trailing comma (added by Brett)

Post-split cleaning
~Where a comma occurs after two words “Agenus aspecies, Bgenus bspecies” treat commas like semicolons to split the values into individual entries from the main spreadsheet.  Example Columnella edentata, Discus whineyi~ Agreed to deal with these after
- [x] Change sp to sp. 
- [x] Change Sp to sp.
- [x] Change Sp. to sp.
- [x] Change spp to spp.
- [x] Change n. sp to n. sp.
- [x] Change cl. to cf.
- [x] Change ct. to cf.
- [x] Change et. to cf.
- [x] Change aff to aff.
- [x] Change aft. to aff. 
- [x] Change “of the group” to “cf.”
- [x] Where Genus name is alone, add “sp.”
- [x] Where Genus name includes “/” move all remaining text into the “Additional Identification Note” and mark as uncertain
Example Cercidiphyllum/Joffrea corrects to “Cercidiphyllum” and move “Joffrea” into the “Additional Identification Note”
- [x] Where name includes “/” between two or more species names, keep first species name with the Genus name and move all remaining text following backslash into the “Additional Identification Note” and mark as uncertain
Example Buchia concentrica/mosquensis corrects to “Buchia concentrica” and move “mosquensis” into the “Additional Identification Note”
- [x] Where two genus names are given as “Agenus or Bgenus”, keep first Genus name and move “or Bgenus” into the note called “Additional Identification Note” and mark as uncertain
Example Ctenis or Podozamites correct to “Ctenis” and move “or Podozamites” to the note called “Additional Identification Note” 
- [x] Where Genus and species name includes “or” between the two names, keep first Genus and species name and move all text after “or” to the note called “Additional Identification Note” 
Example “Buchia erringtoni or Buchia concentrica”, move “Buchia concentrica” to the note called “Additional Identification Note” 
- [x] Where name includes “-like”, move all text to the note called “Additional Identification Note”

**Comment by bferguso** [comment]
@LeannePyle :

> Where a comma occurs after two words “Agenus aspecies, Bgenus bspecies” treat commas like semicolons to split the values into individual entries from the main spreadsheet. Example Columnella edentata, Discus whineyi

Very few of the commas I'm seeing follow this pattern so it might best to either handle by updating the spreadsheet before or fixing it after the load. I may end up introducing more errors by trying to handle this case as part of the load.

**Comment by bferguso** [comment]
@LeannePyle - I'm seeing some rows that have the abbreviation "isp." in them. Is that correct or should they be modified? A number of rows have no space before the "sp." so I'm correcting those as well.
