### ISSUE TITLE
Missing precision column from collection event

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#145]
Current values are:
```
100m
500m
1000m
5000m
>5000m
unverifiable
```

@LeannePyle , @elisabethdeom  - Do we want a pick list for this field? Or would you like to have it as a numeric or text value?

I'm guessing it needs to be a pick list - I've done the initial implementation with it and we can alway change it if necessary.

**Comment by LeannePyle** [comment]
Yes, a picklist please, to display under or next to where inputter enters lat/long
