### ISSUE TITLE
Updates based on paleobiodb

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#163]
- [x] Leanne to update genus validation spreadsheet
- [x] Leanne to update species validation spreadsheet with corrections
- [x] Brett to update mapping table with changes additional
- [x] Apply the mapping back to original
~Load Genus/Species hierarchy~ moved to #198
~Update UI to use the controlled vocabularies~ moved to #198

**Comment by LeannePyle** [comment]
spreadsheet e-mailed

**Comment by bferguso** [comment]
This iteration in Legacy. Cleaning to continue as development proceeds.
