### ISSUE TITLE
Civic addresses should be on one card

### ISSUE THREAD

**Issue by IJGoldie** [bcgov/BCHeritage#164]
Solution is to use the trigger views to load the data into BCRHP rather than CSV.

**Comment by IJGoldie** [comment]
I think the notes field makes more sense, I'll have to confirm what the resident number refers to, but likely the same.

**Comment by bferguso** [comment]
I'm having to do some paragraph cleaning as part of this. Rich format fields (such as SOS Defining Elements and Heritage Value) have newlines in them, but in Arches rich format is HTML encoded string. I've done the minimum of changing newlines to <p> HTML format, but do we want to try to handle bulleted lists, etc. as well?
