### ISSUE TITLE
Pop-up and card display

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#169]
Items to display in the **_pop-up_** for each collection event:
Header: 
- Collection year 
- Regional District

Body:
- Detailed Location on one or two lines so we can see all of it, followed by 
- Geological Formation (shorten to Formation), 
- Geological Period (shorten to Period), and 
- List of Fossil names with .... if too long to display

In the **_cards_** 
Header: 
- same as above, 

Body: 
- Detailed Location
- Period 
- List of Fossil names

**Comment by bferguso** [comment]
@LeannePyle @elisabethdeom - I've added the missing temporal data in an unstructured way to support your meetings next week. I've made the descriptions for the map popup and cards. Hopefully that will satisfy your requirement for the time being. I'm going to mark this as ready for QA, and then we can add the structured temporal data as part of another issue.

**Comment by bferguso** [comment]
Confirmed on Legacy.
