### ISSUE TITLE
Do we need to import audit history from HRIA?

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#174]
There are audit columns in each of the HRIA tables that track when/who created and when/who last updated each record. Do we need to import this data into Arches?
- [ ] Download audit history if becomes necessary
- [ ] Archive data in "safe place" - TBD

**Comment by IJGoldie** [comment]
We'd like to retain this info, and the ability to track who makes and edits entries going forward.

**Comment by bferguso** [comment]
@emjohnst  - I don't think we need to retain the existing audit information, and any future edits in the system will be audited. Can you please confirm that that's acceptable and if so we can close this ticket.

**Comment by emjohnst** [comment]
@bferguso agreed. We are not going to retain the existing audit info.
