### ISSUE TITLE
Determine which (if any) GIS points should be imported from HRIA

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#177]
Currently using GISLATITUDE & GISLONGITUDE however these points look either very inaccurate or wrong.

**Comment by bferguso** [comment]
@IJGoldie - I'd like to resolve this at our Wednesday meeting if possible

**Comment by bferguso** [comment]
Can go to address 1441 Gladstone Avenue in Victoria and find nearby point with 38 addresses associated with it.

**Comment by IJGoldie** [comment]
The 'GIS generated' points can be scrapped entirely.

**Comment by bferguso** [comment]
Removed import of point data stored in HRIA.
