### ISSUE TITLE
Revisit BC Fossil Sample part of model

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#192]
Need to review and refine the BC Fossil Sample part of the Resource Model. Specifically we need to examine:
- [x] The relationship between Taxonomy and Sample
- [x] The location of Geological Assessment in the model (where it belongs)
- [ ] The location of Temporal Assessment in the model (where it belongs)

**Comment by LeannePyle** [comment]
Temporal Assessment was re-named Geological Age and is now showing up in the model
