### ISSUE TITLE
Determine how to present legal address information

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#207]
- [x] Decide whether the way the legal address information is presented is good or if we should have separate fields for different parts of the legal address (section, parcel, etc)

Order on LTSA site is:

1. PID (Parcel Identifier)
2. PIN (Parcel Identification Number)
3. Parcel Type
4. Plan Number
5. Regional District
6. Municipality
7. Owner Type
8. Last Modified Date (not necessary?)

I'm guessing that a function to get the rest of the information from BCGW if a PID is entered would be desirable. Not sure if the PIN is unique or not.

**Comment by bferguso** [comment]
After discussing it was decided that the fields should be split out. Pulled some format/order samples from LTSA site. Can start with that and go from there.

**Comment by bferguso** [comment]
@IJGoldie - I think we may need to delve a little bit deeper in this - the current list of legal types is: 
- Parcel
- Lot
- Plan
- Section
- Block
- District Lot
- Sub-Lot
- Range
- Township
- Land Title District
- PID
- Strata Plan
- Division
- Legal Subdivision
- Meridian
- Unsurveyed Crown Land
- Fractional
- Group

Some (many) of which are embedded in the legal description. Just need to figure out if we want to break those legal descriptions apart or leave them as a free-form text field.

**Comment by bferguso** [comment]
Option 1:
1. Filter out legal descriptions into Legal Descriptions or Notes based on content
2. Legal description in Arches to maintain historical data and could be read/write or readonly (TBD) 
3. Break the Legal Description parts into separate data entry fields in a horizontal layout

Option 2:
1. Filter out legal descriptions into Legal Descriptions or Notes based on content
2. Legal Description is loaded into Arches as is, and data entry done in this field
3. Some prompting & validation can be added to Legal Description Field

Question to answer: 
1. What is the Legal Type field and do we need it even if there is no Legal Number associated with it?
2. If loading Legal Type into Arches - put it in separate field or concatenated in the Notes field w/ Legal Number?

**Comment by bferguso** [comment]
Parsed from legaldescription:

- PLAN,973
- LOT,778
- BLOCK,710
- DL,592
- SECTION,306
- DISTRICT LOT,128
- GROUP,82
- STRATA LOT,71
- TOWNSHIP,36
- RANGE,25
- PARCEL,23
- LAND DISTRICT,22
- PART,15
- STRATA,13
- SUBURBAN BLOCK,12
- STRATA PLAN,10

**Comment by TMcFarland-Heritage** [comment]
Business area recommended option: 
Option 1:

Filter out legal descriptions into Legal Descriptions or Notes based on content
Legal description in Arches to maintain historical data and could be read/write or readonly (TBD)
Break the Legal Description parts into separate data entry fields in a horizontal layout

The following fields should be filtered out and separated into data entry fields:
PLAN,973
LOT,778
BLOCK,710
DL,592
SECTION,306
DISTRICT LOT,128

There should also be 1 field for 'other' that is open text/numbers for any other specific information to be entered. If there is room for guidance for users, it could state that the 'Other information can include township, range, parcel, strata lot, etc. or any other location based information.'
