### ISSUE TITLE
Review current list of overlays and base maps and identify missing layers

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#211]

**Comment by victoriacooper** [comment]
@bferguso what did we decide to do with x-program area tickets?

**Comment by bferguso** [comment]
@victoriacooper - I think issues that affect both business areas can have both fossils and bcrhp labels applied to them.

**Comment by emjohnst** [comment]
@bferguso can you add municipal parks to BCRHP

**Comment by emjohnst** [comment]
@bferguso are we able to use this basemap in Arches? https://catalogue.data.gov.bc.ca/dataset/bc-basemap. It has nice hillside shading and park labels and its the same one the BC Geographical Names Offices uses in their app (our Heritage Branch colleagues) https://apps.gov.bc.ca/pub/bcgnws/web/

**Comment by emjohnst** [comment]
Added file for BCRHP what overlays we'd like to keep and what info map cards should include, with links to where maps can be found. 

- [ ] Remove National Resource Boundaries
- [ ] Replace Indigenous Reserves with Indigenous Reserves and band names
- [ ] Add Cadastral Parcel Map layer with PID/PIN labels
- [ ] Add Local Trust Admin Boundary
- [ ] Add Islands Trust Admin Boundary
- [ ] Historic Trails
- [ ] heritage conservation areas
- [ ] tourism regions
- [ ] Provincial Parks
- [ ] Municipal parks

Basemaps:
- [ ] BC Basemap
- [ ] Esri world imagery or other satellite imagery

[Map Overlays and base maps.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbC9yIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--96a6a23ded9f5cac481cf7dfd227049b7715a042/Map%20Overlays%20and%20base%20maps.xlsx)

**Comment by bferguso** [comment]
@LeannePyle, @elisabethdeom - If no other overlays are necessary, or if they are addressed in a different issue please move this ticket to Done.
