### ISSUE TITLE
Update BCRHP BC Heritage Resource Details card

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#216]
Make updates to the Details card for the LG engagement sessions

**Comment by TMcFarland-Heritage** [comment]
currently have:

Site Names
Borden Number
Site Images
Civic Addresses
Registry Types
Authority
SOS Significance Description

Add: Sign Event: Start Year, Start Year Qualifier and Event

**Comment by bferguso** [comment]
Done. Only showing Construction significant event as discussed.

**Comment by KatieMcEvoy** [comment]
can we remove the registry type and have authority and protection type visible and linked? ie: you can see it's municipally designated.
@bferguso
