### ISSUE TITLE
Add PID to Details card

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#217]
Need to add PID to details card. Legal Address layout needs to be determined first.

**Comment by bferguso** [comment]
To be included w/ discussion w/ Raj.

**Comment by bferguso** [comment]
@rajpersram - Part of your details page layout discussion w/ BCRHP

**Comment by rajpersram** [comment]
Designs and layout for both the pop-up card while viewing a map, and subsequent details page are outlined in Figma '[Place Report - Redesign, HP](https://www.figma.com/file/nflhEcVKXeX3q7hmtXkCAT/ARCHES-Fossils-and-Historic-Places?type=design&node-id=35-808&mode=design&t=vfoX39xGXrFycm0u-4)' mockups. Happy to discuss any of those details on a call.

**Comment by emjohnst** [comment]
Ticket is out of date - see ticket #592

**Comment by bferguso** [comment]
Closed in favour of #592
