### ISSUE TITLE
Move note types into separate fields

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#223]
These note types need to have their own field

- [x] Condition
- [x] Fossil Part or Trace Fossil
- [x] Preservation
- [x] Quantity

Need short descriptions for each. @LeannePyle, @elisabethdeom   - Please add

**Comment by LeannePyle** [comment]
Taxonomic Information - Assign formal higher taxonomic name, especially if specimen is not identifiable to Genus and species name (e.g., Actinopterygii).

Additional Identification - Note any alternate scientific names (e.g., if taxon name changed over time such as Alnus crispoides = Alnus hollandiana) or informal taxonomic designation of a name (e.g., actinopterygian). Do not repeat common names here.

Fossil Part or Trace Fossil - Note the type of fossil part or type of trace fossil (tooth, bone, fish scale, shell, leaf, needle, burrow, track, gastrolith, coprolite).

Condition - Note if specimen is complete, fragment or unidentifiable.

Preservation - Note preservation (original material, mineralization, mold, cast, imprint, compression, carbonized impression, recrystallization).

Quantity - Note how many specimens or if an assemblage is present.

**Comment by bferguso** [comment]
@LeannePyle - The names & descriptions in this ticket are great! I'd like to move them into another ticket which addresses the contextual help and help text so we can do a full run-through of the entire application to make sure we have the right descriptions everywhere we need them.

**Comment by bferguso** [comment]
Taxonomic information has been cleaned in and imported, the following data has not:
Common Name: 21 rows
Fossil Part: 231 rows
Preservation: 4 rows
