### ISSUE TITLE
Export SIGNIFICANCE_RANKING_DETAILS for cleanup

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#229]
Need a list a terms in that category to standardize terminology for dropdown menu

**Comment by bferguso** [comment]
Implemented list and updated loads. Noticed that there was a single value starting with a lower case value.

Need to determine how to handle the `Fossil Part` and `Preservation` fields. This may cause a > 1 cardinality as we are also pulling those in from another part of the data (currently in Notes)

**Comment by LeannePyle** [comment]
words "youngest reported occurrence" should be moved into an additional detail/comment field if we have such a freeform field for significance?
Also can we add a check box called "Heritage value" ?

**Comment by bferguso** [comment]
@LeannePyle - There is no free-form field at the significance details level. Is there a reason that this isn't included? (very few times selected?)
Heritage value added.

**Comment by LeannePyle** [comment]
the "youngest reported occurrence" was a one-time phrase, we do not need this as a checkbox going forward

**Comment by LeannePyle** [comment]
the "youngest reported occurrence" was a one-time phrase, we do not need this as a checkbox going forward

**Comment by bferguso** [comment]
@LeannePyle  - Would you please identify which field you would like "youngest reported occurrence" moved into? This may need to be a manual update post-mvp but I'll see if I can move it somewhere else that will fit.

**Comment by bferguso** [comment]
Removed the vocabulary item. Need to handle data (single row)

**Comment by LeannePyle** [comment]
Noticed "Education value" is missing - can we please add that as a checkbox in the list of Significance Ranking Details

**Comment by bferguso** [comment]
"youngest reported occurrence" to be removed from data.
