### ISSUE TITLE
Import non-image digital assets

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#234]
Need to determine the LOV for document types. Current values are as follows:
```
| Content Type        | Number Records |
---------------------------------------
| Detailed Data Table | 1              |
| Document            | 3888           |
| Document, Combined  | 25             |
| Document, Other     | 24             |
| Map                 | 134            |
| Map, Detailed       | 4              |
| Map, Other          | 6              |
| Site Form           | 9              |
| Table, CMT          | 1              |
```

Document metadata to collect: 
- [x] Document
- [x] Description
- [ ] ~Date~
- [x] File metadata (size, last modified)

**Comment by bferguso** [comment]
@KatieMcEvoy  - Can you please confirm what the final list of `Content Types` should be, and how the existing values should be mapped to the new values so this issue can be resolved?

**Comment by KatieMcEvoy** [comment]
@bferguso I think it should just be:

- Document (Detailed Data Table, Document, Document, Combined, Document, Other,  Site Form, and Table, CMT )
- Map (Map, Map, Detailed,  Map, Other)

Is this also where the URLs go? if so one should be URL to website.

**Comment by bferguso** [comment]
@KatieMcEvoy - No, we'll have a different field for URLs. We may want to classify different URL types there.

**Comment by KatieMcEvoy** [comment]
@bferguso thanks sounds good.

**Comment by bferguso** [comment]
@KatieMcEvoy, @emjohnst -  I don't believe there is a date associated with the documents. Would you please confirm?

**Comment by KatieMcEvoy** [comment]
@bferguso Confirmed, there are no dates associated with the documents.
