### ISSUE TITLE
Search criteria - bounding or polygon

### ISSUE THREAD

**Issue by tzukiwsky** [bcgov/BCHeritage#242]
Limit to sites within a given area of interest defined by a bounding box, a user-defined polygon, or a polygon from a relevant map layer (e.g. first nation treaty area, proposed development area, or area of an application to a natural resource ministry).

**Comment by bferguso** [comment]
This functionality is mostly implemented. A gap analysis should be done to see if there are any specific requirements that are not supported by what has been implemented to date.

**Comment by bferguso** [comment]
Marking as closed. Any gaps to be addressed in new issue.
