### ISSUE TITLE
Abundance picklist

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#254]
Create a field for future use called Abundance of Fossil Material (at collection event level), with four choices
--there is no historic data to fill this

None/Barren
Single fossil
Few (less than five fossils)
Many (five to ten fossils)
Abundant (more than ten fossils)

**Comment by bferguso** [comment]
@LeannePyle - Do we also need an option for None?

**Comment by LeannePyle** [comment]
The None option would mean "barren" should be indicated - did we decide where and how that piece of information would display? as a checkbox? maybe the none/barren option appears just above the Abundance menu? OR should it be part of Abundance, in which case we have lots in the current dataset that are barren samples/collections
We could argue to put the Abundance with Fossil Sample as well, I would be okay with that

**Comment by elisabethdeom** [comment]
I like the idea of having a box above the Abundance section with "None/barren" that can be selected for barren samples. If we do that, can we query on that?
The Abundance piece should be at the sample level and higher levels as well (collection event, site).

**Comment by bferguso** [comment]
After discussions with Leanne, we decided it would be simpler to include None/Barren in the LOV and use a radio list for the UI.
