### ISSUE TITLE
Grant access to ARCHES to new staff

### ISSUE THREAD

**Issue by TMcFarland-Heritage** [bcgov/BCHeritage#276]
Please ensure new heritage branch staff (Katie McEvoy - KMCEVOY and Theresa McFarland - TMCFARLA) to the historic places instance of Arches.

**Comment by bferguso** [comment]
@TMcFarland-Heritage - I have updated the scripts and added you both manually to Legacy. Please have a look and let me know if either of you have any issues accessing the system.
