### ISSUE TITLE
Stratigraphy Cleanup - Header changes

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#277]
Headers on Page
- [x] Group, Formation and Member need to be multi-pick
- [x] Change “Geological Group” to “Geological Group or Lithodemic/Lithotectonic Grouping” 
- [x] Under Geological Member Uncertain, add new header called "Informal Name or Map Unit” we will move non-lithostratigraphic terms into here. This will be an LOV single only.
- [x] Add "Informal Name or Map Unit Uncertain" header as well with checkbox option
- [x] Change header name "Other Stratigraphic Name" to "Other Informal/Other Unit Name" with a freeform box

**Comment by bferguso** [comment]
When changing to the multi-pick the concepts were unlinked. This has been fixed and will be reflected on Legacy on the next refresh.
