### ISSUE TITLE
Ability to generate and export reports to reduce duplication and volume of records relating to local government sites on register.

### ISSUE THREAD

**Issue by victoriacooper** [bcgov/BCHeritage#295]
Ability to generate and export reports so we can reduce duplication of effort and volume of records relating to local government sites on register.

MVP requires ability to do basic .csv reports of enumerated attribute data. Attributes to be determined. Imogen _(Now Theresa)_ will explore the usage of this item little bit deeper. If there is pressing use, can renegotiate it.

**Comment by emjohnst** [comment]
Complete
