### ISSUE TITLE
Edits to BC Fossil Collector Resource Model Page

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#311]
- [x] 1. Move Header “Collector Last Name” to be first in the list
- [x] 2. Delete “Collector Middle Name”
- [x] 3. ~Change “Collector First Name” to “Collector Initial(s)”~

**Comment by bferguso** [comment]
@LeannePyle - where are you at with the first name vs initials decision? Just wondering if we should change this now or leave it for the time being?

**Comment by elisabethdeom** [comment]
We will have last name and first name going forward, and we leave all the historic name as initials.
