### ISSUE TITLE
Remove BCRHP spatial data from Arch BCGW push

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#318]

**Comment by bferguso** [comment]
Having a meeting w/ Peter @Data BC today. It appears there is not column isheritagesite in the All Sites layer (@bferguso  to double check). Possible options:
1. As Trimble to add a the isheritagesite column to the existing view. This may not happen until March / April
3. Use the existing Historic Places view to identify sites that should be omitted.
4. Use the new Arches view to identify sites that should be omitted.

**Comment by emjohnst** [comment]
Update - the ishistoricsite column is available and DataBC can filter on it to remove historic sites from HRIA source layer which will affect subsequent layers

**Comment by emjohnst** [comment]
This was dealt with by DataBC.
