### ISSUE TITLE
Load sites with TFM_SITE.ISHISTORICSITE = N

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#320]
Only sites where the ISHISTORICSITE is null are Arch sites. Need to load all records where ISHERITAGESITE = Y or N.

Do we want to add this flag to Arches (assuming we do). Where should we put it?
- [x] Also load data with ISHERITAGESITE = N
- [x] Add flag to staging table
- [x] Add field to BC Heritage Resource  resource model  - `Official Recgnition Information`  card Implement as a boolean.
- [x] Update loads to populate field in Arches

**Comment by bferguso** [comment]
@TMcFarland-Heritage - There is a Registry Type of "TU" in these new values. Is this a valid value, or should they be changed to something else?

**Comment by KatieMcEvoy** [comment]
TU stands for traditional use. For now they can be included. @bferguso
