### ISSUE TITLE
Look and feel

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#323]
When pages are ready for review, who will start the initial review

**Comment by bferguso** [comment]
@LeannePyle - this can happen any time. This ticket is more about general look and feel rather than order of attributes, etc. I think we were hoping to get some NRIDS support to start this process.

**Comment by LeannePyle** [comment]
need to implement look and feel work done by Raj

**Comment by bferguso** [comment]
Closing this as individual issues now need to be handled in separate tickets.
