### ISSUE TITLE
Fossil Impact Assessment page edits

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#329]
Can we make two sub-sections here with the following headers and associated instructions in the textboxes

Subsection1 - FIA Plan Reporting
- [x] Lead Paleontology Consultant Name - Choose the report author’s name or select “other” if the name you are looking for is not listed
- [x] FIAPlan Report Number - FMO assigns FIAPlan Number 
- [x] FIAPlan Report Title – Enter the report title
- [x] Consultant Report Number - If available, enter the number assigned to the FIA Plan Report by the consultant
- [x] FIAPlan Document – upload report pdf
- [x] FIAPlan Recommendation – FMO use only
- [x] FIAPlan Internal Notes – FMO use only - Describe key findings and conditions 
- [x] FIAPlan Approval - Yes or No
- [x] FIAPlan Response - response with checklist with the following elements

FIA plan activities are subject to the following requirements to conduct the FIA:
how can this be built/displayed? There are 6 lines of text to include

Subsection 2 - FIA Reporting
- [x] Lead Paleontology Consultant Name - Choose the report author’s name or select “other” if the name you are looking for is not listed
- [x] FIA Report Number - FMO assigns FIA Number (generated by Arches)
- [x] FIA Report Title – Enter the report title
- [x] Consultant Report Number - If available, enter the number assigned to the FIA Plan Report by the consultant
- [x] FIA Document – upload report pdf
- [x] FIA Recommendation – FMO use only
- [x] FIA Determined Level of Risk
- [x] FIA Internal Notes – FMO use only - Describe key findings and conditions 
- [x] FIA Approval - Yes or No
- [x] FIA Response – response with checklist  (4 lines/options to include)

**Comment by bferguso** [comment]
@LeannePyle  - Are the FIA / FIAP recommendations the recommendations that come out of the reports? Or are they something else assigned by FMO?

**Comment by LeannePyle** [comment]
Recommendations will be brief summaries of report findings, so for internal use only by FMO.
