### ISSUE TITLE
Chance Find Protocol headers to add

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#330]
Author - Choose the report author’s name or select “other” if the name you are looking for is not listed
- [x] CFP Number - FMO assigns CFP Number – generated by Arches  (CFP-2023-001)
- [x] CFP Document – upload protocol pdf
- [x] CFP Response – response back to author
- [x] CFP Internal Notes – FMO use only
- [x] CFP Approval Date

**Comment by bferguso** [comment]
@LeannePyle - is this the comprehensive list of attributes for CFP? Can we have a look at the CFP document? Should/could some or all of the CFP document content be entered directly in Arches?
