### ISSUE TITLE
Provide best source for LG and related employees data

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#334]
If we want to do a data load of the LG lists and associated employees/resources we need to determine what the best source is for this. Your LG spreadsheets? Somewhere else?
- No list of LG employees - will be added to system as submissions come in

**Comment by bferguso** [comment]
I've loaded a list of government names from the HRIA Authority table. This will likely need some standardization and cleanup. If I should be using a different source please point me in that direction.

**Comment by emjohnst** [comment]
Post mvp to look at Local government names against civic info bc information
