### ISSUE TITLE
Appearance of Landing Page

### ISSUE THREAD

**Issue by TMcFarland-Heritage** [bcgov/BCHeritage#335]
Update the appearance of the BCRHP landing page based on heritage input.
- @KatieMcEvoy will suggest images for landing page
- Theresa to update wording changes: Request change 'BC Registry of Historic Places' to 'BC Register of Historic Places'. Other requested changes pending...

**Comment by bferguso** [comment]
@KatieMcEvoy, @emjohnst  - I think this is done? The text change is completed.

**Comment by emjohnst** [comment]
Yes this is done for mvp, will probably have more changes before public site.
