### ISSUE TITLE
Define types of geometries defined in the IPA Project Details

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#341]
A select list has been added to the IPA project details Spatial Geometry card (boundary, building, access point, etc). Currently using the default Geometry Qualifier list. 
- [ ] Need to determine if this is sufficient, or does another LOV need to be created for this. 
- [ ] If another list needs to be created, define the values in the list

**Comment by LeannePyle** [comment]
From existing default terms related to Spatial Location, we would like the following in the LOV, with this wording:
access point
buffer polygon
centre point
footprint polygon
perimeter polygon
datum point
