### ISSUE TITLE
Add ability to store external URLs to sites

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#345]
Need to add a place to add URLs to a site:
- Historical Society w/ Information on Site
- Historical Society Site Management website
- LG Heritage website - General heritage website

Need:
- [x] URL
- [x] URL description
- [x] #346
- [ ] Have done initial attempt at classifying external URLs into the given categories. @TMcFarland-Heritage to review.

**Comment by KatieMcEvoy** [comment]
tested and got an error message - can we make it so we don't need to input https?
![image](https://github.com/bcgov/BCHeritage/assets/123397964/870ec931-d77a-4540-9957-f75db06d649b)
It doesn't appear the historic URLs were loaded from HRIA

**Comment by bferguso** [comment]
@KatieMcEvoy - technically URLs are not valid without the https or http prefix. Browsers try to complete that for convenience, but the URL should have those as one is secure and one is not. We could look into automatically prefixing https:// on the URL strings, but lets do that as a separate issue.

Moving back to Completed in Dev and will move back to Review/QA once I've refreshed Legacy with the historic URLs.
