### ISSUE TITLE
@TMcFarland-Heritage to define requirements / types / LOV lists

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#346]

**Comment by TMcFarland-Heritage** [comment]
Defining requirements for URL field(s):

	URL field (for entering the web address)
	Description field (for providing a brief description of the website being linked to)
	Type field (drop down menu with the following options)
•	Federal Website
•	Provincial Website
•	Territorial Website
•	Historic Place Website
•	Local Government Website
•	Other website

NOTE: order of how fields should appear on a 'site record' page will be in another Ticket
