### ISSUE TITLE
Define criteria for site to be visible to public

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#353]
Criteria for a record to be 
- [x] Site is Basic Record - Approved; Full Record - Approved 
- [x] Site is not restricted
- [x] Site is officially recognized
- [x] Site registration type is Registered or Federal Jurisdiction

**Comment by emjohnst** [comment]
@bferguso Can this be closed in favour of #698 ?

**Comment by bferguso** [comment]
Closing as this issue has been resolved.
