### ISSUE TITLE
BC Information Resource Model renaming and headers

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#358]
Header Names and Order
- [x] Re-name as BC Fossil Reference Information Resource Model (BC Fossil Reference Information)
- [x] Header = Title
- [x] Subtitle text = Enter the source’s title in sentence case and select type of that title.
- [x] Title  – freeform box 
- [x] Header = Date `BF - Can this be "Publication or Report Year" to be more specific?` - YES
- [x] Subtitle text = Select the year of the report or publication.
- [x] Year of Reference --Calendar box to select a year `BF - "Year of Publication"?`
- [x] Header = Authorship - `BF - Should we reuse/repurpose BC Fossil Collectors resource model? Seems to be an overlap. Does this list need to be ordered?`
- [x] Subtitle text = Select the author(s) or corporate author.
- [x] Author Resource list multi-pick (Filter by Actor type)
- [x] Additional unlisted authors
- [x] Header = Reference Details
- [x] Subtitle text = Enter a description for the reference.
- [x] Type `BF - Can be "Publication Type"?`

@LeannePyle, @elisabethdeom to complete list for LOV

List of Publications types/categories - listed in e-mailed spreadsheet 2023-03-06_fossils_references

1 - Journal
1 - Federal Government
1 - BC Government
1 - Institutional
1 - Society
1 - Book
1 - Thesis
1 - Industry (Unpublished)
1 - Research (Unpublished)
1 - Website
1 - Other

1- Journal
2- Volume / Publication Number
3- Journal article (default) - not sure we need this - title will be listed elsewhere?

1- Federal Government
2- Unpublished Geological Survey of Canada Report
2- Geological Survey of Canada Bulletin
2- Geological Survey of Canada Memoir
2- Geological Survey of Canada Paper
2- Geological Survey of Canada Open file
2- Geological Survey of Canada Current Research
2 - National Research Council of Canada Monograph
2 - NRC Research Press

- [x] Journal or Type Name `BF - Publication Type or Name? Sent list by email`

- [x] Volume / Publication Number
- [x] Page Range
- [ ] ~Type Number – instruction enter bulletin or paper number~
- [x] Digital Object Identifier  – DOI – help = set of characters attached to a journal article
- [x] Header = Information Carrier 
- [x] Subtitle text = Upload pdf(s) of the reference.
- [x] Header = Keyword - could be built out in the future 
- [x] Copyright information and LOV - look at HER, or others for example list
- [x] #486
- [x] Look at cardinality of the loads - looks like unnecessary duplicates

Copyright LOV:
All rights reserved == do not distribute,
copyright license == author permission required,
Public Domain == unlimited distribution permitted

All Unpublished GSC reports should be "Copyright license", "Allowed to distribute" = Yes, and Agreement Text = "GSC has given FMO authority to distribute at their discretion"
Remove "Distribution Permitted" node - inference from Copyright type.

**Comment by bferguso** [comment]
@LeannePyle - For author names, wondering if we should use the same person list as the Collectors list we've created - seems like there is a relatively large overlap.

**Comment by LeannePyle** [comment]
Not sure we need a hierarchy LOV for any other publication type than "Federal Government" - I suggest changing this from "Geological Survey of Canada" to also include 2 kinds of NRCan publications.

For journals, I think just a picklist of what we have in the historical set for now, without a hierarchy of volumes, with a choice of "Other" to add something new or different for future inputs

**Comment by bferguso** [comment]
@LeannePyle, @elisabethdeom - There are 19 publication references with pages listed as `49-57, 65-74, 87`. Do you want the model to support that or can we simplify as 49-87? This type of page listing is only for one publication with the MJO prefix.

**Comment by LeannePyle** [comment]
Those are not page numbers, the whole report name is an odd one: "MJO 81-38-47, 49-57, 65-74, 87"

**Comment by bferguso** [comment]
Need to discuss how to handle FO- type reference sources. If these are 1:1 w/ the title then perhaps these should be used as a source identifier rather than part of the publication hierarchy.
