### ISSUE TITLE
Organizing Publication Resource Model

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#368]
- [ ] One change/questions: Can Parent Publication header become a subheader within Reference Details.

In entering a new set of publication info, the mechanics would be article/book/report title = Title, then Authors, then year, then Details which would be Journal Name, volume, page range, or for something different, selecting Publication Type - GSC Memoir, its number or volume, then its page range.

**Comment by bferguso** [comment]
@LeannePyle - This has been reworked. Would you please have a look to see if the current layout works for you?

**Comment by bferguso** [comment]
@LeannePyle confirmed completed.
