### ISSUE TITLE
Front page updates

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#372]
- [x] The BC logo should be clickable and bring you to provincial website: https://www2.gov.bc.ca/gov/content/home 
- [x] All BC Registry of Historic Places need to be replaced with BC Register of Historic Places
- [x] Need short description of BCRHP for subtitle on 1st scroll page: "The BC Register of Historic Places records historic places that have been officially recognized by the provincial, federal or local / regional governments for their heritage value."

**Comment by KatieMcEvoy** [comment]
Tab in browser still says BC Registry... everything on the actual page is good.

**Comment by bferguso** [comment]
Fixed.
