### ISSUE TITLE
Primary Descriptor of Volumes/etc should include the Parent name

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#382]
Volume numbers primary descriptor is unclear without the associated Journal, Journal (or parent) should be included as part of the primary descriptor name

for example: v. 5 of Science journal would be represented as "Science v. 5"

**Comment by LeannePyle** [comment]
do not see a field for entering or selecting volume number

**Comment by bferguso** [comment]
@LeannePyle  - The volume number goes in the `Title of the Work`, with the parent being the publication. eg: https://dlvrapps.nrs.gov.bc.ca/int/arches-fossils/report/703fc18d-fffc-479e-83b9-2d2be4852b15

**Comment by LeannePyle** [comment]
Still having an issue in seeing a list of volume numbers with associated journals

**Comment by bferguso** [comment]
The descriptors function is doing the right thing. A change in Arches Core stopped the descriptors from being recalculated if there were none. Marking this as complete. Need to address the pick list search issue in a separate ticket.
