### ISSUE TITLE
Change information displayed on map popup

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#392]
- [x] ‘Report’ change clickable word to ‘Site Record’
- [ ] #457
- [x] Should include
    - [x] Site name
    - [x]  Borden Number
    - [x]  Address
    - [x]  Protection Type (to be renamed to ‘recognition type’)
- [x] Remove, if possible:
    - [x] Resource Model and 
    - [x] Resource Instance ID

**Comment by bferguso** [comment]
Duplicate of #452

**Comment by KatieMcEvoy** [comment]
I'm not seeing the protection type on the pop-up

**Comment by bferguso** [comment]
Duplicate of #452
