### ISSUE TITLE
Change information displayed on search results card

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#393]
- [x] Borden #
- [x] Name
- [x] City
- [x] Protection Type (-> Recognition Type)
- [x] Date Built

**Comment by bferguso** [comment]
Duplicate of #454

**Comment by KatieMcEvoy** [comment]
No recognition type visible

**Comment by bferguso** [comment]
I'm seeing this - eg DeSa-3

**Comment by bferguso** [comment]
Missing recognition types were caused by an incorrect language code for a number of the values. This has been fixed and will rectify the missing values on reload.
