### ISSUE TITLE
Handle when description exists in both image and file metadata

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#395]
There are some images that have a description in both the site images table and the file metadata table. Need to determine what we should do with this. Options:
1. Use one or the other
2. Concatenate them

Use the Site Images description over the file metadata. Loss of file metadata description is fine.

This turned out to be not just file & image descriptions, but in some cases multiple image descriptions too. As such I've included 2 fields: 1 with the image description which has the first (image) description and the second field holds the remainder of the descriptions.

**Comment by bferguso** [comment]
Currently loading both for review. Set the File Description to readonly.

**Comment by KatieMcEvoy** [comment]
Let's keep both.
Can we rename Additional Description "Caption" and use it as the image caption? @bferguso
