### ISSUE TITLE
Validate HRIA URLs and remove broken links

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#396]
While importing the External URLs (#345) we noticed that many of them seem suspect (eg http://members.shaw.ca/j.a.brown/SchoolsTo1900.html#10NAME). Suggesting that we:
- [x] Validate each of the URLs programmatically to ensure they are valid and
- [x] Remove invalid URLs

@TMcFarland-Heritage to confirm 
- [ ] what should happen with invalid URLs
- [ ] Should this be part of MVP?

**Comment by emjohnst** [comment]
This task is complete.
