### ISSUE TITLE
Identify HRIA BCGW layer

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#404]
Currently only appear to have oracle_sde format. 
- [ ] See if the following layers can be published as a wms:
- [ ] https://catalogue.data.gov.bc.ca/dataset/archaeology-known-sites
- [ ] https://catalogue.data.gov.bc.ca/dataset/archaeological-study-areas
- [ ] https://catalogue.data.gov.bc.ca/dataset/archaeological-overview-assessments

**Comment by bferguso** [comment]
These should be available via WMS via different protected URL. Submitted an issue to Data Services Client Hub.

**Comment by emjohnst** [comment]
I've asked DataBC this question in a ticket. Given their response time and backlog I suggest we move the WMS idea to next release if we hear back and in the meantime do a data download if Archaeology Branch is okay with that.

**Comment by emjohnst** [comment]
Decided to do direct link to HRIA
