### ISSUE TITLE
Review files missing from HRIA

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#407]
Some files/images exist in the HRIA file system but do not have associated records in the database. Many of these are likely to not be desireable in Arches, but they could (should) be reviewed and added directly into Arches post MVP.

The images were extracted as part of of the ETL but were not imported as they were not linked.
- [x] #408
- [x] #409
- [ ] HB to review the missing files post-mvp to determine which if any to be loaded directly into Arches.

**Comment by emjohnst** [comment]
Dealt with in other tickets.
