### ISSUE TITLE
@TMcFarland-Heritage to store the files & associated spreadsheet for later processing

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#409]
Images missing from the standard HRIA filesystem need to be added as a post-MVP task. The list of missing files sent to @TMcFarland-Heritage is to be stored in a safe place and then manually added after MVP.

**Comment by bferguso** [comment]
@TMcFarland-Heritage confirmed in an email on 2023-04-14 that the files have been stored for processing post-MVP.

**Comment by KatieMcEvoy** [comment]
Z:\Heritage_Branch\@ops\HPI\REGISTRAR\ARCHES\BC Register\Images info
