### ISSUE TITLE
Handle image link discrepancies

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#415]
Some of the HRIA images were stored in a directory that didn't match the borden number. Need to address these records manually to determine what site they should be associated with.

The sites in question are:
|Borden Number| Directory|
|----------------|----------|
|DcRu-693|images/D/c/R/u/|
|DdRu-127|images/D/d/R/u/|
|DhRr-118|images/D/h/R/r/|
|DjSg-13|images/D/c/R/t/281/|
|DjSg-13|images/D/c/R/t/281/|
|DhRo-78|images/D/h/R/o/86/|
|DcRt-281|images/D/j/S/g/13/|

**Comment by emjohnst** [comment]
Dealt with.
