### ISSUE TITLE
Handle image and document attribute cardinality issues

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#416]
Some linked files are referred to in multiple places in HRIA and as such some of them have unexpected multiple attributes (title, description, etc). The data loaded into Arches is the first of each attribute. In the case of description of images, we have added a second description field to add descriptions 2-n. Other attributes are of lower volume that will be more efficient to review them manually after MVP.

| Attribute | records with duplicates |
|-----------|-------------------------|
|descriptions (images) | 4400 |
|descriptions (documents) | 21 |
|file_type |  28|
|title |  10|
|image_type |  0|
|imagedate | 4|
|photographer |  0|
|copyright |  2|
 

_*File Type duplicates*_
DcRt-158
DcRu-780
DcRu-785
DdRu-90
DgRj-8
DgRk-7
DgRs-70
DgRt-23
DgRx-86
DgSj-12
DgSj-15
DgSj-8
DgSk-80
DhRq-55
DhRs-574
DhRs-728
DhRx-64
DiQv-12
DjQe-2
EiRn-6
EjQd-2
FlRr-8
FlRr-9
FlSb-56
GbTk-1
HgRh-1

_*Title*_
DcRt-276
DcRt-277
DcRt-280
DcRt-281
DcRu-1434
DdRv-43
DeRt-23
DhRo-86
DhRs-1394
DjSg-19

_*Image Date*_
DcRt-276
DcRt-281
DhRo-86
DjSg-19

_*Copyright*_
DcRt-281
DcRu-1434

**Comment by emjohnst** [comment]
This was handled in data transfer.
