### ISSUE TITLE
Research Permit Request Order and mandatory fields

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#432]
Needs a how-to added

Order as below with some re-naming and fields listed to mark * for mandatory

- Project Details
    - Project Initiator – mark as mandatory
    - Make Project Initiator appear first – mark as mandatory

- Contributor Resource Model
    - Company or Individual – already marked as mandatory
    - Rule: if click “Company”, then “Company Name” is mandatory
    - Rule: If click “Individual”, then “Associate Company” will appear, but be optional
    - Role – mark as mandatory (for all occurrences of Contributor)
    - Last Name – mark as mandatory
    - First Name – mark as mandatory
    - Start Date – delete within Project Initiator page
    - Contact Email - mark as mandatory --what is languages box here?
    - Contact phone number – mark as mandatory
    - Inactive – needs a subtitle to explain and be only visible by FMO
    - Associate Company – add subtitle to explain “click the company you work for”
Note: changed "Company" to Origanization to make more general. Could be Company, Government Body, First Nation, Institution. Decision was made to not capture the type of organization but this may be necessary if LOVs need to be filtered by organization type (eg in FN communication logs)

- Project details (continued)
    - Project Start Date – mark as mandatory
    - Change "Project Start Date" to Proposed Project Start Date 
    - Project End date
    - Project Site
        - Location Description – mark as mandatory
        - Spatial Location – mark as mandatory
        - [ ] #463

- Research Request Process – reorder this page
    - Research Plan
        - Research Plan Title – mark as mandatory
        - Research Plan File – mark as mandatory

- RP FMO Assessment – change to Research Plan FMO Assessment
    - Approval Status – ~mark as mandatory~ Not doing this as 3rd "unknown" state is needed
    - Change Approval Status to “Request Review Status”
    - ~Change “accepted” to “received”~ This is inherent in the user uploading the file
    - Add a checklist of park, industrial activity incompatible, on private land 
    - Research Plan Number – mark as mandatory
    - Internal Notes
    - FMO Plan Response

- RP First Nation Engagement - change to Research Plan First Nation Engagement
- RP First Nation Engagement - move this to come before the RP FMO Assessment
--correct typo under Communications Log “Communication Type” 
    - Communication type (should there be a LOV here for email, phone, text, letter, face-to-face)
    - Change Email Attachments to “Attachments”
    - Communication Initiator – dropdown for IPA? Change to FMO or Researcher - Changed this to a boolean "FMO Initiated" or "First Nation Initiated"
--a bunch of boxes under this to delete
    - FMO Contact – not visible, change to FMO Contact Person
    - Change Research / First Nation Contact to “First Nations Contacted”
    - Is there an option for Add here for multiple communications with multiple Nations?

- Final Research Report – reorder this page and change to “Research Reports”
- Final Research Report page – rename from “Impact Mitigation Plan”
    - Final Research Report Title – mark as mandatory
    - Final Research Report File – reword from “Final Report File” and mark as mandatory
- Change RP FMO Assessment to “Final Research Report FMO Assessment” and reorder
    - --something to direct them back to record Collection Events??
    - Approval Status
    - Internal Notes
    - FMO Response
 
- Communication Log
    - --needs review of items here, no option for Research in the Assessment Phase LOV

**Comment by bferguso** [comment]
@LeannePyle - For the FInal Research Report section:
1. Would you like everything but the 2 fields listed (Title and File) removed?
2. For the "Final Research Report File" - how many documents should be allowed and what format should they be in?

**Comment by LeannePyle** [comment]
1. Yes, only two fields under Research Plan called Research Plan Title and Research Plan File - and wanted this moved up to be first in the list under the Research Request Process
2. Can we have up to 4 allowed as pdfs. This gives room for a final report but also other potential deliverables resulting from the research.
