### ISSUE TITLE
BC Fossil Publication - edits and mandatory attributes to mark

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#436]
- [x] Title – mark as mandatory
    - [x] --Change to “Title of the Work”
    - [x] --add placeholder “Enter the full title of the journal article or report”
- [x] Year of Publication– mark as mandatory
- [x] Publication Type– mark as mandatory

- [x] Journal or Publication Name – mark as mandatory
    - [x] --LOV needs to be simplified – pointing to wrong thing as titles of reports not volumes - BF: Added filter to only show types of "Journal" or "Volume / Publication Number"
    - [x] --where to put volume number when this is selected? BF: Publication number is part of the Hierarchy. Need to change the display descriptor function so a publication number shows the parent Journal name
    -
- [x] Authors – mark as mandatory
    - [x] --need to be last name first in the LOV
- [x] Copyright Type – mark as mandatory
    - [x] --LOV missing here
-
- [x] What is Historical Values - BF - Values in the spreadsheet that will not be entered in future records

**Comment by bferguso** [comment]
@LeannePyle - Maybe we should open a new issue for the Reference Link section? Seems like there's still a lot to unpack there.

**Comment by LeannePyle** [comment]
Agree - we need to discuss how this will work - I'll make a ticket

**Comment by bferguso** [comment]
@LeannePyle - For the Year of Publication - Journals are published across multiple years. Do we want to just put the first year of publication there for Journals? For the existing data we could use the minimum publication date as a starting point. Created another issue here: #478
