### ISSUE TITLE
BCRHP Complete form for S3 Storage

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#443]
Form is here: 
https://apps.nrs.gov.bc.ca/int/jira/servicedesk/customer/portal/1/create/701

Look for Object storage on this page for references:
https://apps.nrs.gov.bc.ca/int/confluence/display/OPTIMIZE/Overview%3A+Optimization+Products+and+Services

**Comment by TMcFarland-Heritage** [comment]
S3 Storage needs to get up and running. Discuss with (new?) PM next steps to do this @KatieMcEvoy

**Comment by bferguso** [comment]
@KatieMcEvoy - did you get anywhere with this?

**Comment by KatieMcEvoy** [comment]
@bferguso not so far. I asked Baldeep to look into some things because TACS can't request it.
