### ISSUE TITLE
Geometry Qualifier - list needs to be reviewed and updated

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#463]
This was identified when reviewing the Research Permit resource model, but the list should probably be the same for all geometry qualifiers in the system. Need to:
- [x] Remove any values that are not relevant to FMO
- [x] Ensure wording works for relevant values
- [x] Add any values that may be missing

Once list has been defined 
- [x] @bferguso to update the values in the RDM

**Comment by LeannePyle** [comment]
From existing default terms related to Spatial Location, we would like the following in the LOV, with this wording:
access point
buffer polygon
centre point
footprint polygon
perimeter polygon
datum point

**Comment by bferguso** [comment]
Updated values in RDM
