### ISSUE TITLE
Add authority info to details page

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#467]
Add 
- responsible gov't and 
- protection from date to details screen

Format should be 
`Municipal: Victoria 2023-03-01`

**Comment by bferguso** [comment]
@rajpersram - For your BCRHP details page discussion

**Comment by rajpersram** [comment]
These changes have been reflected in the layout for the [BCRHP Place Report mockup on Figma](https://www.figma.com/file/nflhEcVKXeX3q7hmtXkCAT/ARCHES-Fossils-and-Historic-Places?type=design&node-id=35-808&mode=design&t=p7t7Y72FmQA15iZz-4).

I wasn't able to access the details pages in either ARCHES instances so the Government Authority section might need to be reordered.

**Comment by emjohnst** [comment]
Ticket is out of date - see ticket #592

**Comment by bferguso** [comment]
Closed in favour of #592
