### ISSUE TITLE
Clean address information after MVP

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#469]
Multiple and inconsistent civic and legal addresses exist in HRIA. Cleaning has started but need to see if it can be further tuned. Need to:
- [x] @bferguso  Provide list of information to @KatieMcEvoy in spreadsheet format
- [x] @KatieMcEvoy to see if there are patterns that we can use to further clean
- [ ] Is there a way to get civic address from Canada Post or other source via PID / etc? Or to do fuzzy lookup?

There are 1919 sites with duplicate address. Options are:
1. Go into PROD as is and clean later (data entry)
2. Try to refine cleaning before PROD
3. Go into PROD as is and try to develop a semi-automated process to reduce manual effort

**Comment by KatieMcEvoy** [comment]
We should do option 3.
