### ISSUE TITLE
Official Recognition Details Act Field

### ISSUE THREAD

**Issue by KatieMcEvoy** [bcgov/BCHeritage#504]
Chaining logic between widgets like this requires writing some custom code. 
- We could have a single pull down list that contains all combinations available. 
- It looks like if any of the levels (legal instrument, act section, protection type) is entered, the other levels must also be entered. Is that a valid assumption?

Hierarchy is:
1. Authority
2. Legal Instrument
3. Act Section
4. Recognition Type

- [x] Create Legislative Act resource model
- [x] Update SQL scripts to populate Legislative Act resource model
- [x] Update Heritage Site resource model to reference Legislative Act resource model and remove individual hierarchy components
- [x] Update SQL scripts to populate Legislative Act field
- [x] Verify Legislative Act resource data (@KatieMcEvoy, @emjohnst)
- [x] Apply corrections to data

Starting assumption is all levels must be entered.
Will capture start & end dates.

**Comment by KatieMcEvoy** [comment]
Can the Act field be a drop down informed by the selection in the Legal Instrument field and the recognition type be a drop down informed by the selection in the act field?

**Comment by bferguso** [comment]
@KatieMcEvoy
- Should these also be linked to the Authority (Municipal, Federal, Provincial)?
- Do you want to capture the start/end dates or track active/inactive for the act sections?
- There are 2 ways we can implement this hierarchy - as a LOV in the Reference Data Manager, or as another Resource Model. If you would like to collect any extra information about any of these values (explanatory notes, validity start / end dates or active / inactive) then we should do it as a Resource Model. If not, then we should have a look at how you'd need to manage this list and make a decision that way.

**Comment by KatieMcEvoy** [comment]
@bferguso 

- Yes the should be linked to the authority
- Yes we should capture the start/end dates
- I guess this should be another resource model then?

**Comment by bferguso** [comment]
@KatieMcEvoy, @emjohnst - Just loading data into the new resource model - can you please confirm if these values are valid?
1. authority: `Bylaw No. 13-086`, `Bylaw No. 14-058`, `Bylaw No. 18-113`, `Bylaw No. 13`
2. Legal Instrument: `Community Charter`
3. Protection Type: `Area Designation`

**Comment by KatieMcEvoy** [comment]
1. authority: no these are not valid. do you mind sending the borden numbers associated with them?
2. . Legal Instrument: Community Charter - yes this is valid
3. Protection Type: Area Designation - it doesn't look like it but could you send the borden number(s) associated with it so I can check?

**Comment by bferguso** [comment]
Information sent by email.

**Comment by KatieMcEvoy** [comment]
- Invalid bylaw entries have been corrected.
- Area Designation was used in a special case under and act that was the predecessor to HCA. Please leave as is.

**Comment by emjohnst** [comment]
Sent an excel of which Legislative Acts to clean up 
Also working on validity dates and created post mvp ticket #597 to add fields to legislative act resource model

**Comment by bferguso** [comment]
Needed to add the following Recognition Type values:
Area Designation
Heritage Alteration Permit
Notation of Interest
 
Needed to rename the following Recognition Type values:
Other Prescribed Property -> Other Prescribed Heritage Property
Provincially Recognized Heritage Site-> Provincially Recognized Heritage

**Comment by bferguso** [comment]
DLVR refreshed. @emjohnst, @KatieMcEvoy - if the data looks good in DLVR I'll refresh TEST with it.

**Comment by emjohnst** [comment]
@bferguso this issue seems complete?
