### ISSUE TITLE
List of Resource Model Names and Icon Suggestions

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#505]
For Resource Model Names, the list shows where to remove prefix "BC" or "BC Fossil", and suggestions for icons:

- [x] (Delete BC) Fossil Collection Event – keep suitcase icon
- [x] (Delete BC Fossil) Contributor – keep person icon
- [x] Change BC Fossil Public Submission  to “Reported Fossil by Public” – keep envelope icon
- [x] (Delete BC Fossil) Publication – replace with book icon
- [x] (Delete BC) Fossil Sample – replace with tags icon
- [x] (Delete BC) Fossil Site – replace with compass icon
- [x] (Delete BC) Fossil Storage Location – keep museum icon 
- [x] (Delete BC) Fossil Type – add leaf icon
- [x] (Delete BC) Important Fossil Area – replace with sitemap icon
- [x] Industry Project Assessment – add diamond icon
- [ ] Provincially Protected Fossil Site – keep site icon
- [x] Research Permit Request – change to “Research Permit” – add pencil icon

**Comment by bferguso** [comment]
@LeannePyle - These look good. The only suggestion I'd make is changing `Reported Fossil by Public` to `Public Fossil Report`. Does that work for you?

Also - Do you want to leave the `BC Fossil Project Sandbox` name the way it is?

**Comment by LeannePyle** [comment]
Yes - leave BC Fossil Project Sandbox

Keep "Reported Fossil by Public" please

**Comment by bferguso** [comment]
@LeannePyle  - OK, but I feel like the "Reported Fossil by Public"should be less sentence-like. Typically it is a good idea to avoid connecting words to keep it concise.
