### ISSUE TITLE
Front Page text

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#508]
First draft for mvp created and e-mailed for input- will need future additions for external users with suggestion of adding some diagrams about the data structure (e.g., collection event falling within fossil site)

**Comment by LeannePyle** [comment]
Draft of revised text e-mailed to Brett to add

**Comment by LeannePyle** [comment]
Draft of revised text e-mailed to Brett for him to add

**Comment by bferguso** [comment]
@LeannePyle - just to confirm - you would like the existing Jurisdiction and Important Fossil Areas sections removed?

**Comment by LeannePyle** [comment]
That is correct - but we will leave the Mobile information there for now
