### ISSUE TITLE
Provincial Park names

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#511]
- [ ] Identify Zoom level at which names appear rather than have all appear upon opening overlay
- [ ] ~Change ALL CAPS to sentence case~ - This data comes from BCGW, leave for now

**Comment by bferguso** [comment]
Changed MinZoom = 7 to show labels closer in. ~Could look into making this variable based on size of park.~
Zoom based on attribute data not possible. We are just using what text is available in the BCGW layer so let's leave that for now.
