### ISSUE TITLE
Can we Spell out FRPC in Overlays menu?

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#513]
Is it too large for the Legend to spell out? 

In two places, spell out 

- [ ] Fossil Resource Potential Classification Bedrock 

- [ ] Fossil Resource Potential Classification Overburden

**Comment by bferguso** [comment]
I think it's too long for the the layer names, but we can spell it out in the Legend.

**Comment by bferguso** [comment]
This has been spelled out in the legend.
