### ISSUE TITLE
Fossil Resource Potential Classification (FRPC) overlay Colour choice 

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#515]
- [ ] Existing colours for High, Medium, Low, Very Low for FRPC BR (bedrock) layers need to stand out more (?increase opacity) 
- [ ] Dark purple for High is good, but could Medium differ more, and then use more of the "sand" colours for the Low and Very Low?

We will need to instruct users to have FRPC  overlay above Bedrock Geology - turning on both causes FRPC layer colours to be more dull

Primary need is for users to see the outlines of geological units that have high/medium/low potential for impact to fossils. Users also need to generate a map with the geological bedrock names.

**Comment by rajpersram** [comment]
FRPC BR has been adjusted from an opacity of 0.4 to 0.6, making it more opaque and visually impacting. Perhaps this scheme resolves the clarity of the medium layer and improves the lower colours? I believe the 'sand' is just the background map and not representative of a bedrock layer as they are all shades of purple and blue. Please let me know if the updates help with differentiating the layers visually.

**Comment by LeannePyle** [comment]
Yes, looks much better with this change - to my eye, high is now a more solid purple and lower colour are improved
