### ISSUE TITLE
Update Local Government Names in Resource Model

### ISSUE THREAD

**Issue by KatieMcEvoy** [bcgov/BCHeritage#517]
Use Civic Info BC's Directories to validate and update local government names, types, and addresses. https://www.civicinfo.bc.ca/directories

1. Review directory lists for Municipalities and Regional Districts and Island Trusts
2. Search in Arches for existing "Government" resource
3. If none exists, create new
4. If it exists, verify government name, type, and office address (ignore government location for now)
5. Note that Civic Info BC includes type in brackets after name and there is a distinction between "District" and "Regional District".
6. Note that any cities with the same name (For Example, North Vancouver) one of the Names should contain the type, for example North Vancouver, and North Vancouver District.

**Comment by bferguso** [comment]
We can change the primary descriptors function to include the government type after the name in the title, which would add that information in the drop down menu. Once that is done, can the validation be done manually? There is no obvious API in the link in the description, and it would likely take more time to create an automated validation process than to do a manual check.

**Comment by KatieMcEvoy** [comment]
Done entering all Regional Districts and Municipalities.
@bferguso @emjohnst Should we do the same validation process for the addresses as in previous sections? I entered them as they appeared on civic info but they are in a different format from the other sections.

**Comment by emjohnst** [comment]
@KatieMcEvoy I think it's fine for this section to leave as entered

**Comment by KatieMcEvoy** [comment]
Complete - closing issue
