### ISSUE TITLE
Map info not appearing for Site

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#533]
DhRs-1396 record isn't appearing with map info in Arches, but is mapped in HRIA. Can you look into why this site's location info might not have transferred into Arches?

**Comment by bferguso** [comment]
@emjohnst - If it was registered relatively recently it's probably because I haven't refreshed the BCRHP map from the BCGW recently.

**Comment by emjohnst** [comment]
Yes it was, end of December 2022. Thanks for clarifying - was just confused why the site was in there but not map info.
