### ISSUE TITLE
Multiple Polygons

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#534]
Checking that multiple polygon sites are showing correctly in Arches. So far these look to be coming across on the map correctly to me:

FgRj-1 Barkerville - two polygons
DhRs-1370 - two parcels mapped together
DcRt-351 - multiple section rock wall

**Comment by bferguso** [comment]
@emjohnst - Great. These are coming through as a multiple polygon on a single card which I think is probably the best way for it to be presented. Will close.
