### ISSUE TITLE
Street Number and Street Name Searches

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#535]
When typing addresses into "Find a Resource Field" a site record will not show up unless the address happens to also be the site name. This might be because "Street number" and "street name" are separate fields. 

For example, "314 West Hastings Street" will not yield the correct search results for heritage site Tip Top Tailors DhRs-555 unless you search "314" and "West Hastings Street". Searching addresses this way isn't intuitive. Should we consider combining the street number and street name field?

- [x] @bferguso to run existing civic addresses through BC Gov validation tool.
- [x] @bferguso to look at civic address -> legal address lookup

The geocoder has a Civic Address -> Site ID and Site ID -> PID lookup so we should be able to cross reference the civic address with site PIDs for those that have them.

Process should add & delete the original civic and legal addresses, then add the validated version of the civic and legal addresses

**Comment by bferguso** [comment]
@emjohnst, @KatieMcEvoy  - There are 29 rows (24 sites) with `streetname1` and `streetname2` in HRIA. What would you like done with streetname2? Borden numbers are: 
DcRu-505
DcRu-555
DcRu-644
DdRu-86
DgRp-12
DgRp-4
DgRp-7
DgRp-8
DgRp-9
DgRq-26
DgRq-32
DgRs-26
DhRs-271
DhRs-356
DiRv-5
DiRv-6
DkSf-34
DlQf-7
EbQt-35
FaRm-31
GaSa-14
GaSa-15
GaSa-16
GdTd-20.

**Comment by bferguso** [comment]
Do we want to make the street names consistent too? (eg - Street names initcap (`FORT ST` -> `Fort St`), make the road types consistent (eg all `Street` or all `St`)?

Do we want to do address validation as well? BCGov has a service that does BC Address validation: https://digital.gov.bc.ca/bcgov-common-components/bc-address-geocoder/
API Specs are here: https://openapi.apps.gov.bc.ca/?url=https://raw.githubusercontent.com/bcgov/api-specs/master/geocoder/geocoder-combined.json#/
Note that this will make what we have inconsistent with what is in the CHRP.

**Comment by emjohnst** [comment]
After much discussion @bferguso  we would like the BC Address validation for entering new sites. However, I don't think it will work for cleaning past data. Example, DcRu-1136 609 Trutch St was validated to 609 Su'it St with a high score of 99. We need local governments to notify us of address changes for sites otherwise other information in the record, (site name, statement of significance, etc.) will be inconsistent. However, we would like the past address data to not include duplicates and cleaned as much as possible to the format that will be the data validation format: street = st; avenue = ave; City; All caps to lowercase; etc. If data validation has a role in the cleaning but not conversion then it could be helpful. 

Legal Description = if possible is there an easy way to clean this data, it seems like the legal description information just needs to be merged to one record (in Hria 1 legal description existed across multiple tables). If not an easy way to clean then we will "preserve" this information in Arches but not on the main site record where it appears messy.

**Comment by bferguso** [comment]
Let's talk about this when everyone is back in the office. The cardinality of the addresses and the wild variation of format (from nothing to correct), and the cardinality of legal addresses are the main reasons this is hard to do automated cleaning. I understand the issue with Trutch -> Su'it, but the option to bypass the changes would solve those. I feel like we'll hit 90-95% valid updates which I think will put us in a better position to start with.

There is also a ticket to reconcile what is in the CRHP with what is in HRIA (or eventually Arches) which can also be done as a post-MVP step as there were questions about the consistency between the two systems.

**Comment by emjohnst** [comment]
Agreed to validation changes but Katie and I would likely need to review and clean data before being put into Arches once we are closer to mvp.
