### ISSUE TITLE
Collection Event Location Resource Model subheader addition and name changes

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#542]
In Collection Event Location, add the following subheader name and field:

- [ ] ~Subheader: "General Location Description" to be placed above the existing "Place Description"~
- [ ] ~Subtitle to replace "Enter text" to say "Enter brief description - maximum 40 chars"~

In Collection Event Location, change the following subheader names:

- [x] Change NTS Mapsheet Number to 1:50K Mapsheet Number
- [x] Change NTS Mapsheet Name to 1:50K Mapsheet Name
- [x] Change Geographical Name to 1:250K Mapsheet Name

To do
- [x] Text Field called `Location Descriptor` limit 40 chars
- [x] RTF call `Detailed Location`
- [x] Truncate Location Description to 40 chars put into `Location Descriptor`
- [x] Concatenate Full Location Description w/ Detailed Location and put in new `Detailed Location`

**Comment by bferguso** [comment]
@LeannePyle - I was thinking about this afterwards - do we want to use one of the "Place Description" or "Detailed Location" fields for the the title and add the 40 character max rule moving forward? Or do we want 3 location description fields?

**Comment by LeannePyle** [comment]
prefer 3 location description fields as some places will need and additional field for more than 40 char if including instructions along a certain road or something

**Comment by LeannePyle** [comment]
Still do not see the header term Location Descriptor replacing General Location in the Collection Event

**Comment by bferguso** [comment]
@LeannePyle - After looking at the data I think we want the `DETAILED_LOCATION` column from the excel spreadsheet to be in the `Location Descriptor` field and the `LOCATION_DESCRIPTION` to be in the new `Detailed Location` RTF field. Will implement that way for feedback.

**Comment by LeannePyle** [comment]
Yes, this will provide a better level of detail, please implement
