### ISSUE TITLE
Industry Project Assessment Resource Model field addition 

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#544]
- [x] Under Project Details, first field should be “General Project Name”, with a field placeholder that states “Enter brief name - maximum 40 chars”

**Comment by bferguso** [comment]
@LeannePyle - Is the term "General" redundant? Can we just call it "Project Name"?

Should this value be unique across projects?

**Comment by LeannePyle** [comment]
Yes, could be just Project Name
Yes, will need to be unique if a company has multiple projects

**Comment by bferguso** [comment]
Re-applied placeholder text. Made unique across all resources

**Comment by LeannePyle** [comment]
not seeing the field placeholder that states “Enter brief name - maximum 40 chars” but it is there under Project Details of the Research Permit
