### ISSUE TITLE
Reorder Registration Statuses

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#552]
- [x] add Registration Status field to official recognition information
- [x] fix values that are no longer in the LOV
- [x] confirm order on page

Can that lead to legacied sites (or other registration statuses) showing different colours of fill styles on the map?

LOV should be:
1. Registered
2. Federal Jurisdiction
3. Recorded/Unprotected
4. Legacy
5. Cancelled Record
- ~Registry Candidate~
- ~Decision Pending~

**Comment by bferguso** [comment]
There are a number of sites that have lookup values removed in the list:
Registry Candidate: 60
Decision Pending: 126

What should be done with these?

Need to confirm order on page.

**Comment by emjohnst** [comment]
@bferguso These should be moved to "Recorded/Unprotected" - is there a way to preserve this change in status or add it to decision history?

**Comment by emjohnst** [comment]
Reviewing these and may need imput from Theresa when she returns. Will get back to you shortly.

**Comment by emjohnst** [comment]
@bferguso records with "registry candidate" and "decision pending" will be edited in HRIA to fit into the table values proposed above.

**Comment by emjohnst** [comment]
Order should be:

1. Registered
2. Federal Jurisdiction
3. Recorded/Unprotected
4. Legacy
5. Cancelled Record

**Comment by bferguso** [comment]
As discussed this morning, the sort order is not being honoured when deploying to ENDOWMENT. Not fixing now as I believe this is a lower priority.

**Comment by emjohnst** [comment]
Closing in favour of a new ticket to address ordering problem
