### ISSUE TITLE
End Date Qualifier > Remove this field (Look at the data)

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#556]
These are the rows that the end date qualifier does not equal the start date qualifier to decide what to do with the data.
null,Circa,8
Exact,null,95
After,Circa,1
Circa,Exact,7
Circa,After,2
Before,After,1
null,Exact,4
Before,Exact,1
After,null,15
Circa,null,72
Circa,Before,18
Before,Circa,14
Before,null,8
Exact,Circa,10
After,Before,25

**Comment by emjohnst** [comment]
Assuming any rows with "null" mean the date qualifier (either start or end) would apply to both dates, could you give me the Borden numbers for the records in these rows:

After,Circa,1
Circa,Exact,7
Circa,After,2
Before,After,1
Before,Exact,1
Circa,Before,18
Before,Circa,14
Exact,Circa,10
After,Before,25

**Comment by bferguso** [comment]
Sent by email

**Comment by emjohnst** [comment]
Reviewed the emailed records and there isn't much difference between using "before" or  "after" versus just "circa". Recommend we remove both date qualifier fields. For the "Event" drop down add: "Construction (circa)" and "Significant (circa)" beside the existing options of "Construction" and "Significant". This will simply entering dates and it also aligns with how the Canadian register records dates. I'll update main ticket as well with these changes.

**Comment by bferguso** [comment]
@emjohnst - Can we change the UI so we have a checkbox labelled "Circa" instead?

**Comment by emjohnst** [comment]
@bferguso yes as long as "circa" would appear next to the date on the record/card info for the historic site. And the xml report for the Canadian register would still have match their controlled vocabulary for dates: Construction (circa); Construction; and Significant. Page 42 https://www.historicplaces.ca/media/5428/doc-standards-en.pdf

**Comment by bferguso** [comment]
@emjohnst - I have a conversation started in the Arches Community (https://community.archesproject.org/t/targeting-specific-node-widgets-with-css-classes/2096) to see if we can have a bit more control of the widget layout in the default Report page. If that isn't resolved quickly is it OK for now to have the standard layout with the understanding that we'll lay things out better either by way of better control of the default Report and/or by way of a workflow with a better layout?

Also - note that there is no `Significant (circa)` in the Canadian register controlled vocabulary.

**Comment by emjohnst** [comment]
@bferguso yes the standard layout is fine. Let's continue with significant (circa) and maybe in xml export to Canadian Register it changes it to significant to match their controlled vocab.

**Comment by bferguso** [comment]
I've completed a change in arches core that will allow a side-by-side view:
<img width="780" alt="image" src="https://github.com/bcgov/BCHeritage/assets/6750642/a0bcd986-3959-4649-a18f-ed3538c2154d">
