### ISSUE TITLE
Update "Image Types" and Remove “Image Content Type"

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#559]
Arches Image Type drop down should have these options:

1. Contemporary Image
2. Historic Image

The following historic data should be re-mapped to the new Arches fields as follows:

Image Type
{Air Photo},1 - **Image Type > Contemporary Image**
{Digital Image},27 - **Image Type > Contemporary Image**
{Photograph},4533 - **Image Type > Contemporary Image**
{Sketch},866 - **Document Type > Document**

Image Content Type
Replace image content types with these types:
{Combined Document}	4 - **Document Type > Document**
{Detailed Data Table}	1 - **Document Type > Document**
{Document}	3875 - **Document Type > Document**
{Document,Document, Combined}	13 - **Document Type > Document**
{Document, Combined}	8 - **Document Type > Document**
{Document, Other}	24 - **Document Type > Document**
{Image, Drawing}	18 - **Document Type > Document**
{Image, Exterior}	4072 **Image Type > Contemporary Image**
{Image, Exterior,Image, Historic}	12 **Image Type > Contemporary Image**
{Image, Exterior,Image, Other}	3 **Image Type > Contemporary Image**
{Image, Historic}	568 **Image Type > Historic Image**
{Image, Interior}	90 **Image Type > Contemporary Image**
{Image, Other}	1544 **Image Type > Contemporary Image**
{LINK, Local}	763 **obsolete, remove. Other data in Link Text Field will describe link**
{Map}	132 **Document Type > Map**
{Map, Detailed}	3 **Document Type > Document Map**
{Map, Other}	6 **Document Type > Document Map**
{Site Form}	9 **Document Type > Site Form (Ticket #394 to add this to Document Type)**
{Table, CMT}	1 **Document Type > Document**

For ETL: 
- title -> image_features
- 2 descriptions + full date -> image_description concatenated. Date string to be Photographed on [date]
- Image date to be truncated to year in date field.

**Comment by emjohnst** [comment]
@bferguso The reason for the image type change is because the Canadian Register also requires image type as a mandatory field with controlled vocabulary. So instead of having two image type fields (one with HRIA data, one for Canadian Register) we were hoping to combine them. The Canadian Register controlled vocab options for Image Type are: 
Contemporary Photograph;
Historic Image; 
Map / Plan; (Katie and I discussed Map/Plan would make sense under document not image possibly - thoughts?)
Word; (Katie and I discussed this option would not apply to our data)
Other

 I think we can put air photo, digital image, and photograph under "contemporary photograph" for now. Sketch could possibly be "other" but I wonder if it would be suitable under document? Thoughts @KatieMcEvoy @bferguso ?

**Comment by KatieMcEvoy** [comment]
I prefer sketch as a document if that's possible.

**Comment by KatieMcEvoy** [comment]
For Image Captions

Field: Image Type
- select one of the following: Historical or Contemporary

Field: Image View
- the following will be hierarchical lists to select from

**Interior**
Detail view
Overhead view


**Exterior**
Aerial view
Front view
Left side view
Right side view
Back view
Close view
Distant view
Corner view
Detail view

**Landscape**
Aerial view
Close view
Distant view

Field: Image Feature(s)
- free text

Field: Image Date
- date picker


Generate Image caption with:
[Image view] - [Image Features (if exists)], [Image Date YYYY]

**Comment by bferguso** [comment]
@emjohnst, @KatieMcEvoy - The current data has months and days so the current date format is Year, Month and Day. I understand that you would prefer year only - would you like to change the format to year only and truncate the data in the ETL process?

Also I was previously concatenating the (possibly 2) descriptions from HRIA and putting them in the Image Description field (now the Image Features field I believe)? It was a multiline description field - how would you like me to handle that now?

The Image Title was going into the (now to be generated) Image Caption field so we need to decide where that goes too.

**Comment by emjohnst** [comment]
@KatieMcEvoy  @bferguso We would still like to keep the image description field, so the data can still be concatenated and put there. Let's leave that as it was. There is a "image caption" field in HRIA and that should go in the "features" field. Date: is it possible to have the full date YYYY-MM-DD put in the date field and then truncated to year when it's made into the generated caption?

**Comment by emjohnst** [comment]
Complete
