### ISSUE TITLE
Validate Legal Description Data

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#560]
Improve legal description data. Determine how to clean or what to import of HRIA legal description data. Explore options to validate legal description data.

- [x] @bferguso create spreadsheet of current legal description data
- [x] @KatieMcEvoy @emjohnst review spreadsheet, make decisions on whether to preserve, clean, or revalidate existing data
- [x] @bferguso explore resources to validate legal description data in Arches, or generate it based on PID

Authoritative source for legal descriptions found. Possible strategy is to link on PID to get the rest of the legal description.

Using the Fully Attributed Cadastral layer to generate legal descriptions from PIDs.
Validation run on 10 October: Updated: 12804, missed: 1196 of PIDs that are in the correct format (9 digits). Total number of unique PIDs is 14082.

Approach agreed upon in Oct 10 meeting:
- [x] Remove all fields from legal address except PID, Parcel Identification Number, Legal Description (Rename from HRIA Legal Description
- [x] Legal description information from HRIA to be concatenated together and entered into the Legal Description field. This data will then be deleted and replaced with the values from the BCA table (PID -> Legal Description lookup). This will ensure that the original HRIA data is in each record's history

To preserve all existing HRIA address data (civic and legal) the overall strategy is as follows:
   1) Add existing civic address as it is in HRIA
   2) Add legal addresses as it is in HRIA
   3) Delete all legal addresses
   4) Delete civic addresses that were validated using the BC address validation API
   5) Add validated civic addresses - NB - this will result in a mix of original civic
      address UUIDs and new (corrected) civic address UUIDs
   6) a) Add the validated legal addresses to validated civic addresses
        b) Add the unvalidated legal addresses to validated civic addresses
        c) Add the validated legal addresses to unvalidated civic addresses
        d) Add the unvalidated legal addresses to unvalidated civic addresses

**Comment by emjohnst** [comment]
@bferguso could we verify legal description data from the [ParcelMap BC Parcel Fabric - Fully Attributed](https://catalogue.data.gov.bc.ca/dataset/parcelmap-bc-parcel-fabric-fully-attributed) layer? It has legal description as an attribute "LEGAL_DESCRIPTION is the full legal description of the parcel and is primarily recorded from the Land Title Register. Where recorded only in the Crown Land Registry, this attribute is to be populated from Tantalis for the fabric compilation, but maintained by PMBC during on-going operations." https://catalogue.data.gov.bc.ca/dataset/parcelmap-bc-parcel-fabric-fully-attributed/resource/59d9964f-bc93-496f-8039-b83ab8f24a41

**Comment by bferguso** [comment]
@emjohnst - can we just use the legal address information you sent me (easiest) to replace what we have or do we need to try to do some sort of validation on what we have? If we can just match on PID and use the info you sent me it should be pretty straight forward to do.

**Comment by emjohnst** [comment]
@bferguso Yes, replace. Can we use the same process we are going to use for address? Upload old data (for history) then replace with cleaned data. I would like to discuss format so the way we enter it going forward will match the format of the legal description info you are seeing.
