### ISSUE TITLE
Update Spatial Location Card and populate with data from correct sources

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#561]
1. Arches Field: Accuracy Remarks > Should include Data from "Source Notes" field in HRIA (pop-up box).
Source Notes is from the Record Edit History Pop-up box that appears when saving a new site under Map references. Example of data in this field is "Notification from Local Government"

2. Arches Field: Spatial Accuracy > Should include Data from "Source Notes" field in HRIA
Accuracy Notes is from Record Edit History Pop-up box but is also saved under GIS History table in Map references under the label "Source Notes". Only include the most recent "Source Notes" data in Arches. Example of Data "snapped to cadastral"

3. Reverse order on card: Spatial Accuracy and then Accuracy Remarks.

[Uploading... Record Edit History Pop up.JPG]

**Comment by emjohnst** [comment]
Spatial accuracy is a drop down field in HRIA, let's discuss if it's useful to bring this table in: 
1:10K
1:20K
1:250K
1:50K
1:5K
GPS
Orthophoto
Site Map (Detailed)
Site Map (Rough)
Unknown

**Comment by emjohnst** [comment]
Spatial accuracy drop down menu (see comment above) likely not to be included in Historic Site Resource model but will confirm after speaking with Archaeology

**Comment by emjohnst** [comment]
[Uploading... image.png]

**Comment by emjohnst** [comment]
@bferguso can you search what data is in "Accuracy Remarks" in HRIA? [Uploading... HRIA Map References view - Accuracy Remakrs and Source Notes.JPG]

**Comment by KatieMcEvoy** [comment]
"Accuracy Remarks" are part of the pop-up when creating a new site polygon in HRIA.
 It is used to show what method was used in creating the polygon. Many will say "snapped to cadastral". Ex: DcRu-1447

**Comment by bferguso** [comment]
Loading spatial accuracy and accuracy remark data, both as straight text fields as is seems like the spatial accuracy field may be for historical records only. Spatial Accuracy widget also set as readonly.

**Comment by KatieMcEvoy** [comment]
Closing - removing spatial accuracy and adding source notes being handled in ticket 822
