### ISSUE TITLE
changes to Provincially Protected Fossil Site Resource Model

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#566]
- [x] Change Temporal Assessment to Geological Age
- [x] Within Geological Age replace Max Geological Start Date and Geological Start  Date with Minimum Time and Maximum Time 
- [x] Change Geological Assessment to Stratigraphy

**Comment by bferguso** [comment]
For Geological Age and Stratigraphy - should we mirror what we have in Fossil Sample?

**Comment by LeannePyle** [comment]
Yes please

**Comment by bferguso** [comment]
Tried exporting the branch from Fossil Sample but there is a bug in the Graph manager. Will investigate.

**Comment by bferguso** [comment]
Found a workaround to the issues:
1. The Resource Model needs to be unpublished before exporting the branch
2. The sourcebranchpublication_id values in the updated Resource Model JSON needs to be nulled out if the Branch does not continue to exist in the instance
