### ISSUE TITLE
Create CRHP XML template

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#572]
CRHP Form Field = Equivalent Arches Field (if Exists) / Controlled Vocab / **Notes**

- [x] Unique Provincial Identifier = Borden Number / free text
- [x] Name of Historic Place = Site Name >Common / free text - Can there be multiple names submitted? - Only one allowed - currently picking arbitrary if more than one
- [x] Other Names = Site Name > Other / free text
- [x] Jurisdiction = NA / "British Columbia"
- [x] Formal Recognition Authority = NA / "Province of British Columbia" ; "Local Governments (BC)" ; "City of Vancouver" **Only Select 1 - Highest Level of Designation**
- [x] Formal Recognition Type = Legislative Acts>Recognition Type / See Attached Image from CRHP Documentation Standards **Only Select 1 - Highest Level of Designation**
- [x] Formal Recognition Statue = Legislative Acts> Act Section / See Attached Image from CRHP Documentation Standards **Only Select 1 - Highest Level of Designation**
- [x] Formal Recognition Date = Official Recognition Details>Designation or Protection Start Date / yyyy/mm/dd **Only Select 1 - Highest Level of Designation**
- [x] Location - Province Territory = Property Address> Province / "British Columbia"
- [x] Location - level 2 = Property Address > City / Free text
- [x] Location - Street and Street number = Property Address > Street Address / Free text
- [x] Grid Coordinates (~UTM~ or Latitude/Longitude) = ??? / Free text
- [ ] Cadastral Reference = Legal Description > PID / Free text - 
- [x] Description of Boundaries = NA / "Refer to BC Spatial Data"
- [x] Area of Historic Place = ??? / Square meters
- [x] Documentation Location = Statement of Significance > Document Location / Free text **Only Select 1**
- [x] Statement of Significance Description = Statement of Significance > Description / Free Text **Only Select 1**
- [x] Statement of Significance Heritage Value = Statement of Significance > Heritage Value / Free Text **Only Select 1**
- [x] Statement of Significance Character Defining Elements = Statement of Significance > Character Defining Elements / Free Text **Only Select 1**
- [x] Contributing Resources Number = Heritage Class > Number / free text
- [x] Contributing Resources Type = Heritage Class > Heritage Category / "Archaeological Site/Remain" ; "Building" ; "Collection" ; Landscape(s) or Landscape Feature(s)" ; "Structure"
- [x] Category of Property = Heritage Class > Ownership / "Private" ; "Public (Federal)" ; "Public (Provincial)" ; "Public (local)" ; "Not-for-profit"
- [x] Date Type = Chronology>Event/ "Construction Date"; "Significant Dates"; "Construction Date (circa)"
- [x] From Date = Chronology> Start Year / yyyy/mm/dd
- [x] To Date =Chronology> End Year / yyyy/mm/dd
- [x] Architect/Builder = Architects/Builders / free text
- [x] Function (historic) category and type = Heritage Function > Functional Category> Historic check box / Controlled Vocab
- [x] Function (current) category and type = Heritage Function > Functional Category> Current check box / Controlled Vocab
- [x] Theme > Heritage Theme / Controlled Vocab
- [x] Image Type > Image Type / Controlled Vocab "Contemporary Photograph" ; "Historic Image" 
- [x] Image Caption > Image caption / Free text
- [x] Image Description > Image Description / Free text
- [x] Copyright > Copyright / Free text
- [x] Image link **resized** - this doesn't go anywhere so just using the Arches UUID file URL
- [x] Name of Provincial Registrar = NA / "BC Registrar" - Currently using name of Registrar
- [x] Individual Owner notification = NA / "N" - Only one character allowed
- [x] Individual Owner Notification Response Type = NA / "Not applicable"
- [x] Contact info of provincial registrar "BChistoricplacesregister@gov.bc.ca"
- [x] Website links = URL for link 
- [x] Website Links Link type= External URL Type / free text
- [x] Website link Description = NA / free text

Canadian Heritage Register Documentation Standards Handbook https://www.historicplaces.ca/media/5428/doc-standards-en.pdf

![Capture](https://github.com/bcgov/BCHeritage/assets/139929541/0ac67524-f978-412a-a9fd-600efd908d5f)

**Comment by emjohnst** [comment]
@bferguso emailed xml example reports becuase file type is not supported to attach here.

**Comment by bferguso** [comment]
@emjohnst - A few questions / comments here:

1. Recognition Type - "Highest Level of Designation" - assuming that "Province of British Columbia" > "Local Governments (BC)" or "City of Vancouver"? Is it possible to have "Local Governments (BC)" AND "City of Vancouver" on a single record. If so, which one wins?
2. Confirming that NTS Mapsheet no longer required?
3. Cadastral Reference - this was not previously submitted. Confirming you'd like this added.
4. Address / PID info - if there is more than one address how do we choose?
5. SoS - how do we choose if there is more than one?
6. For the contact information, previously it had the name (first and last) of the Registrar. Doesn't seem like the XML allows for "BC Registrar" as a single value.
7. For Heritage Categories - there is only one ownership allowed, but multiple categories / contributing resource counts. Picking the first one for the ownership. Is this OK?
8. For all of the controlled vocabularies - need to confirm if our values match the CRHP values. If not, we'll need to translate on output.

I don't have a button for this yet but you can just replace the "report" part of the URL when you open the details of the site with crhp_export. Eg, if you click on a site you'll get something like this:
`https://dlvrapps.nrs.gov.bc.ca/int/bcrhp/report/ed9eb1f2-c4d1-42d9-87ad-54f146057b81`
just change it to this:
`https://dlvrapps.nrs.gov.bc.ca/int/bcrhp/crhp_export/ed9eb1f2-c4d1-42d9-87ad-54f146057b81` to look at the XML.

Depending on your browser you may need to "View Source" to stop the browser from trying to format the information.

**Comment by emjohnst** [comment]
@bferguso 
1. Local Gov and City of Van would not be possible together
2. I'm not sure what the nts mapsheet is - let's say no and we can run a test with the Canadian Register to make sure it looks ok
3. Let's not include cadastral reference if there is not an easy way to pick 1, I think it will be more common to have multiple PIDs as opposed to multiple addresses. This is an optional field.
4. Open to suggestions on this, only "level 2" location information is required (city?) - if there is more than one is it possible for the script to just pick the first one? Or leave out street addresses and just have the city?
5. Can we employ similar rules as Recognition information - picking the highest level as there should only be Local Government or Provincial Type SoSs. 
6. You can just put my name then Emerald Bedell
7. I suspect there may need to be some translation
Let me know if you have any other questions on this

**Comment by bferguso** [comment]
@emjohnst  - Another question:

1. The existing XML output has "District" attribute in it. Can we leave that blank too? Not sure where that's coming from.

**Comment by emjohnst** [comment]
@bferguso  Yes let's leave it blank. It might have to do with Heritage Conservation Areas (aka districts) or I think it's more likely it has something to do with "related listings" which is the responsibility of the Canadian Registrar to complete.

**Comment by bferguso** [comment]
How to access for now: https://testapps.nrs.gov.bc.ca/int/bcrhp/report/[uuid] -> https://testapps.nrs.gov.bc.ca/int/bcrhp/crhp_export/[uuid]

**Comment by emjohnst** [comment]
Moving the following from ticket #729 to here.

Sites in CRHP not Listed / Published
| borden\_number | isacceptedbyfeds | state | status |
| :--- | :--- | :--- | :--- |
| DdRu-136 | Y | Listed | Suspended |
| DdRu-91 | N | De-Listed | Cancelled |
| DeRt-23 | Y | Nominated | Pending Eligibility |
| DgRo-13 | null | Listed | Suspended |
| DgRp-7 | null | Listed | Suspended |
| DgRq-60 | Y | De-Listed | Do Not Publish |
| DgRq-66 | Y | De-Listed | Do Not Publish |
| DgRq-70 | Y | De-Listed | Do Not Publish |
| DgRr-57 | null | Nominated | Ineligible to List |
| DgRs-106 | Y | De-Listed | Do Not Publish |
| DgRx-113 | Y | De-Listed | Owner Objection |
| DgRx-75 | Y | De-Listed | Owner Objection |
| DhRr-143 | Y | De-Listed | Do Not Publish |
| DhRr-144 | Y | De-Listed | Do Not Publish |
| DhRr-157 | Y | De-Listed | Owner Objection |
| DhRr-163 | Y | De-Listed | Do Not Publish |
| DhRr-167 | Y | De-Listed | Owner Objection |
| DhRr-305 | Y | De-Listed | Owner Objection |
| DhRr-314 | Y | De-Listed | Owner Objection |
| DhRs-1124 | null | Listed | Suspended |
| DhRs-1300 | null | De-Listed | Published |
| DhRs-150 | Y | De-Listed | Do Not Publish |
| DhRs-280 | Y | De-Listed | Do Not Publish |
| DhRs-735 | Y | De-Listed | Owner Objection |
| DhRs-880 | Y | Listed | Suspended |
| DhRt-100 | Y | De-Listed | Owner Objection |
| DhRx-72 | N | De-Listed | Do Not Publish |
| DhRx-73 | Y | De-Listed | Owner Objection |
| DhRx-76 | N | De-Listed | Owner Objection |
| DhRx-98 | Y | De-Listed | Owner Objection |
| DhSb-53 | Y | Nominated | Pending Eligibility |
| DiQv-56 | null | Listed | Suspended |
| DjSg-12 | null | Listed | Do Not Publish |
| DkQw-49 | null | Listed | Suspended |
| DkRi-18 | null | Nominated | Ineligible to List |
| DlQu-90 | Y | Nominated | Ineligible to List |
| EcRk-40 | null | Listed | Suspended |
| EeQt-13 | null | Nominated | Pending Eligibility |
| EeRc-109 | null | Listed | Suspended |

**Comment by emjohnst** [comment]
@bferguso 
Have a few edits:
Used example record McIvor House DlQu-69 and I tested against a HRIA xml export for this site from 2021. Emailed the xml I tested against.

1. Missing SoS Description [Place Description] 
- Fixed
2. Address should be 2269-2279 Benvoulin Rd 
- This is a data conversion issue. The XML is using the "Street Address" which is correct. We should look at this case for the data conversion when we evaluate the address validation
3. [Coordinate Detemination] has a question - should be 'Digital Maps" based on controlled vocab list 
- This is correct in DLVR. TEST not up to date
4. Missing ownership type under Heritage class. should be "not-for-profit" 
- This is correct in DLVR. TEST not up to date
6. Date Types need to match controlled vocab I think. Significant Dates change to "Significant" and Construction Date (circa) to Construction (circa); etc. 
- Fixed
7. Missing Architect/Builder <AssociatedEPOs> Gordon C. Scott 
- This is correct in DLVR. TEST not up to date
8. Image type doesnt match 'Image-Exterior' versus 'Exterior' but these aren't even the controlled vocab options for image type in the handbook so maybe doesn't matter? 
- That was my thought. It's free text so maybe best to use the value in Arches?

Other than that looking good :)

**Comment by emjohnst** [comment]
@bferguso truncate image description
