### ISSUE TITLE
Update for "Site Record Admin" node and add/edit Cards

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#575]
- [x] Rename "Remarks" node to "Site Record Admin" node
Restrictions
- [x] Add Card for "Restrictions" (no ability for multiple entries)
- [x] Add "Restricted" check box
- [x] Add "Restrictions" note RTF field
Internal Remarks
- [x] Rename "Remarks" card to "Internal Remarks"
- [x] Add "Remark Type" drop down on Remarks Card with following options: General; Incomplete Data; Duplicate Record
CRHP Admin
- [x] Add "CRHP Admin" Card
- [x] Add "CRHP Eligibility" drop down options: Ready; Incomplete; Ineligible; Approved
- [x] #713
- [x] #714
- [x] Add "Submitted to CRHP" Date field
- [x] #715
- [x] Add "Federal ID Number" field (Max 5 digit numerical field)
- [x] #716
- [x] #729

Initial proposed Record state values:
New
Submitted
~Incomplete (not here - by way of Internal remarks?)?~
BCRHP Accepted
~Accepted - Basic (Not eligibile for CRHP)~
~Accepted - Full~
Ready for CRHP Export
Submitted to CRHP
Approved by CRHP
Ineligible to CRHP

- [x] Records with isacceptedbyfeds = 'Y' -> BCRHP Status Accepted - Full Record, otherwise Accepted - Basic Record
- [x] Records with isacceptedbyfeds = 'Y' -> CRHP Status Approved, otherwise leave blank

**Comment by emjohnst** [comment]
@bferguso what do you think of these field suggestions:

Record Status:
Provisional
Incomplete
Authoritative

"Private" or "Internal Only" - check box

Canadian Register Record Status:
CRHP Ready 
CRHP Incomplete
CRHP Ineligible
CRHP Approved Y/N - There is HRIA CRHP table data for here "Is accepted by feds"

"XML Export" button
Submitted to CRHP (date field) - there is HRIA CRHP table data for here "date exported to fed"
Federal ID Number (5 digits) - There is HRIA CRHP table data for here "Fed name"

Other HRIA data - I suggest we don't include "is owner notified" needs to be on xml but can just be N - not a requirement for BC. "is public access" field has not been used in past but needs to be on xml can say Y

**Comment by emjohnst** [comment]
@bferguso re: public record sites

Public record sites must be:
1. Officially Recognized "Y" (is this equivalent of Historic Place=Y Site table in HRIA?)
2. Registered or Federal Jurisdiction
3. Not checked Private/Internal Site

**Comment by bferguso** [comment]
@emjohnst  - 

1. There are 555 records in the HRIA CRHP Admin table that only have the `isownernotified` column populated. None of the attributes above would be populated (exported date, accepted, or fed ID). I'm omitting these records from Arches because the `isownernotified` is not being transferred to the new system. -- Not sure if we can glean the status of those records to assign the eligibility to something else (not eligible?). Just would like confirmation what you'd like done with those.

Wil filter these rows out

**Comment by emjohnst** [comment]
@bferguso Agree to not transfer isownernotified as it was not used consistently or correctly in past data entry and we discussed using new restrictions section/internal remarks for owner objections to inclusion on the registers. The CRHP tables in HRIA were created likely as part of routine data entry and could only be saved if one field was completed - likely owner field. This provides no indication if the record is eligible/ineligible or ready for Canadian Register.

**Comment by emjohnst** [comment]
@bferguso Still working through this - a question that came up for us is what would we do when there is an update and its not a new submission? The record may already be set to Accepted/Approved. How do we represent that in the record status, especially when its a record eligible for CRHP that already has a submission date?

**Comment by emjohnst** [comment]
@bferguso @KatieMcEvoy 
Here is what I am proposing for Site Record Admin node. Katie and I discussed it makes more sense to us to treat the CRHP register record separate to the BCRHP record for tracking its status. I know we've had at-length discussions about combining them but in our process we treat them as different operations. I am still confirming if we can remove some data (CRHP approved/federal id). If you are okay with this @bferguso I'll update the description.

"Site Record Admin" Card:
"BCRHP Record Status" Drop Down
- "In Progress" - Record in progress but not ready for review
- "Update Requested" - Previously submitted and approved record requires changes
- "Submitted" - Submitted to BCRHP for review/approval
- "Approved - Full Record"
- "Approved - Basic Record"

"Restricted" "Unrestricted" toggle

"CRHP Record Status" Drop Down
- "Ineligible"
- "Submitted"
- "Update Required"

"Submission Date" date field / xml export button

**Comment by bferguso** [comment]
@emjohnst, @KatieMcEvoy  - I feel like the historical Decision History values belong under the Site Record Admin card as well. Are you good with that?

**Comment by emjohnst** [comment]
@bferguso @KatieMcEvoy After discussing with Katie, Yes we think Decision history makes more sense under "Site Record Admin". However we also discussed we would still like "Internal Remarks" to be its own node because the comments in there are very general to the whole record and this was the only place to "flag" important information in HRIA so it's important to have quick access to it.

**Comment by bferguso** [comment]
Loading with the rules above.  Changes to BCRHP or CRHP LOVs can be done as a separate issue.

**Comment by emjohnst** [comment]
Moving from ticket #729 to here

Sites in CRHP not Listed / Published
| borden\_number | isacceptedbyfeds | state | status |
| :--- | :--- | :--- | :--- |
| DdRu-136 | Y | Listed | Suspended |
| DdRu-91 | N | De-Listed | Cancelled |
| DeRt-23 | Y | Nominated | Pending Eligibility |
| DgRo-13 | null | Listed | Suspended |
| DgRp-7 | null | Listed | Suspended |
| DgRq-60 | Y | De-Listed | Do Not Publish |
| DgRq-66 | Y | De-Listed | Do Not Publish |
| DgRq-70 | Y | De-Listed | Do Not Publish |
| DgRr-57 | null | Nominated | Ineligible to List |
| DgRs-106 | Y | De-Listed | Do Not Publish |
| DgRx-113 | Y | De-Listed | Owner Objection |
| DgRx-75 | Y | De-Listed | Owner Objection |
| DhRr-143 | Y | De-Listed | Do Not Publish |
| DhRr-144 | Y | De-Listed | Do Not Publish |
| DhRr-157 | Y | De-Listed | Owner Objection |
| DhRr-163 | Y | De-Listed | Do Not Publish |
| DhRr-167 | Y | De-Listed | Owner Objection |
| DhRr-305 | Y | De-Listed | Owner Objection |
| DhRr-314 | Y | De-Listed | Owner Objection |
| DhRs-1124 | null | Listed | Suspended |
| DhRs-1300 | null | De-Listed | Published |
| DhRs-150 | Y | De-Listed | Do Not Publish |
| DhRs-280 | Y | De-Listed | Do Not Publish |
| DhRs-735 | Y | De-Listed | Owner Objection |
| DhRs-880 | Y | Listed | Suspended |
| DhRt-100 | Y | De-Listed | Owner Objection |
| DhRx-72 | N | De-Listed | Do Not Publish |
| DhRx-73 | Y | De-Listed | Owner Objection |
| DhRx-76 | N | De-Listed | Owner Objection |
| DhRx-98 | Y | De-Listed | Owner Objection |
| DhSb-53 | Y | Nominated | Pending Eligibility |
| DiQv-56 | null | Listed | Suspended |
| DjSg-12 | null | Listed | Do Not Publish |
| DkQw-49 | null | Listed | Suspended |
| DkRi-18 | null | Nominated | Ineligible to List |
| DlQu-90 | Y | Nominated | Ineligible to List |
| EcRk-40 | null | Listed | Suspended |
| EeQt-13 | null | Nominated | Pending Eligibility |
| EeRc-109 | null | Listed | Suspended |

**Comment by emjohnst** [comment]
@bferguso Based on options above can we update the CRHP drop down to:

"Ineligible"
"Submitted"
"Approved"
"Update Required"
"Removed"

This will mean that: submitted = nominated; approved = listed; removed = delisted.

**Comment by bferguso** [comment]
@emjohnst  - What would you like the status set to for the Listed / Suspended and Listed - Do Not Publish?

**Comment by emjohnst** [comment]
@bferguso 
- [x] Listed / Suspended = Update Required
- [x] Listed / Do Not Publish = Update Required
