### ISSUE TITLE
Site Submission Resource Model Changes

### ISSUE THREAD

**Issue by KatieMcEvoy** [bcgov/BCHeritage#582]
- [x] Change Resource Model Name from BC Historic Site Submission to "Heritage Site Submission"

Submission Details card
- [x] Change name of Submitting Authority field to "Submitting Government"
- [x] Remove the Submitted by field
- [x] Change name of BCRHP Submission Assignee field to "Assigned To"
- [x] "Assigned To" field should be limited to HB employees only (Heritage Branch)

Under Historic Site Card
- [x] Under requested Operation, Addition should be changed to "New Addition"
- [x] At least 1 box must be checked under Submission Type - Made field mandatory
- [x] Add a "Information Provided" check box with options "Basic Record" and "Full Record". 1 of these must be selected. 
- [x] Change name of BCRHP Assignee to "Alternate BCRHP Assignee"
- [x] Alternate BCRHP Assignee need to be left blank unless manually entered to separate it from the submission Assignee - Nothing to do here?
- [x] Alternate BCRHP Assignee should be limited to HB employees only
- [x] Change Site Submission Internal Notes to "Internal Notes" - Changed card only as this collides with submission-level internal nodes

Comments to LG Card
- [x] Change Comments to LG card name to "Comments to Submitting Government"
- [x] Change Comments to LG field name to "Comments to Submitting Government"
- [x] Change Delivery Recipients to "Recipients" - Omit HB employees, sort ascending
- [x] Change Delivery Date to "Date"

**Comment by KatieMcEvoy** [comment]
@KatieMcEvoy @emjohnst
- [x] Look into the different submission types to add to that field if a reasonable

**Comment by emjohnst** [comment]
@bferguso is it possible when linking from the "Historic Site" field on the Historic Site page to preserve the Site Name typed so you don't have to retype it when you "Create new site?"

**Comment by bferguso** [comment]
@emjohnst - As discussed last week - when adding the "Historic Site", it is the full site, not just the name so it can be built upon.

**Comment by emjohnst** [comment]
@bferguso can we change:
- [x] Historic Site Internal notes to "Site Internal Notes" (widget label) and 
- [x] Internal Notes for the submission to "Submission Internal Notes" (card label). 

Let me know if I can go in there and do it myself.

**Comment by emjohnst** [comment]
@bferguso Add under submission type "Amendment" and "Removal"
