### ISSUE TITLE
Historic Site Arch Data fields

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#587]
Search results to identify how many and which historic sites have data in fields that were mapped as "Archaeological" business area fields.

Looking for sites to be identified by Borden number and include registration status based on the search: 
Historic site = Y
Historic site = N
(Additional separate search spreadsheet for these sites) Historic site = null + Registration status: Registered

Archaeological Data fields:
Site Visits
Archaeological Culture
Site typology and feature Descriptions
Stratigraphy
Cultural material
Site visit team
Condition
Disturbance
Biogeography
Cultural depressions
Rock art
CMTs
Site Visit Roles
References

Background: Heritage branch and archaeology branch used to be the same branch and I think a lot of this data in historic site records is from that time of management (70s,80s,90s). Have to decide how to move forward with managing the data of these sites once we isolate a list of sites that have both Heritage and Arch branch data.

**Comment by bferguso** [comment]
@emjohnst - Do you just want a list of borden numbers or are you looking for data from the above tables?

**Comment by emjohnst** [comment]
@bferguso Could I have borden number and registration status? If possible could we do columns of the Archaeological data fields above with just a "Y" if there is data there? Or if this is easier 1 spreadsheet with the borden numbers and registration status of all records with any data in these fields based on our search criteria, and then another list of how many records have data by field type, (Site Visits - 130, etc.)

**Comment by bferguso** [comment]
Spreadsheet sent via SOFT

**Comment by emjohnst** [comment]
@bferguso Could you do a similar search with "union of all list" and find out which of the records from that list has no "Authority" attribute information? Or "Authority = null"

**Comment by emjohnst** [comment]
@bferguso Also, can you confirm what the total # of records was for Historic Site =Y and Historic Site =N? We had 2600ish records with Archaeological data attributes out of how many?
