### ISSUE TITLE
Government resource model - Map

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#590]
Mapbox should have same settings as historic site resource model mapbox when about to edit such as:
- [x] map view of all of BC when opening
- [ ] have municipal layers showing - no longer required EJB update 2024/01/08
- [ ] ability to add feature (so I can use municipal map layers to set government location)

**Comment by bferguso** [comment]
For #2 above - there is currently no way to configure which layers are visible on each of the edit maps. So we can either:
1. Display the municipal boundaries by default everywhere, including on the search page or
2. Not show them for now on the edit page and address this at a later date.

If option 2 is selected, please create a separate ticket for this in the `New` swimlane and we can address it sometime after MVP.

**Comment by bferguso** [comment]
For item 3 above - are you looking to select from the cadastral later to create those geometries? Or are you looking to be able to select from the municipal / regional boundaries as well?

**Comment by emjohnst** [comment]
@bferguso just the municipal /regional boundaries for this resource model. Okay not proceeding with 2.

**Comment by bferguso** [comment]
Can we leave this as a non-mvp ticket then? Do you need to add these boundaries immediately?

**Comment by emjohnst** [comment]
@bferguso yes it doesn't have mvp label. it could be moved to post mvp swim lane. I'll remove it from epic as well.

**Comment by emjohnst** [comment]
closing in favour of another similar ticket #871
