### ISSUE TITLE
Update Resource Models Details Cards

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#592]
Heritage Site Resource Model Details Card:

TBD (after Xmas break)

Legislative Act Details Card:

- [x] Authority
- [x] Legal Instrument
- [x] Act Section
- [x] Recognition Type
- [x] Validity Period

Government Details Card:

- [x] Gov name
- [x] Gov type

Government Person Details Card:

- [x] Name
- [x] username
- [x] Contact
- [x] Gov Association

Site Submission Details Card:

- [x] Submitting Government Name
- [x] Submission Date
- [x] Completion Date
- [x] Submitted Sites Number
- [x] Requested Operation
- [x] Information Provided
- [x] Historic Site(s)

**Comment by bferguso** [comment]
@emjohnst - Are you looking for the government location map or address? If it's the map that will need to wait until after MVP.

**Comment by emjohnst** [comment]
@bferguso that's fine, I'll update ticket to remove that.
