### ISSUE TITLE
Search Results Cards

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#594]
Government Resource Model
Search result card
- [x] Government Name (header)
- [x] Government Type

Historic Site Submission Resource Model
Search result card:
- [x] Date Submitted > Submitting Government (Header) - would prefer it reversed but is it ordered this way so search results can be ascending/decending based on date submitted? If so, leave as is.
- [x] Number of Sites
- [x] Assignee
- [x] Completion date

Legislative Act Resource Model
Search result card:
- [x] Authority, Legal Instrument
- [x] Act Section
- [x] Recognition Type
-
Update to Leg Act Search result card Jan 9 2024:
- [x] Active

**Comment by bferguso** [comment]
@emjohnst, @KatieMcEvoy  - For Site Submissions - Should we also include who the submission has been assigned to so you can easily identify who is responsible for which submission?

**Comment by emjohnst** [comment]
Yes include assignee

**Comment by bferguso** [comment]
I have updated the L&F to what Raj had suggest. Feel free to give feedback and submit a ticket for any changes you'd like made.

**Comment by KatieMcEvoy** [comment]
Legislative Act Resource Model
Search result card:

If possible Authority (Provincial/Municipal/Federal) should come before that Act and Section.
Currently order is Act, Authority, Section, Recognition Type.
New order should be: Authority, Act, Section, Recognition Type.

**Comment by bferguso** [comment]
This is the same issue as #825. The change is now in DLVR - moving this ticket back to DLVR and will re-promote to QA once it has moved to TEST.
