### ISSUE TITLE
Add Fields to Legislative Act Resource Model

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#597]
- [x] "Citation" text box
- [x] "Replaced by" picklist - Select the legislative act that replaces this one
- [x] "Active" checkbox - only these will be presented as options in the Heritage Site
- [x] Document uploader

**Comment by bferguso** [comment]
@emjohnst - Should the "Replaced By" actually be a link to another instance of a Legislative Act?

**Comment by emjohnst** [comment]
@bferguso @KatieMcEvoy  yes that could be helpful. I was also thinking of making changes to the "start" and "end" date. The legislative library did a lot of research for me on the Heritage Conservation act so I could fill out this resource model. What I learned is that some changes that affect what we would write in the "Act Section" - where it references specific sections of the act - those section numbers change a lot through various revisions and amendments of the act so the act doesn't "end" but there is a slightly different version that becomes "in force". I have all of the "in force" dates but "end" aka repealed dates are only used in a few circumstances.
What I am trying to say is maybe we go by a "Current" or "Active" check box and that would predetermine what acts would show up in the Heritage Site Resource model. Would that be a relatively simple change? We would still keep "Start" and "end" date though. This will also be a lot easier for me to control what acts appear in the Heritage Site Resource Model without having to do more research myself or asking the library to do it - but we will get there eventually :)

**Comment by bferguso** [comment]
<img width="1317" alt="image" src="https://github.com/bcgov/BCHeritage/assets/6750642/910a7d2e-05a1-4aa2-a930-614e56f85102">
