### ISSUE TITLE
Add Sandbox equivalent to BCRHP Arches

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#603]
- [x] @bferguso to create resource model of Sandbox equivalent 
- [x] @KatieMcEvoy and @emjohnst to come up with name - "Sandcastle" selected
- [x] Rename geometry card to "Project Boundaries" and node to "Project Boundary"
- [x] Allow filtering by geometry from this layer
- [x] #607
- [x] #608

Potential Names:
Project Box
Referral Analysis

**Comment by bferguso** [comment]
Created the model under the temporary name "Shifting Sandcastle"

**Comment by emjohnst** [comment]
When adding new project, "BC Fossil site location" should be renamed to "Project Boundaries" or something similar

**Comment by emjohnst** [comment]
Not seeing ability to "select by feature" for map overlays

**Comment by emjohnst** [comment]
Need ability to support Shapefiles and KMZ files for referrals

**Comment by bferguso** [comment]
Leaving KMZ & Shapefile out of scope for this ticket. See associated tickets in description.
