### ISSUE TITLE
Add detail to Significance Ranking Detail

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#605]
In the list of Significance Ranking Details, the choice "Education value" is missing 

Add "Education value" in the Fossil Collection Event Resource Model - Significance Ranking Details under Collection Event Significance

Add "Education value" in the Fossil Site Resource Model - Significance Ranking Details under Significance Ranking Code

**Comment by bferguso** [comment]
Was a concept that hadn't been added to the collection
