### ISSUE TITLE
Allow import of Shapefile

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#608]

**Comment by emjohnst** [comment]
@bferguso this functionality doesn't seem to be working. I've tested 5 different shapefiles - I drag and drop the shapefile but nothing happens. In one case, the page became unresponsive. In the other four cases I noticed the same!
 error message in the console (image attached).

[Image](https://github.com/user-attachments/assets/6a10cf4e-2216-4653-b9aa-a6d2de8cbcbc)

**Comment by bferguso** [comment]
@emjohnst  - Would you please send me a copy of the shapefile(s) you were using to test this?

**Comment by bferguso** [comment]
Of the 4 zip files sent by email, 3 of them imported successfully for me, but the SaddleMtLookoutTrail.zip file didn't. The Saddle Mt is a zipped KML file, not a Shapefile, so I wouldn't expect that to import properly. After unzipping it I was able to import the doc.kml file successfully. See here for all the geometries: https://testapps.nrs.gov.bc.ca/bcrhp/resource/2a354dd4-f1c9-4592-bf85-8524bfcfabe7#

Moving back to Review/QA.
