### ISSUE TITLE
Populate Civic Address Notes from Location_______ HRIA table

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#609]
- [x] Identify source
- [x] Update loads
- [ ] Add "Site Access" RTF as a field to Historic Site Resource Model under "Location Description"/Civic Address Notes field and populate with "siteaccess" data

**Comment by bferguso** [comment]
@emjohnst - Is this from the site_location.accuracy_remarks column? (eg - for EfQo-4 site it is "Location changed based on detailed site map. Geometry changed based on legacy status." or site EeRe-19 it is "Location not changed based on detailed site maps.  Geometry changed based on detailed site map.  Location matched to railway and creek."
)

**Comment by emjohnst** [comment]
Nope those are spatial accuracy remarks

**Comment by bferguso** [comment]
Found the source. There is another column "siteaccess" that is also populated in 800+ records. Concatenating all values with newlines and populating the `Civic Address Notes` field with the result.

**Comment by emjohnst** [comment]
@bferguso  Please add "Site Access" as a field to Historic Site Resource Model under "Location Description"/Civic Address Notes field and populate with "siteaccess" data

**Comment by emjohnst** [comment]
Site access field has been determined to belong with legacy arch data resource model to be developed. Closing issue.
