### ISSUE TITLE
Add "How To" video and/or manual to landing page

### ISSUE THREAD

**Issue by KatieMcEvoy** [bcgov/BCHeritage#629]
- [x] Link to the user manual
- [x] add a how to video

2024-06-11 still in developement, dependency on other tickets

**Comment by emjohnst** [comment]
Basic Video link: [https://youtu.be/kn4lAEU2NNc](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyoutu.be%2Fkn4lAEU2NNc&data=05%7C02%7CEmerald.JohnstoneBedell%40gov.bc.ca%7C7ddb814e93d948559a8208dcb0d9bfad%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638579696468283511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=tCPGwXlmXrbpkL8w7s8ns3dA4MlHvvBO5htrOg%2BtG4E%3D&reserved=0)

Advanced Video link: [https://youtu.be/qkpAsaczhn8](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyoutu.be%2FqkpAsaczhn8&data=05%7C02%7CEmerald.JohnstoneBedell%40gov.bc.ca%7C7ddb814e93d948559a8208dcb0d9bfad%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638579696468295992%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Nv63f7qoz6SU7omNUhuczMcvBdKm5kng5XLn5mzjeRo%3D&reserved=0)

**Comment by bferguso** [comment]
Changes made to index.htm in branch bcrhp/release/1.1.2. Changes pushed manually into PROD.
