### ISSUE TITLE
Reformat PID and PIN

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#642]
Where: 
Historic Site Resource Model
BC Property Legal Description 

- [x] update PID and PIN field to numeric type field
- [ ] put non-numeric PID/PIN info in legal description notes prefaced by "Non-numeric PID/PIN information to be reviewed: "

- [x] Rename PID > "PID (Parcel Identifier)"
- [x] Rename PIN > "PIN (Parcel Identification Number)"
- [x] Display fields side by side so they appear on one line and add "or" between them
To be displayed on one line as:
 PID (Parcel Identifier) [9 digit box] or PIN (Parcel Identification Number) [numeric box]

**Comment by bferguso** [comment]
We can't move the label before the boxes, but the rest has been implemented in Dev.

**Comment by emjohnst** [comment]
@bferguso should I be able to see it in dlvr or not yet? Wasn't there this morning

**Comment by KatieMcEvoy** [comment]
PIN field is not numeric (accepts letters).

**Comment by bferguso** [comment]
Make it a numeric field and add better widget later?

@emjohnst - Currently there are a number of sites with non-numeric PID values. Sent by Teams.
