### ISSUE TITLE
Export Button Content

### ISSUE THREAD

**Issue by KatieMcEvoy** [bcgov/BCHeritage#644]
Remove jargon from export button - not sure what Celery means
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2VDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b44f829fab3da034c7904c3195bc7ca738848fe4/Celery.JPG)

**Comment by emjohnst** [comment]
Text no longer appearing.
