### ISSUE TITLE
Review Source of Spatial Data

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#648]
- [x] Look at source of spatial data
- [x] resolve 1261 sites missing spatial data. 

Might be because their location is not published in the BCGW. DgRr-41 is example site with spatial data in HRIA but missing in Arches.

Notes from conversation on this topic:

1261 without entries in the HISTORIC_ENVIRONMENT_SP layer and 131 that don't exist in the SITE_LOCATION table (this has the point data that we're not  currently using)

For the ones that are missing polygon data here are the statuses / row counts:
Federal Jurisdiction	3
Cancelled Record	22
Registry Candidate	60
Legacy	7
Registered	77
Decision Pending	126
Recorded/Unprotected	966

**Comment by emjohnst** [comment]
Arch branch did a report on how many historic sites in HRIA are missing spatial information and it was only 131

**Comment by bferguso** [comment]
@emjohnst  - the 131 sites matches the comment above - found that 131 didn't have entries in the SITE_LOCATION table. We had previously determined that the point data was not reliable but perhaps we should use it for sites that don't otherwise have a geometry?

Is there another restricted BCGW layer that we could source that may have geometries not listed in the HISTORIC_ENVIRONMENT_SP table?

**Comment by bferguso** [comment]
This appears to have been resolved by using the entire set of HRIA sites for the geometry sites.

**Comment by emjohnst** [comment]
@bferguso  Excellent! - just curious I tried to remove "registry candidate" and "decision pending" statuses from all of our records to come over - I did that a few months ago and up in the description you had said some of the missing polygons had that status type. I wondered if you could do a check that any Historic place = y and historic place = no does not have registry candidtate and decision pending

**Comment by emjohnst** [comment]
@bferguso this seems complete?

**Comment by bferguso** [comment]
@emjohnst  - Yes, I believe this is complete. As long as all sites that you expect to have geometries have geometries we should be good.
