### ISSUE TITLE
Map Layers to Add, Remove, Update, and Order

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#665]
Also Specifying below which map layers are internal/public.
iMap link for styling: https://maps.gov.bc.ca/ess/hm/imap4m/

Updates
- [x] Replace Indigenous Reserve Boundaries with Indian Reserves and Band Names: (Please name this layer Indigenous Reserves and Band Names) https://catalogue.data.gov.bc.ca/dataset/indian-reserves-and-band-names-administrative-boundaries 
iMap Layers: 
Indian Reserves including Band Names - Colour Filled
Indian Reserves including Band Names - Outlined

Additions
- [x] Islands Trust Administrative Boundaries Outlined: https://catalogue.data.gov.bc.ca/dataset/islands-trust-legally-defined-administrative-areas-of-bc
iMap layer: Islands Trust - ABMS - Outlined *just outline
- [x] Local Trust Administrative Boundaries: https://catalogue.data.gov.bc.ca/dataset/local-trust-areas-legally-defined-administrative-areas-of-bc
iMap layer: Local Trust Areas - ABMS - Outlined *just outline
- [x] Tourism Regions: https://catalogue.data.gov.bc.ca/dataset/bc-tourism-regions
iMap layer: Tourism Regions *outline
- [x] Tantalis surveyed parcels https://catalogue.data.gov.bc.ca/dataset/tantalis-surveyed-parcels
iMap layers:
Land Act Survey Parcels - Tantalis - Legal Descriptions
Land Act Survey Parcels - Tantalis - Outlined

Removals
- [x] National Resource Boundaries
- [x] NTS 1:250K
- [x] NTS 1:50K
- [x] Provinces and States
- [x] Trim Contours

- [x] Reorder Maps to Appear in this order:
Cadastral ParcelMap - Public
Municipal Boundaries - Public / Filter
Regional District Boundaries - Public / Filter
Indigenous Reserves and Band Names - Internal / Filter
Islands Trust Administrative Boundaries - Internal / Filter
Local Trust Administrative Boundaries - Internal / Filter
Tourism Regions - internal / Filter
Digital Road Atlas - Public
Trim Water Lines - Public
Lakes - Public
Rivers - Public (updated 2024-07-03)
Streams - Public (updated 2024-07-03)
Crown tenures - Internal
Tantalis Surveyed Parcels - Internal
National parks - Public
Provincial Parks - Public / Filter
Municipal Parks - Public
Borden Grid - Public
Heritage Sites - Site Boundary - Public

**Comment by emjohnst** [comment]
@bferguso For public site, I'm suggesting these layers made to be internal only - for the reason to reduce clutter to users as I am pretty sure all these layers are public, but I'm not sure about the crown tenure one?

Indigenous Reserve Boundaries and Band Names
Islands Trust Administrative Boundaries
Local Trust Administrative Boundaries
Trim Water Lines
Crown tenures

**Comment by bferguso** [comment]
@jrods - Need to think a bit about the best way to modify overlays as part of the CI/CD process. There is a management command that can be used to remove/add overlays from using JSON config files. It may be better to perform the order and setting the public flag using migrations though.

**Comment by JessicaInTime** [comment]
@emjohnst there is also the Stream and Rivers mapbox layers, where would you like them in the ordered list?

**Comment by emjohnst** [comment]
@jrods added streams layer in body of ticket above!

**Comment by JessicaInTime** [comment]
@emjohnst Streams, Rivers are 2 different layers

**Comment by emjohnst** [comment]
@jrods Updated!

**Comment by bferguso** [comment]
@We'll need to test the public/private after the OIDC changes are in (#910)

**Comment by emjohnst** [comment]
Done in test
