### ISSUE TITLE
Map Card Text for Overlays

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#666]
This ticket is dependent on #665 

Quotations indicate the label to appear on map card, brackets are the data column name.

Cadastral ParcelMap https://catalogue.data.gov.bc.ca/dataset/parcelmap-bc-parcel-fabric-fully-attributed
Keep Owner Type
Keep Municipality
- [x] Remove Plan #
- [x] Remove Parcel Class
- [x] Add "PID:" (PID_NUMBER)
- [x] Add "PIN:" (PIN) 
- [x] Add "Legal Description:" LEGAL_DESCRIPTION

Indigenous Reserves and Band Names
- [x] "Band Name:" (BAND_NAME)

Islands Trust Administrative Boundaries Outlined
- [x] "Admin Area Name:" (ADMIN_AREA_NAME)

Local Trust Administrative Boundaries
- [x] "Admin Area Name:" (ADMIN_AREA_NAME)
- [x] "Admin Area Group Name:" (ADMIN_AREA_GROUP_NAME)

Tourism Regions
- [x] "Region Name:" (TOURISM_REGION_NAME)

Tantalis Surveyed Parcels
- [x] "Identifier:" (LAND_TITLE_OFFICE_IDENTIFIER)
- [x] "Parcel Type:" (PARCEL_TYPE)

Update information displayed on map cards for Heritage Site - Site Boundary Layer

- [x] #989
- [x] Remove Borden Number (displayed above with site name)
- [x] Add City

**Comment by bferguso** [comment]
@jrods - Are you still unable to operate the checkboxes? Are you logged in?

**Comment by JessicaInTime** [comment]
@bferguso apologies missed marking the ones that in changes. I didn't see the Add City, I will need to update the PR for that data.

**Comment by emjohnst** [comment]
Done in test
