### ISSUE TITLE
Review Street Address Data Cleaning Manually

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#673]
- [x] Brett provide spreadsheet of verified street addresses closer to MVP
- [x] Have a discussion about best approach prior to modifying spreadsheet
- [x] E and K to Review spreadsheet of street addresses run through bc gov API verification
- [x] E and K Make note of problematic ones
- [x] Update process to upload spreadsheet with exceptions and manual corrections
- [x] Update loads to use manual corrections in validation spreadsheet
- [ ] E and K to note and correct remaining / outlier problems in Arches

**Comment by bferguso** [comment]
Need to wait for resource model updates being made directly in DLVR (Help text and required fields)

**Comment by bferguso** [comment]
Site with PID 011752033 was the only legal address that was not able to be validated - this must have been entered/updated since the original extract in October. May want to include this cleanup in Arches after MVP.

**Comment by emjohnst** [comment]
@bferguso I will add this to manual clean up ticket
