### ISSUE TITLE
Create Locality field - Heritage Site Resource Model

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#689]
- [x] Create "Locality" field - free text
- [x] Capture data from Location Description "Locality"

**Comment by bferguso** [comment]
Based on the data, the assumption that the Locality part of the location description is at the end, starting with the text "Locality:".
Added location descriptions unchanged and updated those with the term "Locality" in them to keep an audit history.

**Comment by bferguso** [comment]
Pushed to DLVR.
