### ISSUE TITLE
Review existing data to verify no private sites/info are available

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#698]
Private/Non-public sites defined as:

Officially Recognized = 'No'
Where Registry type is not 'Registered' or 'Federal'
Where any sites marked as Restricted are not accessible

Specific fields that are not public access:
- official recognition details notes
- legal address notes
- chronology source of dates
- remarks
- decision history
- all documents until reviewed

Data to be reviewed:
image description, document description, location description, images

**Comment by bferguso** [comment]
I think the criteria above is incomplete - it is missing the BCRHP Submission Status = "Approved - Basic Record" and "Approved - Full Record" criteria.

**Comment by emjohnst** [comment]
Done in test
