### ISSUE TITLE
Providing Access to QA team members

### ISSUE THREAD

**Issue by SMFERNAN** [bcgov/BCHeritage#710]
Hi Brett,

I am bringing on some QA support so the Product Owners can setup their UAT, please could the QA team members be granted access to BCFMS and BCRHP in Test (the same access Emerald and Elisabeth have)? 

Please could you also provide them with access to Github? Are as below
Pratibha
Jonathan 
Lizette

**Comment by bferguso** [comment]
Details removed after implementation. @SMFERNAN  - they should now have access to both DLVR and TEST for both BCFMS and BCRHP.
