### ISSUE TITLE
Documents Issue - Heritage Site Resource Model

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#712]
Documents that are image file types, uploaded via the document uploader are appearing as images in the Record View. Would prefer if these were downloadable links like PDFs, or perhaps these need to be converted to PDFs?

Example record, Hat Creek Ranch EfRi-44
Document Site_Map

**Comment by bferguso** [comment]
By default Arches will display any photographs/images that can be rendered on the screen (jpg, gif, etc). This will require the implementation of a custom widget and has no bearing on the resource model. The widget is configured to only allow PDFs for any new data which should be rendered properly. We could: 
1. convert the formats on upload (which would require pre-MVP effort)
2. do some sort of post-MVP conversion to change the formats after MVP
3. accept that the historical data for those records are displayed as-is
4. create a widget to not render the files, regardless of the format.

My preference would be either 2 or 3 to try to keep mvp on track as best we can.

**Comment by emjohnst** [comment]
@bferguso @KatieMcEvoy Let's do 3 for now and revisit this ticket post-mvp to consider option 3.

**Comment by emjohnst** [comment]
No longer priority
