### ISSUE TITLE
Populate "Approved" drop down option with HRIA Data > CRHP Admin table > "Is accepted by feds" field

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#713]

**Comment by bferguso** [comment]
1. There are 29 records with Fed IDs assigned but isacceptedbyfeds is not 'Y'. Should we assign these to be "Accepted"? - "Submitted" State (If there is a submitted date - that should be good)
2. There are 3 records where isacceptedbyfeds = 'N'. Should we set those to Ineligibile? -> Incomplete State (TBD)

**Comment by emjohnst** [comment]
@bferguso 
1. Yes - submitted
2. I guess we need a state that is "Incomplete" for CRHP, can you please add that? I'll update that other ticket...

**Comment by bferguso** [comment]
@emjohnst , @KatieMcEvoy  This will be affected by any updates that will be made to the BCRHP and CRHP statuses. Perhaps those changes can go in this ticket.

**Comment by emjohnst** [comment]
@bferguso updating this ticket in light of the changes:
1. Do these sites have a submission date? If so, they should be Submitted
2. If accepted by feds is No - put to "updated required" - that will flag me to take a look at them

**Comment by bferguso** [comment]
Moving to Review/QA - additional changes handled in ticket #575
