### ISSUE TITLE
Populate Federal ID Number field with HRIA Data > CRHP Admin table > "Fed name"

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#716]

**Comment by bferguso** [comment]
There are two records with non-numeric Fed IDs: (DgRx-114 & DcRu-355) and 5 more that have 6 digits (DgRs-90, EeQt-40, DiQv-74, DiQv-75, DjQv-48). Is it possible to clean those up in HRIA?

**Comment by emjohnst** [comment]
@bferguso Hi Brett, I corrected the ones with non numeric IDs in HRIA. The other values are accurate though because it is an identifier by count

**Comment by bferguso** [comment]
@emjohnst  - `it is an identifier by count` - Is this referring to the 6-digit values? If so we will need to change the constraint on that field from 5 digits to 6 then. Are you good with that?.

Just to confirm - in the end all values just have the characters 0-9?

**Comment by emjohnst** [comment]
@bferguso yes let's change constraint to 6 digits and yes will still be all numeric
