### ISSUE TITLE
Symbol differentiation for microfossil and macrofossil

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#717]
For collection event site display on the map:

- [x] make macrofossils a blue square
- [x] make microfossils a red triangle
- [x] green pentagon for sites with both macro and micro

**Comment by bferguso** [comment]
@LeannePyle, @elisabethdeom  - Did you not want to keep the same formatting you have on the example output you provided? Also, I've made barren / unknown (no micro or macro) a grey dot.

**Comment by LeannePyle** [comment]
Yes, that uses a green pentagon - corrected above and good to include the barren samples with grey dot

**Comment by LeannePyle** [comment]
last look in Arches - macro was red, please change:

- [x] make macrofossils a blue square - not a light blue, but to match existing output - see emailed example
- [x] make microfossils a red triangle

**Comment by bferguso** [comment]
@LeannePyle  - I pulled the colour codes from the sample Elisabeth sent to me. Updated colour to match what you sent me today and swapped the macro/micro colours.

Implemented in DLVR. Please have a look.
