### ISSUE TITLE
Rename Notes fields and reformat description fields

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#721]
This ticket is to: 
1) Rename notes fields for consistency across Heritage Site Resource Model and indicate which notes field are internal; and 
2) identify rich text fields to plain text fields to remove coding from csv outputs.

Rename fields
- [x] Heritage Site Location, Legal Address Notes > **Legal Address Internal Notes** - both graph and card labels
- [x] Official Recognition Details, Notes > **Official Recognition Internal Notes** - card label only
- [x] Architects/Builders, Comments > **Architects/Builders Notes**  - graph - **Construction Actor Notes**, Card (visible) **Architects/Builders Notes**
- [x] Chronology, remarks > **Chronology Notes** - both

Change format from RTF to plain text
- [ ] ~Location Description~ Decided not to
- [ ] ~Legal Address Internal Notes~ Decided not to
- [x] Official Recognition Internal Notes
- [ ] ~Internal Remarks~ Decided not to

**Comment by bferguso** [comment]
@emjohnst  
- `Location description` and `Internal Remarks` are multi-line fields in HRIA. What do you want to do with the HRIA data if we make it a plain text field. There are many instances of those fields that are quite long too so they won't display very well in a single-line format.
- Legal Address Notes is being used to concatenate a number of fields from HRIA in multiple lines. How would you like to represent multiple values in a single line? Maybe "[value]", "[value]"... ?
