### ISSUE TITLE
List of Overlays in IPA Project Site

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#722]
In the overlay choices, Important Fossil Areas, Provincially Protected Fossil Site, and Fossil Collection Events missing

**Comment by bferguso** [comment]
@LeannePyle - Where are you seeing this? I see this in both DLVR and TEST:
<img width="364" alt="image" src="https://github.com/bcgov/BCHeritage/assets/6750642/9e7e699e-b6f2-4fa6-8b89-f422baffb7c3">
