### ISSUE TITLE
Map Card Text Historic Sites

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#723]
Update information displayed on map cards for Heritage Site - Site Boundary Layer

- [ ] Add link to Details page on map card pop-up.
- [ ] Remove Borden Number (displayed above with site name)

See issue #666 for other map card text styling for other layers- if those are mvp or no?

**Comment by bferguso** [comment]
None of the above or items in #666 need to be part of MVP from a technical perspective. They are all configuration changes not Resource Model related. Feel free to assign/remove the mvp label this ticket and #666 as you'd like, based on the priority of other issues. I'd say that this should be much lower on the list than HRIA Borden Number retrieval and CRHP XML output functionality.

**Comment by emjohnst** [comment]
Okay, I'll put these in post mvp swim lane. This one is priority for public site.

**Comment by emjohnst** [comment]
Closed in favour of 666
