### ISSUE TITLE
Review Records Image Type to Fix Image Captions

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#727]
These records had "Image, Other" type in HRIA. Need the appropriate image caption information completed post-mvp:
The vast majority of the "Image, Other" values are URLs - there are only 29 that are actually images. Here they are:

- [x] DcRu-1148
- [x] DcRu-1149
- [x] DcRu-162
- [x] DcRu-991
- [x] DcRw-32
- [x] DcRw-32
- [x] DdRu-124
- [ ] DgRp-14 - Site record broken link in images
- [x] DgRp-4
- [x] DgRp-4
- [x] DgRq-61
- [x] DgSl-54
- [x] DhRp-67
- [x] DhRr-110
- [x] DhRr-269
- [x] DhRr-76
- [x] DhRs-1303
- [x] DhRs-716
- [x] DjPv-37
- [x] DjQe-2
- [x] DjQe-2
- [x] DjQe-2
- [x] DjRi-100
- [x] EdQj-1
- [x] EkRo-124
- [x] FbSr-22
- [x] GeRd-2
- [x] HhTf-5
- [x] HhTf-6

**Comment by KatieMcEvoy** [comment]
@bferguso just looking at the first few. It looks like .jpgs with no type given are showing up as Image, other. there seem to be multiple/record and I anticipate a good amount of maps and sketches. Is there a specific way I should proceed?

**Comment by emjohnst** [comment]
@bferguso is it possible to do a search in the images for broken/non-accepted file types as in the case of DgRp-14? It appears a PDF document was put in with images but it appears as a broken link. The Pre-2021 site record was not associated with the record in HRIA. I went looking for it the S3 storage to download and save it to Documents.

**Comment by emjohnst** [comment]
Created spin-off ticket for the broken image link issue. This task is complete.
