### ISSUE TITLE
Reconcile and fix CRHP and HRIA submission status data

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#729]
Should reconcile and fix the data that is in CRHP with what is in HRIA.

Sites listed as Listed / Published in CRHP but do not have is accepted by feds = 'Y':
DcRu-1260
DcRu-1423
DcRu-1424
DcRu-1431
DcRv-190
DdRt-33
DeRt-125
DeRw-36
DfSj-122
DgQn-46
DgQq-29
DgQq-30
DgRd-2
DgRq-88
DgRq-89
DgRq-90
DgRr-56
DgRr-59
DgRs-117
DgRs-118
DgRs-119
DgRs-93
DgRt-28
DhRg-11
DhRg-12
DhRr-402
DhRs-1126
DhRs-895
DhRt-125
DhRx-120
DiQh-12
DiRa-42
DkQi-22
DkQi-23
DkQi-24
DlQh-15
DlQi-20
EaQi-7
EbRj-219
EdQs-37
EdQs-38
EdRo-50
EdSr-49
EeQu-8
EeRf-23
EeRn-87
EfRq-8
EiRh-29
FaRa-4
FeRk-19
FhRm-16
GfTm-13

**Comment by bferguso** [comment]
@KatieMcEvoy, @emjohnst  - Just making sure this is on your radar.

**Comment by KatieMcEvoy** [comment]
@bferguso @emjohnst These have all been changed to Is Accepted by Feds = Y.

**Comment by bferguso** [comment]
OK, great. Moving to Review/QA so can check that things look right in Arches.

**Comment by KatieMcEvoy** [comment]
@bferguso @emjohnst Looks good, closing ticket.
