### ISSUE TITLE
Spatial Data Missing

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#730]
Site DhRr-923 is missing spatial location data in Arches but has its spatial location data in HRIA.

**Comment by bferguso** [comment]
Are there geometries in HRIA that don't end up in the BC Geographic Warehouse?: https://catalogue.data.gov.bc.ca/dataset/historic-environment-spatial-layer ?

I haven't updated the pull from the BCGW for months so if that is a relatively site that could be part of it. If there are geometries that don't go to the BCGW we'll need to find another source to extract them.

**Comment by emjohnst** [comment]
@bferguso it was added in May 2022. I thought we did a search of sites missing spatial information - 131, and that aligned with the 131 sites missing spatial information in HRIA. Is there another search we could do in Arches to find out how many more there might be?

**Comment by bferguso** [comment]
So this doesn't appear to be in the BCGW spatial layer - I just updated it and reloaded. We'll need to see if there is some other place we can get this. This is related to #648

**Comment by bferguso** [comment]
Obtained the set of full sites from arch and used those to create the geometries. Appears that has resolved the issue (at least for the site above).

**Comment by emjohnst** [comment]
@bferguso Excellent, I can see its geometry now.
