### ISSUE TITLE
Official Recognition Info Missing

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#731]
Site DcRu-1225 - 611 Vancouver Street is appearing as grey in Arches map view and missing Official Recognition Info - Registration Status and Registry Type and the sub card with the official recognition details.

In HRIA the site is an active Heritage Designation with a full record of the official recognition details. In HRIA it is missing registry type but that shouldn't prevent the rest of the recognition information from being transferred.

**Comment by bferguso** [comment]
I'm not seeing an entry in the TFM_REGISTER_TYPE table. Is that a valid state for a record of this type?

**Comment by emjohnst** [comment]
@bferguso It is possible some records might be missing registry type in HRIA due to error. But generally all records should have a registry type.

**Comment by bferguso** [comment]
Here is a list of sites that don't have a register type:
DcRt-58: determined to be part of arch site DcRt-44 - changed Is Historic Place to null
DcRu-1225
DcRu-1252: cancelled record
DcRu-1253: cancelled record
DcRu-695: cancelled record
DeSb-1:
DfRv-137
DfRw-104
DgQv-30: cancelled record
DhQd-8:cancelled record
DhRe-2: cancelled record
DhRs-1384
DhRs-188: cancelled record
DhRs-27: cancelled record
DhRs-835
DkSr-12: cancelled record
EbQu-44: cancelled record
EcPx-28: cancelled record
EdQa-10: cancelled record
EeQa-6: cancelled record
EeRb-56: cancelled record
EeRe-27: cancelled record
EiRb-21: cancelled record
FfRo-29
FhUa-20: cancelled record
FhUa-22: cancelled record
HaRk-30: cancelled record

**Comment by KatieMcEvoy** [comment]
I updated the non-cancelled records
