### ISSUE TITLE
Updates to Site Admin Card

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#737]
- [x] Make "In progress" default value for BCRHP submission status
- [x] Reorder BCRHP Submission status:
 In progress
Submitted
Update Requested
Approved - basic Record
Approved - full record

- [x] Reorder CRHP Submission status:
Ineligible
Submitted
Update Required
Approved
Removed

**Comment by bferguso** [comment]
As discussed this morning, the sort order is not being honoured when deploying to ENDOWMENT. Not fixing now as I believe this is a lower priority.

**Comment by emjohnst** [comment]
Closing this ticket and opening another bug ticket for this issue without mvp label as it is low priority
