### ISSUE TITLE
MVP Task - Create Copy of Legacy Arch HRIA Data

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#739]
Create a copy of prod data from these tables and save until Legacy RM is built. Related to Epic 645.
Do a test to make sure data from specific fields listed in epic subtickets #645 have all been captured.

Tables
- [x] TFM_ARCH_CULTURE
- [x] TFM_CONDITION
- [x] TFM_DECISION_HISTORY
- [x] TFM_LOCATION
- [x] TFM_MAP_REFERENCE
- [x] TFM_SITE_VISIT
- [x] TFM_SITE_VISIT_TEAM
- [x] TFM_SITE_VISIT_ROLES
- [x] TFM_CULTURAL_MATERIAL

Views
- [x] V_TFM_FEATURE_CMT
- [x] V_TFM_FEATURE_CULT_DEP
- [x] V_TFM_FEATURE_ROCK_ART
- [x] V_TFM_FEATURE_GENERAL
- [x] V_TFM_REFERENCE_TV
- [x] V_TFM_STRATIGRAPHY_SITE
- [x] V_TFM_TYPOLOGY

Materialized Views
- [x] VMV_TFM_FEATURE

**Comment by bferguso** [comment]
- [ ] Some of the objects above are vews and materialized views. Created tables from them.
- [ ] The V_TFM_REFERENCE_TV view doesn't link back to a site - is that OK? Is it a standalone table? Is it OK to pull the whole table? I can't see a way to filter your data from Arch.

**Comment by emjohnst** [comment]
@bferguso we need the references to link back to a site - this is where other government records about the site are referenced (past permits, reports, published documents etc.) its pretty important

**Comment by bferguso** [comment]
Tables are now being copied to the target servers as part of the data refresh. They have been put in a schema called `hria_archive` as the table names above. Have done minor denormalization to include the borden number in all tables.
CSV export sent to BCRHP by way of SOFT. File is available for the next 7 days.

**Comment by emjohnst** [comment]
@bferguso Looking good, just noted a couple of missing things:

- [x] Missing TFM_Disturbance table
- [x] Missing tables I listed under TFM_MAP_reference but perhaps they are there own tables. They are "GIS History" "NTS Reference" and "Other maps"

**Comment by bferguso** [comment]
@emjohnst  VMV_TFM_FEATURE - I'm seeing these rows in the dataset. I'm not sure that the csv files are ordered. Can you confirm that you're not seeing it? Wondering if maybe it is another case of Excel not aligning the data properly.

**Comment by emjohnst** [comment]
@bferguso I am seeing that data in the spreadsheet now for VMV_TFM_FEATURE, ill update my above comment

**Comment by emjohnst** [comment]
Please send TFM disturbance, gis history, and nts reference and other maps tables to me by email.

**Comment by bferguso** [comment]
Exported all to CSV again, directly from the PROD database, and sent them to you via SOFT. Email sent this evening.

**Comment by emjohnst** [comment]
Received and saved on LAN Arches folder - HRIA Legacy Data
