### ISSUE TITLE
XML Bug error messages

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#742]
Resolve error messages in creating xml reports. Example record: DgQk-70

- [x] Resolve error message for xml reports DgQk-71 (Jan 22, 2024)

We weren't escaping the name values, just the SoS and multi-line strings.

I have also added the Image Copyright, Image caption, Image description, and Image Content Type to the set of fields that are being check for special characters (eg &).

 Are there any other fields that may have special characters in them?

**Comment by bferguso** [comment]
This was caused by the & character being present in the data. Used the sax escape function to resolve.

**Comment by emjohnst** [comment]
@bferguso noticing this same issue in Test database. Has this been resolved but is not in Test yet?

**Comment by emjohnst** [comment]
@bferguso Experience same issue in dlvr. Attached error message for DgQk-71 and moved this ticket to in progress.

<img width="863" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGpxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e843d94a3d4d123dbe4ad44da2063b5e37a224fb/XML%20issue.JPG" alt="XML issue.JPG" />
