### ISSUE TITLE
Testing delete function on Collection Event search card

### ISSUE THREAD

**Issue by LeannePyle** [bcgov/BCHeritage#744]
Trying to figure out how to test the delete function - clicking the trash can icon on the Edit search card takes user to the "Add" - so is the instruction to only use the pencil icon for editing which also allows deleting?

**Comment by bferguso** [comment]
Deleting a resource is done by editing a resurce and then using the Manage -> Delete Resource buttons on the top left corner of the screen:
<img width="288" alt="image" src="https://github.com/bcgov/BCHeritage/assets/6750642/baa1b74d-42ef-423c-8e7c-9a9bd47abf84">
