### ISSUE TITLE
PIN data issue

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#747]
Reviewed Emily Carr record and noticed it has a PID as well as PIN number. My understanding is that properties only have one. Upon checking BC Assessment I only see the PID listed. Not sure where the PIN number data for this record came from - can you check why that might have happened? Also see ticket #642 about reformating PID and PIN.

**Comment by bferguso** [comment]
@emjohnst - The PIN came from validating using the WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_FA_SVW layer looking using the PID as a key. We don't need to add those if you don't want them. I'll get to #642. How are we on all the resource model changes. We need to finalize those ASAP so if there is anything outstanding we should tackle that first.

**Comment by emjohnst** [comment]
@bferguso The Epic #670 has all the resource model updates

**Comment by emjohnst** [comment]
Closing this issue as was able to identify source of PIN and seems correct and fine to add to records that have both PID and PIN
