### ISSUE TITLE
Heritage Site Card and PDF Print out

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#752]
Could we see a test of two-column format for this page and print out? Where text is all in one column that is more wide and images slightly bigger in the second column? This is to reduce the big white space gaps between the two text columns

Heritage Site Card
Remove duplicate date in right corner
Rename Name to "Site Name" - only include common name
Borden number - keep
- [x] Rename Civic Addresses to "Property Address(es)
- [x] Registry Types - keep
- [x] Rename Significant Events to Construction Date(s) and only include construction date types
- [ ] Legislative Acts - keep full act, filter out expired acts
- [x] Move SoS Type Above 'Description" header and replace with "Provincial Statement of Significance" and "Local Government Statement of Significance" - just keep description.

Heritage Site PDF

- [ ] ~Remove teeny tiny date and time stamp in upper left corner~ - This is a browser print setting
- [x] Remove duplicate date appearing next to date on right corner
- [x] Remove Right and left scroll bars
- [x] Replace Heritage Site Name at top with "BC Register of Historic Places"
- [ ] ~Remove the tinier "Bc Register of Historic Places - Search"~ - This is a browser print setting
- [x] Rename Name to "Site Name" and only display "Common Name"
- [x] Borden number - keep
- [x] Rename Civic Addresses to "Property Address(es)
- [x] Remove Registry Types
- [x] Rename Significant Events to Construction Date(s) and only include construction date types
- [ ] #762
- [x] Move SoS Type Above 'Description" header and replace with "Provincial Statement of Significance" and "Local Government Statement of Significance"
- [x] Add header for Heritage Values section
- [x] Add Header for Character defining elements section
- [x] Add header for Document Location
- [x] #763

**Comment by bferguso** [comment]
@emjohnst  - Can you please send me a copy of the PDF that your system is generating so I can see some of those elements described above?

**Comment by emjohnst** [comment]
[Carr House PDF Print Out.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2F4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2397de8d31d97f309d87ac28ee64fc7b89ff1ab/Carr%20House%20PDF%20Print%20Out.pdf)

**Comment by emjohnst** [comment]
@bferguso attached PDF above, this was using Chrome

**Comment by bferguso** [comment]
Struggling with getting to print across multiple pages. Pushing that off to separate ticket.
Do we want to limit number of images to 1 or 2 for print to facilitate layout? We could then spread the SOS sections across the entire page.

**Comment by emjohnst** [comment]
@bferguso yes we can limit images to 2.

**Comment by bferguso** [comment]
Spinning Legislative Act off as separate ticket. Need to prioritize Border Number generation and Data BC exports over this if we're going to have any chance of meeting current release target date.
Also - need to handle multi-page printout. Spinning that off as well.
