### ISSUE TITLE
CSV Output Update

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#754]
Make all fields available in csv output for MVP

**Comment by bferguso** [comment]
@emjohnst, @KatieMcEvoy - If I set you up with a clean version of the resource model in DLVR can I task you with doing this? If so, you'll need to add a short version of each label (10 characters or less). I can export that resource model and use it in the next deployment.

**Comment by emjohnst** [comment]
@bferguso @KatieMcEvoy yes, can you just give us a brief tutorial on how to do this again? Did we do this for the other resource models csv's as well? If not, maybe Katie can take on those ones
