### ISSUE TITLE
Fossils map sheet overlay styling

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#76]
@elisabethdeom  - Review all overlays and base maps and define overall look & feel 

Fossils Resources
- [x] Apply colours as outlined by @rajpersram (@bferguso to do)
- [x] Areas of Importance
- [x] Collection Events
- [x] Sites
- [x] Storage locations?

Overlays
- [x] Bedrock Geology
- [x] Cadastral layer - Public vs Private land. Change current formatting to match what is in iMap BC

Cadastral definitions (fill / border)
Crown Agency: 255,209,257 / 255,195,230
Crown Provincial: 255,190.232 / 255, 159, 229
Untitled Provincial: 206,180,253 / 167,150,198
Mixed Ownership: 252,128,114
Federal: 128, 177,211 / 117, 166, 209
Municipal: 36,174,96 / 48, 171, 69
Private 255,235,118 / 255,206,85
First Nations: 215, 194, 159 / 181,160,124
Unclassified: 157,157,157 / 135,135,135

**Comment by bferguso** [comment]
Custom map popups require changes in Arches core PR 4983

**Comment by rajpersram** [comment]
All colours outlined in [BC Gov Fossils Management System Color Scheme r2.dox](https://bcgov.sharepoint.com/:w:/r/teams/06270/Shared%20Documents/Project%20Documentation/User%20Experience/BC%20Gov%20Fossils%20Management%20System%20Color%20Scheme%20r2.docx?d=w79d0974712984e84b5f2e133468d42e0&csf=1&web=1&e=pG76tm) (found in Teams > Project Documentation > User Experience) have been applied. As far as I know, no other changes requested from @elisabethdeom.
