### ISSUE TITLE
order for the Site admin

### ISSUE THREAD

**Issue by KatieMcEvoy** [bcgov/BCHeritage#761]
CRHP drop down: 
"Ineligible"
"Submitted"
"Approved"
"Update Required"
"Removed"

BRHP drop down order:
"In Progress" - Record in progress but not ready for review
"Update Requested" - Previously submitted and approved record requires changes
"Submitted" - Submitted to BCRHP for review/approval
"Approved - Full Record"
"Approved - Basic Record"

Broken out from issue #575

**Comment by emjohnst** [comment]
Another ticket is open for this issue - Brett has implemented it but there is an issue that it is not appearing in test/dlvr - needs to be investigated post-mvp
