### ISSUE TITLE
Number of sites with full/basic approved record status

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#765]
Only 69 sites have approved - basic record status and 2067 have approved - full record.

Essentially, if a site is not approved-full record its status should be approved-basic record. 

There was a couple points in time when new users to HRIA database did not have permissions to flip sites to approved in HRIA but that should not account for the disparity in numbers we are seeing here. Any sites not flipped to approved in HRIA should have been - it was a technical error.

**Comment by bferguso** [comment]
Looks like the data is now correct in TEST.
