### ISSUE TITLE
Review BCGW layers

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#768]
Review tables of data for BCGW and make sure we still want to publish this data.

OBJECTID
BORDENNUMBER
ISHERITAGESITE
REGISTRATIONSTATUS
SITENAME
HERITAGETYPE
STREETNUMBER
STREET_NAME
CITY
PROVINCE
GOVERNMENTLEVEL
LEGALINSTRUMENT
ACTSECTION
PROTECTIONTYPE
REFERENCENUMBER
STARTDATE
EXPIRYDATE
- [ ] DATE_SOURCE - Remove
- [ ] DATE_FROMDATE - Rename STARTDATE
- [ ] DATE_FROMQUALIFIER - Remove
- [ ] DATE_TODATE - Rename ENDDATE
- [ ] DATE_TOQUALIFIER - Rename DATEQUALIFIER
DATE_HISTPLACETYPE
DIMENSIONS_AREA
STMT_DESCRIPTION
HERITAGEVALUE
CHARDEFELEMENTS
SIGNTYPE
DOCUMENTLOCATION
COMMENTS - What data is in here????
GISLATITUDE
GISLONGITUDE
PK - What is PK???
SHAPE

**Comment by emjohnst** [comment]
Data from Many Rows layer:

OBJECTID                      NUMBER,
  BORDENNUMBER                  VARCHAR2(13 BYTE),
  SN_SITENAME                   VARCHAR2(4000 BYTE),
  SN_TEMPORARYNUMBER            VARCHAR2(4000 BYTE),
  MR_GISLATITUDE                NUMBER,
  MR_GISLONGITUDE               NUMBER,
  MR_GISUTMEASTING              NUMBER,
  MR_GISUTMNORTHING             NUMBER,
  MR_GISUTMZONE                 NUMBER,
  MR_SPATIALACCURACY            VARCHAR2(20 BYTE),
  MR_MAPSHEETNUMBER             VARCHAR2(4000 BYTE),
  AD_LOCATIONDESCRIPTION        VARCHAR2(4000 BYTE),
  AD_SITEACCESS                 VARCHAR2(4000 BYTE),
  AD_ADDRESS                    VARCHAR2(4000 BYTE),
  AD_LEGALTYPE                  VARCHAR2(4000 BYTE),
  AD_LEGALNUMBER                VARCHAR2(4000 BYTE),
  AD_LEGALDESCRIPTION           VARCHAR2(4000 BYTE),
  TY_TYPOLOGY                   VARCHAR2(4000 BYTE),
  TY_FEATUREDESCRIPTIONSTRATUM  VARCHAR2(4000 BYTE),
  TY_LENGTH                     VARCHAR2(4000 BYTE),
  TY_WIDTH                      VARCHAR2(4000 BYTE),
  TY_HEIGHTAG                   VARCHAR2(4000 BYTE),
  TY_THICKNESS                  VARCHAR2(4000 BYTE),
  TY_DEPTH                      VARCHAR2(4000 BYTE),
  TY_DIAMETER                   VARCHAR2(4000 BYTE),
  TY_DEPTHBELOWSURFACEFROM      VARCHAR2(4000 BYTE),
  TY_DEPTHBELOWSURFACETO        VARCHAR2(4000 BYTE),
  TY_SHAPE                      VARCHAR2(4000 BYTE),
  TY_SLOPE                      VARCHAR2(4000 BYTE),
  TY_ORIENTATION                VARCHAR2(4000 BYTE),
  TY_SPECIES                    VARCHAR2(4000 BYTE),
  TY_SIDE                       VARCHAR2(4000 BYTE),
  TY_FLDESC                     VARCHAR2(4000 BYTE),
  AC_DESCRIPTION                VARCHAR2(4000 BYTE),
  DT_RCDUNADJUSTED              VARCHAR2(4000 BYTE),
  DT_RCDUNADJUSTEDVAR           VARCHAR2(4000 BYTE),
  DT_RCDADJUSTEDVAR             VARCHAR2(4000 BYTE),
  DT_RCDADJUSTED                VARCHAR2(4000 BYTE),
  DT_RCDREMARKS                 VARCHAR2(4000 BYTE),
  DT_TODATE                     VARCHAR2(4000 BYTE),
  DT_TODATEQUALIFIER            VARCHAR2(4000 BYTE),
  DT_TODATECALENDAR             VARCHAR2(4000 BYTE),
  DT_FROMDATE                   VARCHAR2(4000 BYTE),
  DT_FROMDATEQUALIFIER          VARCHAR2(4000 BYTE),
  DT_FROMDATECALENDAR           VARCHAR2(4000 BYTE),
  DT_METHOD                     VARCHAR2(4000 BYTE),
  DT_SOURCE                     VARCHAR2(4000 BYTE),
  DT_REMARKS                    VARCHAR2(4000 BYTE),
  DM_LENGTH                     VARCHAR2(4000 BYTE),
  DM_WIDTH                      VARCHAR2(4000 BYTE),
  CO_DESCRIPTION                VARCHAR2(4000 BYTE),
  CO_PERCENTINTACT              VARCHAR2(4000 BYTE),
  CO_CONDITION                  VARCHAR2(4000 BYTE),
  CO_STATUS                     VARCHAR2(4000 BYTE),
  CO_FACTOR                     VARCHAR2(4000 BYTE),
  CO_HISTORY                    VARCHAR2(4000 BYTE),
  CO_DISTDATE                   VARCHAR2(4000 BYTE),
  EV_GISELEVATIONUPPER          VARCHAR2(4000 BYTE),
  EV_GISELEVATIONLOWER          VARCHAR2(4000 BYTE),
  EV_USERELEVATIONLOWER         VARCHAR2(4000 BYTE),
  EV_USERELEVATIONUPPER         VARCHAR2(4000 BYTE),
  EV_COMMENTS                   VARCHAR2(4000 BYTE),
  SV_SITEVISITTYPE              VARCHAR2(4000 BYTE),
  SV_DATE_AFFL_PERM             VARCHAR2(4000 BYTE),
  SV_SVDESC                     VARCHAR2(4000 BYTE),
  SV_PERSONNAME                 VARCHAR2(4000 BYTE),
  SV_PERSONROLE                 VARCHAR2(4000 BYTE),
  SV_CMTYPE                     VARCHAR2(4000 BYTE),
  SV_CMSTAT_DET_DESC_REP        VARCHAR2(4000 BYTE),
  SV_CMDATE                     VARCHAR2(4000 BYTE),
  SV_CMLOCATION                 VARCHAR2(4000 BYTE),
  SR_AUTH_TITLE                 VARCHAR2(4000 BYTE),
  TN_TYPE                       VARCHAR2(4000 BYTE),
  TN_SUBTYPE                    VARCHAR2(4000 BYTE),
  TN_AGENCYNAME                 VARCHAR2(4000 BYTE),
  TN_REMARKS                    VARCHAR2(4000 BYTE),
  AU_GOVERNMENTLEVEL            VARCHAR2(4000 BYTE),
  AU_LEGALINSTRUMENT            VARCHAR2(4000 BYTE),
  AU_PROTECTIONTYPE             VARCHAR2(4000 BYTE),
  AU_REFERENCENUMBER            VARCHAR2(4000 BYTE),
  AU_STARTDATE                  VARCHAR2(4000 BYTE),
  AU_DESCRIPTION                VARCHAR2(4000 BYTE),
  RE_DATE_REM                   VARCHAR2(4000 BYTE),
  PK                            VARCHAR2(4000 BYTE) NOT NULL,
  REG_FORMRECEIVED              VARCHAR2(4000 BYTE),
  REG_ISPROTECTED               VARCHAR2(4000 BYTE),
  REG_REGISTRATIONDATE          VARCHAR2(4000 BYTE),
  REGAU_ACTSECTION              VARCHAR2(4000 BYTE),
  REGAU_EXPIRYDATE              VARCHAR2(4000 BYTE),
  REGTY_SITECLASS               VARCHAR2(4000 BYTE),
  REGTY_TYPE                    VARCHAR2(4000 BYTE),
  REGTY_SUBTYPE                 VARCHAR2(4000 BYTE),
  REGTY_SITETYPEDESCRIPTOR      VARCHAR2(4000 BYTE),
  REGTY_TYPOLOGYOBJECTID        VARCHAR2(4000 BYTE),
  REGPM_PERMITYEAR              VARCHAR2(4000 BYTE),
  REGPM_PERMITNUMBER            VARCHAR2(4000 BYTE),
  REGLD_PID                     VARCHAR2(4000 BYTE),
  REGLD_PIN                     VARCHAR2(4000 BYTE),
  REGCO_ASSESSBY                VARCHAR2(4000 BYTE),
  REGCO_ASSESSMENTDATE          VARCHAR2(4000 BYTE),
  REGCO_ISSUINGAGENCY           VARCHAR2(4000 BYTE),
  REGCO_PERMITNUMBER            VARCHAR2(4000 BYTE),
  REGCO_RECOMMENDATION          VARCHAR2(4000 BYTE),
  REGCO_REMARKS                 VARCHAR2(4000 BYTE),
  REGSN_ASSIGNEDBY              VARCHAR2(4000 BYTE),
  REGSN_SITENAMEDATE            VARCHAR2(4000 BYTE),
  REGMR_GISLATITUDE             VARCHAR2(4000 BYTE),
  REGMR_GISLONGITUDE            VARCHAR2(4000 BYTE),
  REGMR_HISTSOURCELATITUDE      VARCHAR2(4000 BYTE),
  REGMR_HISTSOURCELONGITUDE     VARCHAR2(4000 BYTE),
  REGMR_HISTSOURCEUTMZONE       VARCHAR2(4000 BYTE),
  REGMR_HISTSOURCEUTMEASTING    VARCHAR2(4000 BYTE),
  REGMR_HISTSOURCEUTMNORTHING   VARCHAR2(4000 BYTE),
  REGAD_STREETNUMBER            VARCHAR2(4000 BYTE),
  REGAD_STREETNAME              VARCHAR2(4000 BYTE),
  REGAD_CITY                    VARCHAR2(4000 BYTE),
  REGAD_POSTALCODE              VARCHAR2(4000 BYTE),
  REGRM_LENGTH                  VARCHAR2(4000 BYTE),
  REGRM_WIDTH                   VARCHAR2(4000 BYTE),
  REGRM_GISAREA                 VARCHAR2(4000 BYTE),
  REGEV_ENVOBJECTID             VARCHAR2(4000 BYTE),
  REGEV_USERELEVATION           VARCHAR2(4000 BYTE),
  REGEV_GISELEVATION            VARCHAR2(4000 BYTE),
  REGEV_TYPE                    VARCHAR2(4000 BYTE),
  REGEV_NAME                    VARCHAR2(4000 BYTE),
  REGEV_DESCRIPTION             VARCHAR2(4000 BYTE),
  REGFT_FEATURETYPE             VARCHAR2(4000 BYTE),
  REGFT_FEATURENUMBER           VARCHAR2(4000 BYTE),
  REGFT_LENGTH                  VARCHAR2(4000 BYTE),
  REGFT_WIDTH                   VARCHAR2(4000 BYTE),
  REGFT_DIAMETER                VARCHAR2(4000 BYTE),
  REGFT_DEPTH                   VARCHAR2(4000 BYTE),
  REGFT_DBSFROM                 VARCHAR2(4000 BYTE),
  REGFT_DBSTO                   VARCHAR2(4000 BYTE),
  REGFT_SHAPE                   VARCHAR2(4000 BYTE),
  REGFT_ORIENTATION             VARCHAR2(4000 BYTE),
  REGFT_BERMRIM                 VARCHAR2(4000 BYTE),
  REGFT_REMARKS                 VARCHAR2(4000 BYTE),
  REGFT_COLOUR                  VARCHAR2(4000 BYTE),
  REGCM_STATUS                  VARCHAR2(4000 BYTE),
  REGCM_DETAILS                 VARCHAR2(4000 BYTE),
  REGCM_REPOSITORY              VARCHAR2(4000 BYTE),
  REGST_MINDEPTH                VARCHAR2(4000 BYTE),
  REGST_MAXDEPTH                VARCHAR2(4000 BYTE),
  REGST_COMMENTS                VARCHAR2(4000 BYTE),
  REGSD_CULTURAL                VARCHAR2(4000 BYTE),
  REGSD_MINDEPTH                VARCHAR2(4000 BYTE),
  REGSD_MAXDEPTH                VARCHAR2(4000 BYTE),
  REGSD_REMARKS                 VARCHAR2(4000 BYTE),
  REGAC_CULTURENAME             VARCHAR2(4000 BYTE),
  REGAC_MATERIALDESCRIPTION     VARCHAR2(4000 BYTE),
  REGAC_CULTUREDESCRIPTION      VARCHAR2(4000 BYTE),
  REGDT_RCDLABNAME              VARCHAR2(4000 BYTE),
  REGDT_RCDLABNUMBER            VARCHAR2(4000 BYTE),
  REGSV_SITEVISITTYPE           VARCHAR2(4000 BYTE),
  REGSV_REMARKS                 VARCHAR2(4000 BYTE),
  REGSV_SITEVISITDATE           VARCHAR2(4000 BYTE),
  REGSV_DESCRIPTION             VARCHAR2(4000 BYTE),
  REGSV_AFFILIATION             VARCHAR2(4000 BYTE),
  REGSV_PERMIT                  VARCHAR2(4000 BYTE),
  REGSV_PERMITTYPE              VARCHAR2(4000 BYTE),
  REGSV_ISSUINGAGENCY           VARCHAR2(4000 BYTE),
  REGSV_PERMITTED               VARCHAR2(4000 BYTE),
  REGSV_PERMITHOLDER            VARCHAR2(4000 BYTE),
  REGSR_TITLE                   VARCHAR2(4000 BYTE),
  REGSR_REFDATE                 VARCHAR2(4000 BYTE),
  REGSR_AUTHORS                 VARCHAR2(4000 BYTE),
  REGSR_COMMENTS                VARCHAR2(4000 BYTE),
  REGSI_TYPE                    VARCHAR2(4000 BYTE),
  REGSI_REPOSITORY              VARCHAR2(4000 BYTE),
  REGSI_PHOTOGRAPHER            VARCHAR2(4000 BYTE),
  REGSI_IMAGEDATE               VARCHAR2(4000 BYTE),
  REGSI_DESCRIPTION             VARCHAR2(4000 BYTE),
  REGSI_TITLE                   VARCHAR2(4000 BYTE),
  REGRM_REMDATE                 VARCHAR2(4000 BYTE),
  REGRM_REMARKS                 VARCHAR2(4000 BYTE),
  REGRD_TYPE                    VARCHAR2(4000 BYTE),
  REGRD_DESCRIPTION             VARCHAR2(4000 BYTE),
  REGRD_FILENAME                VARCHAR2(4000 BYTE),
  REGDH_HISTDATE                VARCHAR2(4000 BYTE),
  REGDH_DECISION                VARCHAR2(4000 BYTE),
  REGDH_CRITERIA                VARCHAR2(4000 BYTE),
  REGDH_PERSON                  VARCHAR2(4000 BYTE),
  REGDH_DESCRIPTION             VARCHAR2(4000 BYTE),
  REGDH_RECOMENDEDBY            VARCHAR2(4000 BYTE),
  REGDH_RECOMENDEDDATE          VARCHAR2(4000 BYTE),
  REGPID_PID1                   VARCHAR2(4000 BYTE),
  REGPID_PID2                   VARCHAR2(4000 BYTE),
  REGPID_PID3                   VARCHAR2(4000 BYTE),
  REGPID_PID4                   VARCHAR2(4000 BYTE),
  REGPIN_PIN1                   VARCHAR2(4000 BYTE),
  REGPIN_PIN2                   VARCHAR2(4000 BYTE),
  REGPIN_PIN3                   VARCHAR2(4000 BYTE),
  REGPIN_PIN4                   VARCHAR2(4000 BYTE)

**Comment by bferguso** [comment]
Note that the column names in the description are BCGW column names not the column names in the view exposed to Data BC for extract (`V_HISTORIC_ENVIRO_ONEROW_SITE`). The column names in the view are:
OBJECTID
DOCUMENTKEY
BORDENNUMBER
ISHISTORICSITE
REGISTRATIONSTATUS
COMMON_NAME
OTHER_NAME
PARCELID
STREETNUMBER
STREET_NAME
CITY
PROVINCE
ADDRESS_HERITAGEEXPORTTOFED
GOVERNMENT_NAME
GOVERNMENTLEVEL
PROTECTIONTYPE
STARTDATE
EXPORT_TO_CRHP
DATE_FROMDATE
DATE_FROMQUALIFIER
DATE_HISTDATETYPE
STMTOFSIGN_DESCANDSOSTYPE
IS_ACCEPTED_BY_FEDS
ARCHITECT_NAME
BUILDER_NAME
CURRENT_FUNCTION
HISTORIC_FUNCTION
DIMENSIONS_AREA
GISLATITUDE
GISLONGITUDE
UTMZONE
UTMNORTHING
UTMEASTING
MAPSHEET_NUMBER
MAPSHEET_SCALE
TENURERESERVES_JURISDANDDESC
PK
SHAPE
