### ISSUE TITLE
KML opening issue

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#769]
I'm still having an issue opening KMLs in Arches and nothing happening. I tried dragging into Sandbox and Heritage Site RM. DataBC said this file is fine. This file opens in GoogleEarth. 

I downloaded the KML file from here: https://catalogue.data.gov.bc.ca/dataset/recreation-line

**Comment by bferguso** [comment]
If you just clicked on the KML file on that page there are no geometries in it, so the error is accurate. Perhaps by dragging it into Google Maps it uses the link in the KML file to retrieve the actual geometries from the BCGov openmaps WMS. The content of the file is as follows:

```
<?xml version="1.0" encoding="utf-8"?>
    <kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2"
    xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/kml/2.2 ogckml22.xsd">
    <NetworkLink>
      <name>Recreation Line</name>
      <open>1</open>
      <LookAt>
        <longitude>-125.790485103603</longitude>
        <latitude>54.53529082074053</latitude>
        <altitude>0</altitude>
        <heading>-0.5347266315948855</heading>
        <tilt>0</tilt>
        <range>1826047.023906531</range>
        <altitudeMode>relativeToGround</altitudeMode>
        <gx:altitudeMode>relativeToSeaFloor</gx:altitudeMode>
      </LookAt>
      <refreshVisibility>1</refreshVisibility>
      <flyToView>1</flyToView>
      <Link>
        <href>https://openmaps.gov.bc.ca/kml/geo/layers/WHSE_FOREST_TENURE.FTEN_RECREATION_LINES_SVW.kml</href>
      </Link>
    </NetworkLink>
    </kml>
```

The actual geometries can be downloaded with the "Download" link but KML isn't one of the options:
<img width="415" alt="image" src="https://github.com/bcgov/BCHeritage/assets/6750642/791f18fe-3614-4f92-a03b-a80f9aa214a5">

**Comment by emjohnst** [comment]
@bferguso where did that second screenshot come from? I can try to do a geoJSON file - we don't actually have an example of this file type yet to try in Arches for test

**Comment by emjohnst** [comment]
Hi @bferguso , I'm running into an issue again using data from the BCGW.  I'm now trying to download [this layer](https://catalogue.data.gov.bc.ca/dataset/bc-parks-ecological-reserves-and-protected-areas) to add to the Sandbox resource model - trying to answer an inquiry we received of how many sites are in Provincial parks - its a map overlay but I can't filter by it. I tried downloading the KML file, but as you said its a link and does not have geometry, nothing happened when I dragged it into Sandbox. I downloaded the GeoJSON file and it uploaded to Arches test after some time but it won't save - maybe too big?

**Comment by bferguso** [comment]
@emjohnst  - I believe that layer is available to you as the "Parks - Provincial" overlay. I think generally trying to open large geometries that span the entire province like the one above will be too large.

**Comment by emjohnst** [comment]
@bferguso is there a way I can search by that entire map overlay? Is this what "search by map extent" is for? it's not currently working for me if that's its function.

**Comment by bferguso** [comment]
Map Extent searches by the portion of the map that currently visible on your screen. Overlays need to be individually configured to be used as a source for a geometric search. There's currently no way to search by all the features in that layer - it would be massive as there are thousands of geometries many with hundreds of points each.
