### ISSUE TITLE
Maps in Test Issues

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#772]
Government Resource Model - Map box won't load its just blank

Heritage Site Resource Model - Cadastral maps won't load

**Comment by bferguso** [comment]
@emjohnst - Can you please check this again? It seems to be working for me. Note that you need to be zoomed in sufficiently to see the Cadastral Parcelmap overlay (I'm seeing 500m on the scale).

**Comment by KatieMcEvoy** [comment]
Both seem to be functioning now.
