### ISSUE TITLE
Date field format change - Legislative Act Rm

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#780]
- [ ] change Start and End Date in Leg Act Rm to year-month-day type.

**Comment by bferguso** [comment]
I'm seeing this in TEST. Are you seeing something different?:
<img width="403" alt="image" src="https://github.com/bcgov/BCHeritage/assets/6750642/5d70d3f3-c3f5-40e0-b870-ddde9b0c2563">

**Comment by emjohnst** [comment]
@bferguso I'm seeing it the correct way now. Closing ticket.
