### ISSUE TITLE
Province Does Not Display on Report View

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#785]
Wondering if this is intentional or not, but the province does not display on report view. See attached image.

- [ ] Display province on report view<img width="1798" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmZvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--290a9aa6d43af4154103c84e0a735e5b795ce358/ProvinceError%20Report%20View.JPG" alt="ProvinceError Report View.JPG" />

**Comment by bferguso** [comment]
This is caused by a mis-match of validated address province ('BC') and lookup value ('British Columbia').
