### ISSUE TITLE
Error when downloading Shapefiles

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#787]
Got the attached error message when unzipping downloading shapefile:
"Either no instances were identified for export or no resources have exportable geometry nodes                Please confirm that the models of instances you would like to export have geometry nodes and that                those nodes are set as exportable"
This happens for multiple sites (Emily Carr House, Nanaimo Court House, etc.)

- [ ] Resolve ability to download shapefiles

**Comment by bferguso** [comment]
@emjohnst - I think you need to show me what you're doing. I just created a shapefile without issue..

**Comment by emjohnst** [comment]
@bferguso Hi Brett it's working today now, we just tested it. It was not working for Katie or I yesterday and we tried several different sites. Very weird. I'll close this issue.
