### ISSUE TITLE
Export Validated Addres data

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#793]
- [x] Export validated address data for Emerald and Katie to review

**Comment by bferguso** [comment]
Need to discus strategy to correct / ignore corrections within spreadsheet before starting to edit. Trying to track down new Legal Address information for validation as WFS is no longer available. (Sent email 23 Jan)

**Comment by bferguso** [comment]
Decided to leave use the legal descriptions that were extracted in mid-october as there wouldn't be a huge advantage to reload. Received a reply from the data custodians saying that there is a path to download this data and there is also an authenticated service we can use for WMS if we want to generate new legal descriptions based on a PID or PIN.
