### ISSUE TITLE
Edit Address Data in Arches

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#810]
Post mvp:
Fix address data entry for:

- [ ] DhRr-64 - One row had a corrected street address (17610 BC HARBOURS BD-RR) and one didn't. This is causing 2 records. Fix 17610 BC HARBOURS BD-RR to 17610 BC Harbours Board Rwy

- [x] DcRu-1125 - has 2 addresses  516 Trutch St and 517 Trutch St

- [x] Site with PID 011752033 was the only legal address that was not able to be validated - this must have been entered/updated since the original extract in October. May want to include this cleanup in Arches after MVP. - Not sure what this site is, got no results seaching PID in advanced search Em 2024-03-27

**Comment by emjohnst** [comment]
@bferguso experiencing an issue saving an edit to an address for DhRr-64 (first task). Error message attached.



![Image](https://github.com/bcgov/BCHeritage/assets/139929541/3a98f09e-a49c-4f1d-937a-c3f8ffbe398f)

**Comment by KatieMcEvoy** [comment]
Task 3: This is a tree (DhRs-1268) that was originally incorrectly recorded to be on PID 011752033. It was fixed and there is no longer a site on that property.

@bferguso I'm also getting the same error message for task 1.

**Comment by emjohnst** [comment]
Closing ticket because addresses  were cleaned up programmatically for this record.
