### ISSUE TITLE
CSV Report 414 Request Error

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#816]
MVP Priority: High

Description
Cannot export csv report results

Steps to reproduce
1. Search by Sandbox resource "Translink Exchanges"
2. Go to Map Search, filter, search by feature
3. Buffer feature to 400m
4. Set geometry results to "union"
5. Expected search results of map filter should be 89
6. Click export search results, make sure csv is selected
7. Click Download

Actual Results
- Error message - 414 Request - URI Too Long (image attached)

Expected Results
- CSV downloads

![CSV report error](https://github.com/bcgov/BCHeritage/assets/139929541/4c388f67-3d4c-424a-8aa8-f36e6d809770)

**Comment by bferguso** [comment]
Put force the export to be a POST, and put a layer in front of the searcy.py -> export_results to put all request POST parameters into the GET

**Comment by emjohnst** [comment]
Tested and resolved
