### ISSUE TITLE
Reorder general remarks

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#826]
MVP Priority: Medium

- [ ] Reorder general remarks

General remarks appear in random order. Is it possible to make them appear in order of date? I'm not sure how what is the best order. In "Edit" the new ticket is added to the bottom. But in "Record View" the new ticket is added to the top. 

Example: DiRf-2 

Actual Results
2003 Remark
2023 Remark
2017 Remark
2018 Remark
2003 Remark

Expected Results
2003
2003
2017
2018
2023

**Comment by bferguso** [comment]
There is no provision for this in Arches Core. We'll need to figure out how to do this.

**Comment by emjohnst** [comment]
I think this can be done through drag and drop in the tree to reorder.
