### ISSUE TITLE
Improved / Enhanced Excel output for BCGov users

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#837]

**Comment by bferguso** [comment]
@emjohnst  - I think this is the same as #947. If so, this issue can be closed and moved to Done.

**Comment by emjohnst** [comment]
@bferguso No #947  is a csv output for public users, internal users still need to be able to create a csv with any field and we would like to improve it for internal users in Post MVP 2, I will mark this ticket under that milestone now.
