### ISSUE TITLE
Data Cleaning in Prod

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#839]
Need to perform in-place data validation and cleaning. Likely to be a combination of semi-automated and manual:
- [x] URLs
- [x] Reconcile CRHP and BCRHP sites

**Comment by emjohnst** [comment]
Removing Urls from this issue and creating new one for it as it should be address before public site is launched.

**Comment by bferguso** [comment]
Estimate is for contractor effort only for planning purposes.
@emjohnst - Is the URL validation and cleaning done? Are is there anything else not in the above list that needs to be completed? Do we still want to do the CRHP reconciliation prior to the release of the public website?

**Comment by emjohnst** [comment]
@bferguso we have done our own analysis of eligible CRHP sites and have identified the backlog. I don't think there is anything further to do on your own so I will mark this ticket as complete.
