### ISSUE TITLE
Filter by Feature Not Working

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#853]
- [ ] Muncipal Boundaries

**Comment by bferguso** [comment]
@emjohnst  - Please provide more details. It's working for me. Filter by feature is configured on an overlay-by-overlay basis so if there are some that you are expecting to filter by but currently can't please list which ones should be added.

**Comment by KatieMcEvoy** [comment]
When filtering by feature a "Request Failed" error message appears.
Municipal Boundaries

Can't select:
crown tenures
Indigenous Reserve Boundaries
Natural Resource Regions
Municipal Parks
National Parks
Provincial Parks
Regional District Boundaries

**Comment by bferguso** [comment]
This issue was caused by increasing the max URL length to a value that is too large in an attempt to fix complex Advanced Search functions. Will reduce length to a smaller value and we will have to create a fix for the Advanced Search issue.
