### ISSUE TITLE
Update Field Character Limits

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#857]
As per discussions with DataBC, update field character limits to be consistent with the data that gets sent to them.

- [x] locality to 50
- [ ] construction year qualifier 10
- [x] document location 350

Emerald to update help text post mvp with character limits:
- [ ] Location description to 2500
- [ ] SoS Descripotion 4000
- [ ] SoS Heritage Value 4000
- [ ] Sos Character defining elements 4000

**Comment by bferguso** [comment]
There is no ability to put a limit on the rich text fields. If it is the case that Data BC truncates we can use that for now. We can potentially create a widget to limit rich text fields, applying the same conversion that will happen on the Data BC HTML->Plain text extract. Maybe for now we should add instructions / note to the field stating the limit.

The construction year qualifier is is simply a boolean value in the database which creates the text "Circa" in the view. No need to limit the field.

**Comment by emjohnst** [comment]
Agreed, I will update help text info post mvp. When you are done with this ticket can you assign it to me?
