### ISSUE TITLE
Missing Sites

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#862]
Please add missing sites to Arches:

- [ ] HkTu-6
- [ ] HaRc-53
- [ ] DjRi-141
- [ ] EaQv-39
- [ ] EaQu-90
- [ ] EaQv-40

**Comment by bferguso** [comment]
@emjohnst  - These look like they were all created on Feb 5th, after we did the final pull. Are there digital assets associated with these sites?

**Comment by emjohnst** [comment]
@bferguso confirmed non of them have digital assets
