### ISSUE TITLE
Follow up with tasks from CRHP meeting

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#87]
- [ ] BF to follow up with requests below
- [ ] NA to provide valid vocabularies - CSV or Excel
- [ ] BF to provide script to upload vocabularies - wait to hear back from NA when it will be useful
- [x] NA - To set up CRHP for BF, provide links to app and "Full export" reports for reconcile

**Comment by emjohnst** [comment]
Closing as this ticket it outdated
