### ISSUE TITLE
Edit Mandatory Fields in Site Submission Resource Model

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#870]
- [x] Remove Submission Type mandatory requirement
- [x] remove Information Provided as mandatory requirement

**Comment by bferguso** [comment]
@emjohnst  - This leaves nothing on that card that is mandatory. This may cause issues if cards are created with no data at all. I'd suggest we leave at least one value a mandatory on this card.

**Comment by emjohnst** [comment]
Can you make requested operation mandatory
