### ISSUE TITLE
Missing Address/Location Description

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#880]
Post mvp task - review 96 records with missing address and location info in Arches, add any missing info from HRIA

Spreadsheet of sites can be found at Arches > Data Clean Up> Heritage Sites with Missing Address and Location Description folder on LAN

**Comment by emjohnst** [comment]
@KatieMcEvoy could you start the work on this ticket and let me know if you have any questions?

**Comment by emjohnst** [comment]
@KatieMcEvoy just wondering if you had a chance to start this, and if not I can help support, please let me know

**Comment by KatieMcEvoy** [comment]
@emjohnst sorry no I haven't. This one slipped by me. If it's time sensitive I might need some support.

**Comment by KatieMcEvoy** [comment]
All of these did not have addresses in HRIA.
If there was a street address in the description in HRIA I entered that into the BC Property Address fields in Arches.
Most still do not have addresses but many have a location description in arches.
@emjohnst let me know if this can close or if there are next steps.
