### ISSUE TITLE
Missing Location info

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#881]
Some sites are missing information from the location table in HRIA. 

Example: DhRs-1402 is missing an address in Arches but in HRIA there is data

HRIA data in "Location______" field: "510 West Hastings Street, Vancouver, BC". 
Record is missing the typical address data in HRIA 
However, all sites with data in the HRIA "Location______" field should have come over into the Arches "Location description" field.

**Comment by bferguso** [comment]
There was an assumption that there would always be a civic address. Made the join from the HRIA db outer join. Address row count before was 21079, after 21136.
Still need to refresh DEV instance to confirm results.
