### ISSUE TITLE
Hide Edit buttons

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#886]
If record is not editable by the user:
- [x] Don't show link on the site name in the search card
- [x] Don't show report link in the map popup
- [x] Put auth in front of resource report so only users that can edit the resource can access it.

**Comment by bferguso** [comment]
Have also hidden full record view from users that don't have edit rights on the record. When a site is not editable, th site name in the search result doesn't have a link to the report.

**Comment by bferguso** [comment]
Requiring "Resource Editor" group to view resource report page. May need to make this more fine grained when we open up to Local Governments.

**Comment by emjohnst** [comment]
Done in test
