### ISSUE TITLE
Define Details Page content and layout

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#887]
Details Page layout - See attached PDF for content transformation and layout

[Public Site Details Page Mock-up.pdf](https://github.com/bcgov/BCHeritage/files/14924514/Public.Site.Details.Page.Mock-up.pdf)

Public Details Page Edits:

- [x] Is it possible to add a light grey banner behind the image widget?
- [x] Remove second date appearing in top banner
- [x] Remove "Copyright" as Label and include it as Text beside copyright owner e.g. Copyright City of Victoria
- [x] Official Recognition Details - Display as list not as columns, this is causing issues when there rae 4+ recognitions
- [x] Fix Recognition Type as suggested in mock-up (above): [Leg Act Authority, Leg Act Recognition Type (for example:
Municipal, Heritage Designation)]
- [x] #959
- [x] Fix date alignment for Construction dates, example record DcRt-179
- [x] Fix chronology section for suggested format on mock-up (above)
- [x] #961

See #967 for details page for internal users

[Details Card Help Text.docx](https://github.com/bcgov/BCHeritage/files/15440701/Details.Card.Help.Text.docx)

**Comment by rajpersram** [comment]
[Please refer to the original Figma layout suggestions](https://www.figma.com/file/nflhEcVKXeX3q7hmtXkCAT/ARCHES-Fossils-and-Historic-Places?type=design&node-id=30-785&mode=design&t=KYsEqNFgOirJJ4qZ-4) as a starting point for discussion. Were the redesigns implemented? Let me know if there are access issues. You'll need a free Figma account to view the pages, and I can add your email specifically if you still can't access them. I can chat on Wed, Apr 10.

**Comment by emjohnst** [comment]
@bferguso updated ticket details with pdf and comments of content and layout

**Comment by bferguso** [comment]
As per today's meeting - remove province and postal code from address section.
To use same template with less information for internal view. @emjohnst to provide attribute list for internal users.

**Comment by emjohnst** [comment]
@bferguso Note, uploading images to Carr House Record DcRu-235 created broken image link for image widget on detail page. Do you want me to create separate ticket for that?

**Comment by emjohnst** [comment]
@bferguso Question - is there a limit to the number of photos we can include in the widget?

**Comment by emjohnst** [comment]
@bferguso Updated ticket with edits to page

**Comment by JessicaInTime** [comment]
@emjohnst would you be able to clarify more about the hover details for Recognition Type? From the edit and add resources, is it referring the details be from the help icon popup (example screenshot) or is there somewhere else the details come from?
<img width="512" alt="Screenshot 2024-05-21 at 8 55 57 AM" src="https://github.com/bcgov/BCHeritage/assets/5874122/1fe460ef-7865-4dfd-b0d7-500d1fc110cd">

**Comment by emjohnst** [comment]
@jrods Brett and I discussed the possibility of making the recognition type text clickable to be able to see a pop-up from the text, rather than from the help icon popup. I think it would be more obvious to people to click on the text for a definition rather than looking for it in the help icon (If this isn't possible, then we can look at adding it in the help icon).
Brett suggested the pop-up text could be drawn from the Reference Data Manager > Thesauri > BC Recognition Type > Notes field. None of these  thesauri values have notes in them yet.

**Comment by emjohnst** [comment]
@jrods @bferguso I've edited the ticket to include include a Help pop-up on the details page (this is based on Jessica's suggestion, but would still like a link/hover option over recognition type on the details page.) I've attached a document with the suggested Help text, originally this was going to go into a public user manual but I think the information would be more useful within the system itself.

**Comment by emjohnst** [comment]
@bferguso @jrods multiple SoS's will be displayed on the details page, correct?

**Comment by JessicaInTime** [comment]
@jrods (note for self) look at why the copyright changes are not in deployment

**Comment by emjohnst** [comment]
Done in test
