### ISSUE TITLE
Update Landing Text (review layout, content, video tutorial, manual, better images, carousel images, update screen grabs)

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#890]
Update Landing Page Text:

- [x] What is the BC Register of Historic Places? Update text below to following:
The BC Register of Historic Places (BCRHP) is an official list of historic places that have been formally recognized by the province or by a local government. The BCRHP supports land use decisions, heritage conservation projects, and public awareness initiatives. There are over 5,000 registered sites representing the diversity of historic places across the province. 
The BCRHP is a subset of the Provincial Heritage Register of historic and archaeological sites that exists as a statutory requirement of the [Heritage Conservation Act](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96187_01). Archaeological and pre-1846 sites are not included on the BCRHP. Contact the [Archaeology Branch](https://www2.gov.bc.ca/gov/content/industry/natural-resource-use/archaeology) for information about archaeology in BC.

- [x] Local Government Historic Places (Remove "on the BC Register" in header) Update text below to following:
Under the [Local Government Act](https://www.bclaws.gov.bc.ca/civix/document/id/consol21/consol21/96323_31) and the [Vancouver Charter](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/vanch_29), local governments can formally protect and recognize places with local or regional heritage significance, primarily through municipal designation and community heritage register listings. Local governments notify the province of recognized municipal historic places so they can be added to the BC Register of Historic Places.

- [x] Provincial Historic Places  (Remove "on the BC Register" in header) Update text below to following:
Under the [Heritage Conservation Act](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96187_01) , the province protects historic places with provincial-level heritage significance in several ways, primarily through designation as provincial heritage property (Crown land) or provincial heritage sites (non-Crown land).
In British Columbia, there are over 50 provincial heritage designations for historic places under the Heritage Conservation Act.

- [x] Federal Government Historic Places (Remove "on the BC Register")
The federal government has responsibility for national-level formal recognition. National Historic Sites and other federal recognitions are not officially part of the BC Register of Historic Places but are noted in the system.

- [x] Add Contact us section
Header: Contact the Heritage Branch
For more information about historic places or to report any issues, please contact the [Heritage Branch](https://www2.gov.bc.ca/gov/content/governments/celebrating-british-columbia/historic-places)

**Comment by emjohnst** [comment]
@bferguso We can only update screengrabs and video tutorial once the public site version is functioning so that they are reflective of the site and how it will look. Question: can a video tutorial be uploaded to landing page and if so, what file types are accepted? Or would it be preferable to have a PDF "manual" that links to video instructions on youtube or elsewhere?

**Comment by emjohnst** [comment]
@bferguso can we use multiple images for the landing page like Jersey Historic environment? https://her.jerseyheritage.org/ If so, can you provide an estimate of time/cost for that so we can determine if that's a priority for this public site release or a future one?

**Comment by bferguso** [comment]
@emjohnst - Yes, we can use multiple images. Can you please create a new issue so we can track the task? Ideally we'll need to track down a framwork for this - perhaps it could tie into the Details tab carousel.

**Comment by emjohnst** [comment]
@bferguso created ticked #930 for landing page photos.

**Comment by emjohnst** [comment]
Done in test
