### ISSUE TITLE
Create list of saved searches (HB, such as Section 18, Provincial Historic Sites, Trail, National Historic Sites, etc.)

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#891]

**Comment by emjohnst** [comment]
See ticket #933 for bug issue and saved searches questions

**Comment by bferguso** [comment]
@emjohnst - Do you need our help for this or is this something you'll be able to do without us?

**Comment by emjohnst** [comment]
@bferguso I can do this once the public site is in prod

**Comment by emjohnst** [comment]
Closing ticket as this is HB task in next release
