### ISSUE TITLE
Searching: Limit to Heritage Site Resources

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#893]
Let's also include searching Governments

**Comment by emjohnst** [comment]
@bferguso is this a duplicate ticket of #694?

**Comment by bferguso** [comment]
@emerald - do we want people to be able to see the Legislative Acts resources as well?

**Comment by emjohnst** [comment]
@bferguso yes they can see that

**Comment by emjohnst** [comment]
Done in test
