### ISSUE TITLE
Missing Data - Heritage Function Type

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#896]
Missing Heritage Function Category/Type 

Example: DcRu-435 has "current" and "historic" function period, but no function type in Arches. In HRIA there is a function type and period for this record: Government > Office or office building. 

There are 36 sites with with Function Type "no value" and Function Period "has value". 
Add missing options:

- [x] Government > Office or Office Building
- [x] Government > Treaty-Making Site
- [x] Food Supply > Rural District or Area
- [x] Industry > Armament Manufacturing Facility
- [x] Industry > Chemical Products Manufacturing Facility
- [x] Change Leisure > Auditorium, Cinema or Night Club to Leisure > Auditorium, Cinema or Nightclub
- [x] Transport-Air > Aircraft
- [x] Undetermined (Archaeological Site) > Exposed Site
- [x] Undetermined (Archaeological Site) > Underwater Site

**Comment by bferguso** [comment]
Government > Office or office building missing from the `BC Heritage Function` LOV.

**Comment by bferguso** [comment]
@emjohnst  - The current HRIA data is `Auditorium, Cinema or Night Club`. We'll need to translate those values if you want to change the LOV.
