### ISSUE TITLE
Create migrations to modify existing data for new app context

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#909]
The application URL is stored in the database in various places (map sources, map layers (legend?), file names, etc. These are currently `/int/bcrhp` and will become `/bcrhp` when moving to OIDC authentication. Need to develop a migration that makes the changes in the database.

Issue #910 must be completed prior to this

Areas to be addressed:
- [x] map_sources and associated JSON files
- [x] map_layers legend column
- [x] cards_x_nodes_x_widgets - Concepts & associated resource model JSON files
- [x] concepts - legacyoid - should change the host to the PROD host too
- [x] tiledata - file URLs
- [x] nodes config column - relationship search string
- [x] values value column
- [x] published_graphs serialized_graph column - nodes search string
- [x] v_historic_site site_url column
- [ ] edit_log (unclear if this is necessary)

**Comment by JessicaInTime** [comment]
Updated the description, there were additional tables that needed to also be changes.

@bferguso @emjohnst There is also the question of if the instances in the edit_log tables should also be updated. But I'm not familiar enough with how the edit log view is intended to work both from a technical side and user perspective.

**Comment by emjohnst** [comment]
@jrods Yes we do rely on the edit log for the records, there is a history of data clean up we've preserved in the edit history for reference and will continue to used the edit history log for referenced of changes to the record over time. Thanks!

**Comment by emjohnst** [comment]
@bferguso was the edit log migration developed?

**Comment by bferguso** [comment]
We are still able to see the edit logs of the changes made. The /int/ prefix is only visible in the edit logs table for the system settings node (for saved searches), and the images and documents nodes (for file URLs). As such, I don't believe that we need (or maybe even should) update the values there. If this premise proves to be invalid, we can update those values in a subsequent release.

**Comment by bferguso** [comment]
@emjohnst - I believe this can be marked as done.
