### ISSUE TITLE
Update CI/CD for Prod patches

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#917]
Current CI/CD process was developed to rebuild entire site with data refreshes. Need to confirm whether we need to modify the process to patch the existing application. Specifically we need to look at how:
- [x] to patch the source code c/w migrations
- [x] perform data fixes
- [x] refresh lower environments from higher so that migrations can be rolled back / tested
- [x] Push resource model changes through environments (make repeatable) so they don't need to be done directly in PROD?
- [x] Move variables from ansible replacement to .env file

**Comment by bferguso** [comment]
Spoke with arches core team, and this is what I believe we should do:
- Perform full software updates (file system only) using Ansible
- Data fixes (including overlay config, controlled concept and collection changes, etc), view updates to be done via migrations. For Dev, the database needs to be seeded with a copy of DLVR or Dev prior to running migrations as the migrations require the resources models as a prerequisite. All migrations must have a reverse migration so they can be tested and reversed in all environments.
- There is no good way to perform repeatable resource model changes until v8.x which will have future graphs. Non structural resource model edits (labels changes, help text additions, etc) can be done in-place, but we will need to look at a process to ensure any manual interventions are done consistently and the changes are capture in the resource model JSON files. 
- Currently the only way to make structural resource model changes is to delete all resource data, delete and recreate the resource model, and re-insert the resource data.
- Refreshing lower environments from higher can be done by database export/import and elasticsearch reindex

**Comment by emjohnst** [comment]
Done in test
