### ISSUE TITLE
Broken Image Links

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#920]
Some file types have been added to the images section and appear as broken links. 

- [x] Search broken image file links or all non-jpg files for images. Example record: DgRp-14. 
- [x] Emerald to correct DgRp-14 record when search complete.

- [x] DcRt-244  
- [x] DcRu-1057  
- [x] DcRu-1432  
- [x] DcRu-505  
- [x] DcRu-693  
- [x] DcRu-986  
- [x] DdRu-127  
- [x] DdRu-153  2011-216 ElRu-1 detailed site map.pdf
- [x] DdRu-153  HRIA assoc doc test 4.pdf
- [x] DfRv-136  Peninsula RWs 1895.pdf
- [x] DfSi-56  DfSi-56 Pre-2021 Site record(1).pdf
- [x] DfSi-75  DfSi-75 Pre-2021 Site record(1).pdf
- [x] DfSi-76  DfSi-76 Pre-2021 Site record(1).pdf
- [x] DgQk-49  
- [x] DgQk-49  
- [x] DgQk-70  
- [x] DgQq-30  
- [x] DgRo-9  DgRo-9 Pre-2021 Site record.pdf
- [x] DgRp-12  DgRp-12 Pre-2021 Site record.pdf
- [x] DgRp-13  DgRp-13 Pre-2021 Site record.pdf
- [x] DgRp-14  DgRp-14 Pre-2021 Site record.pdf
- [x] DgRp-3  DgRp-3 Pre-2021 Site record.pdf
- [x] DgRp-37  DgRp-37 Pre-2021 Site record.pdf
- [x] DgRp-44  
- [x] DgRp-5  DgRp-5 Pre-2021 Site record.pdf
- [x] DgRp-6  DgRp-6 Pre-2021 Site record.pdf
- [x] DgRp-7  DgRp-7 Pre-2021 Site record.pdf
- [x] DgRp-8  DgRp-8 Pre-2021 Site record.pdf
- [x] DgRp-9  DgRp-9 Pre-2021 Site record.pdf
- [x] DgRq-10  DgRq-10 Pre-2021 Site record.pdf
- [x] DgRq-11  DgRq-11 Pre-2021 Site record.pdf
- [x] DgRq-12  DgRq-12 Pre-2021 Site record.pdf
- [x] DgRq-13  DgRq-13 Pre-2021 Site record.pdf
- [x] DgRq-14  DgRq-14 Pre-2021 Site record.pdf
- [x] DgRq-15  DgRq-15 Pre-2021 Site record.pdf
- [x] DgRq-16  DgRq-16 Pre-2021 Site record.pdf
- [x] DgRq-17  DgRq-17 Pre-2021 Site record.pdf
- [x] DgRq-20  DgRq-20 Pre-2021 Site record.pdf
- [x] DgRq-21  DgRq-21 Pre-2021 Site record.pdf
- [x] DgRq-23  DgRq-23 Pre-2021 Site record.pdf
- [x] DgRq-24  DgRq-24 Pre-2021 Site record.pdf
- [x] DgRq-25  DgRq-25 Pre-2021 Site record.pdf
- [x] DgRq-26  DgRq-26 Pre-2021 Site record.pdf
- [x] DgRq-27  DgRq-27 Pre-2021 Site record.pdf
- [x] DgRq-28  
- [x] DgRq-28  DgRq-28 Pre-2021 Site record.pdf
- [x] DgRq-29  DgRq-29 Pre-2021 Site record.pdf
- [x] DgRq-30  DgRq-30 Pre-2021 Site record.pdf
- [x] DgRq-32  DgRq-32 Pre-2021 Site record.pdf
- [x] DgRq-33  DgRq-33 Pre-2021 Site record.pdf
- [x] DgRq-39  DgRq-39 Pre-2021 Site record.pdf
- [x] DgRq-9  DgRq-9 Pre-2021 Site record.pdf
- [x] DgRs-23  DgRs-23 Pre-2021 Site record.pdf
- [x] DgRv-45  
- [x] DhQd-8  DhQd-8 Pre-2021 Site record(1).pdf
- [x] DhQh-1  DhQh-1 Pre-2021 Site record(1).pdf
- [x] DhQh-2  DhQh-2 Pre-2021 Site record(1).pdf
- [x] DhQh-4  DhQh-4 Pre-2021 Site record(1).pdf
- [x] DhQh-5  DhQh-5 Pre-2021 Site record(1).pdf
- [x] DhQi-1  DhQi-1 Pre-2021 Site record(1).pdf
- [x] DhQi-2  DhQi-2 Pre-2021 Site record(1).pdf
- [x] DhQi-3  DhQi-3 Pre-2021 Site record(1).pdf
- [x] DhQj-20  DhQj-20 Pre-2021 Site record(1).pdf
- [x] DhQj-29  DhQj-29 Pre-2021 Site record(1).pdf
- [x] DhQj-34  DhQj-34 Pre-2021 Site record(1).pdf
- [x] DhQv-25  DhQv-25 Pre-2021 Site record(1).pdf
- [x] DhQv-70  DhQv-70 Pre-2021 Site record(1).pdf
- [x] DhQv-85  DhQv-85 Pre-2021 Site record(1).pdf
- [x] DhQw-19  DhQw-19 Pre-2021 Site record(1).pdf
- [x] DhQw-30  DhQw-30 Pre-2021 Site record(1).pdf
- [x] DhQw-31  DhQw-31 Pre-2021 Site record(1).pdf
- [x] DhQw-32  DhQw-32 Pre-2021 Site record(1).pdf
- [x] DhQw-33  DhQw-33 Pre-2021 Site record(1).pdf
- [x] DhQw-34  DhQw-34 Pre-2021 Site record(1).pdf
- [x] DhQx-16  DhQx-16 Pre-2021 Site record(1).pdf
- [x] DhQx-28  DhQx-28 Pre-2021 Site record(1).pdf
- [x] DhRa-10  DhRa-10 Pre-2021 Site record(1).pdf
- [x] DhRa-8  DhRa-8 Pre-2021 Site record(1).pdf
- [x] DhRd-1  DhRd-1 Pre-2021 Site record(1).pdf
- [x] DhRd-5  DhRd-5 Pre-2021 Site record(1).pdf
- [x] DhRd-6  DhRd-6 Pre-2021 Site record(1).pdf
- [x] DhRd-7  DhRd-7 Pre-2021 Site record(1).pdf
- [x] DhRe-1  DhRe-1 Pre-2021 Site record(1).pdf
- [x] DhRe-2  DhRe-2 Pre-2021 Site record(1).pdf
- [x] DhRf-1  DhRf-1 Pre-2021 Site record(1).pdf
- [x] DhRf-2  DhRf-2 Pre-2021 Site record(1).pdf
- [x] DhRg-1  DhRg-1 Pre-2021 Site record(1).pdf
- [x] DhRg-2  DhRg-2 Pre-2021 Site record(1).pdf
- [x] DhRg-3  DhRg-3 Pre-2021 Site record(1).pdf
- [x] DhRg-4  DhRg-4 Pre-2021 Site record(1).pdf
- [x] DhRg-5  DhRg-5 Pre-2021 Site record(1).pdf
- [x] DhRg-6  DhRg-6 Pre-2021 Site record(1).pdf
- [x] DhRg-7  DhRg-7 Pre-2021 Site record(1).pdf
- [x] DhRg-8  DhRg-8 Pre-2021 Site record(1).pdf
- [x] DhRg-9  DhRg-9 Pre-2021 Site record(1).pdf
- [x] DhRh-2  DhRh-2 Pre-2021 Site record(1).pdf
- [x] DhRh-3  DhRh-3 Pre-2021 Site record(1).pdf
- [x] DhRi-2  DhRi-2 Pre-2021 Site record(1).pdf
- [x] DhRl-30  DhRl-30 Pre-2021 Site record(1).pdf
- [x] DhRl-34  DhRl-34 Pre-2021 Site record(1).pdf
- [x] DhRl-35  DhRl-35 Pre-2021 Site record(1).pdf
- [x] DhRl-36  DhRl-36 Pre-2021 Site record(1).pdf
- [x] DhRl-37  DhRl-37 Pre-2021 Site record(1).pdf
- [x] DhRl-38  DhRl-38 Pre-2021 Site record(1).pdf
- [x] DhRr-118  
- [x] DhRr-143  
- [x] DhRr-403  
- [x] DhRr-440  
- [x] DhRr-469  
- [x] DhRr-469  
- [x] DhRr-85  
- [x] DhRs-101  
- [x] DhRs-103  
- [x] DhRs-1300  
- [x] DhRs-167  
- [x] DhRs-167  
- [x] DhRs-167  
- [x] DhRs-168  
- [x] DhRs-216  
- [x] DhRs-41  
- [x] DhRs-41  
- [x] DhRs-449  
- [x] DhRs-450  
- [x] DhRs-455  
- [x] DhRs-464  
- [x] DhRs-464  
- [x] DhRs-492  
- [x] DhRs-860  
- [x] DhRs-860  
- [x] DhRt-73  29 - 3851 W 29th Av - Mural.pdf
- [x] DhRx-134  
- [x] DlQi-33  
- [x] DlQv-71  DlQv-71 1997-0232 Photos.pdf
- [x] EfQr-20  
- [x] EfRr-26  
- [x] EiQd-18  EiQd-18 Pre-2021 Site Record.pdf
- [x] FgRj-1  Barkerville FgRj-1 OIC 553 (2012).pdf
- [x] FgRl-2  
- [x] GaTw-8  GaTw 1-8 Pre-2021 Site record.pdf
- [x] GaTw-8  GaTw-H8 Pre-2021 Site record.pdf
- [x] GbTn-130  GbTn-130 2013 Non-permit Site Images.pdf
- [x] GbTn-68  Fort Barrett 1946 Photo.pdf
- [x] GeSs-4  GeSs- H4 Pre-2021 Site record.pdf
- [x] GeSs-6  GeSs- H6 Pre-2021 Site record.pdf
- [x] GeTb-35  Pacific GTP Yard Plans 1937.pdf
- [x] HaRs-1  HaRS-1 Pre-2021 Site record.pdf
- [x] HbRe-1  Old Fort map 1910.pdf

**Comment by bferguso** [comment]
List sent via email
