### ISSUE TITLE
Update Landing Page Images

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#930]
- [x] Add widget for multiple image carousel. 
- [x] Emerald to email new images for landing page. Send via file transfer 2024-04-11

New Images, in order of appearance on website

1 - Caption "Cole Island at Colwood"

2 - Caption "Barkerville Historic Town and Park"

3 - Caption "McAbee Fossil Beds"

**Comment by emjohnst** [comment]
@bferguso is there any resolution/image size specifications for the landing page? or is that determined by the widget?

**Comment by emjohnst** [comment]
@bferguso sent photos via file transfer

**Comment by bferguso** [comment]
@emjohnst  - Can these images go in the public GitHub repo? And are we removing the Grist Mill one? (I really like that one!) Also - do we need any photo attribution statements for them?

**Comment by emjohnst** [comment]
@bferguso No to the public repository. And yes, removing Grist Mill one. The Photo attributes are the caption statements above - we have copyright/permission to use them for this purpose.

**Comment by emjohnst** [comment]
@bferguso Can we improve the way images are appearing "stretched out"?

**Comment by emjohnst** [comment]
Done in test
