### ISSUE TITLE
Improve public user experience of mobile site

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#931]
Before launching public site, ensure mobile experience is improved.
- [x] #960
- [x] #988
- [x] Address issues (estimate TBD depending on outcome of (1)

Issues currently being experienced:
- [x] Formatting of landing page image
- [x] Unable to click the icon to get to search

**Comment by JessicaInTime** [comment]
I've updated the ticket from a previous discussion we had about the issue with the landing page carousel images #988.

**Comment by emjohnst** [comment]
Other tickets created as spin off issues to this one.
