### ISSUE TITLE
Remove landing page banner

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#932]
- [x] Remove yellow landing page banner "Welcome to the new BC Register of Historic Places System"
- [x] GCPE advice - add more space between BC Gov logo and website title. Attached "protective space guidelines"
- [x] GCPE comment/question - is the logo the standard proportions or is it stretched out? - BF standard proportions. Only constraining one dimension
- [x] Fix issue with table of contents, perhaps remove vertical black bar or fix spacing (photo attached)

![Image](https://github.com/bcgov/BCHeritage/assets/139929541/93b0c669-3605-4efb-b05d-2833408da4cb)
![Image](https://github.com/bcgov/BCHeritage/assets/139929541/867a435b-b3eb-4ebe-9091-4c4b972eb78c)

**Comment by bferguso** [comment]
I believe this was added because it was part of the BCGov standard. Would you please confirm we can do that before we remove it?

**Comment by emjohnst** [comment]
@bferguso I have not found a reference to using a banner like this in the Visual Design Guide of the Web Standards Guide. I'm referring to just the yellow/gold banner and not the logo banner. The yellow/gold banner seems to deviate from the standard web format of BC gov pages. 
![snip](https://github.com/bcgov/BCHeritage/assets/139929541/b4441751-994e-43cc-936a-57f2733a1d27)

**Comment by bferguso** [comment]
@emjohnst - OK I'll remove it. Not sure where this requirement came from as it isn't something I would have done without direction. This was added on May 8th 2023.

**Comment by emjohnst** [comment]
@bferguso added a few more landing page tasks to this ticket

**Comment by emjohnst** [comment]
Done in test
