### ISSUE TITLE
Saved Searches Error

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#933]
When trying to save a "Saved Search" there is an error message.

Question: do saved searches have to be from the public url to be viewable to the public?
Another Question: The field I searched on for the saved search should not be viewable to the public - is that going to pose an issue?

![Image](https://github.com/bcgov/BCHeritage/assets/139929541/8e8285ea-b44c-4cb4-9f65-4a32c4ec6703)

**Comment by bferguso** [comment]
@emjohnst - Can you please send me the information for the search you were trying to create by email (URL, description, image if you're trying to use one)

**Comment by emjohnst** [comment]
@bferguso Here is the link to the search: https://apps.nrs.gov.bc.ca/int/bcrhp/search?paging-filter=1&tiles=true&format=tilecsv&reportlink=false&precision=6&total=56&advanced-search=%5B%7B%22op%22%3A%22and%22%2C%226cc30f6e-0d06-11ed-8804-5254008afee6%22%3A%7B%22op%22%3A%22eq%22%2C%22val%22%3A%22%22%7D%2C%226cc30d5c-0d06-11ed-8804-5254008afee6%22%3A%7B%22op%22%3A%22eq%22%2C%22val%22%3A%22%22%7D%2C%221f28339e-3b93-11ee-b4c5-080027b7463b%22%3A%7B%22op%22%3A%22%22%2C%22val%22%3A%22%22%7D%2C%2250c26f28-3b93-11ee-ac05-080027b7463b%22%3A%7B%22op%22%3A%22%22%2C%22val%22%3A%22%22%7D%2C%226cc30b36-0d06-11ed-8804-5254008afee6%22%3A%7B%22op%22%3A%22~%22%2C%22lang%22%3A%22en%22%2C%22val%22%3A%22%22%7D%2C%226cc30c44-0d06-11ed-8804-5254008afee6%22%3A%7B%22op%22%3A%22~%22%2C%22lang%22%3A%22en%22%2C%22val%22%3A%22japanese%20canadian%20recognition%20project%22%7D%7D%5D

**Comment by emjohnst** [comment]
Description: Japanese Canadian Historic Places
The 56 places received provincial recognition through the Province of British Columbia’s “Japanese Canadian Historic Places Recognition Project”. They were selected by community and sector experts for their importance to the Japanese Canadian community and contributions to the history and development of the province. Together, the sites help tell the story of Japanese Canadians across the province, and give insight into significant moments in BC’s history.

**Comment by emjohnst** [comment]
![Nikkei Memorial Internment Centre NHS](https://github.com/bcgov/BCHeritage/assets/139929541/1d5d797c-1f4c-4a73-8341-21203da2d8e2)

Image attached

**Comment by bferguso** [comment]
This appears to be related to adding the image

**Comment by bferguso** [comment]
This was caused by the fact that system settings graph doesn't have a graph slug. Setting null graph slug to `system_settings` so the images can be saved properly in s3.

**Comment by emjohnst** [comment]
@bferguso I believe this is complete now?
