### ISSUE TITLE
French SoS's

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#934]
We would like to add French SoS statements to several provincial Francophone sites before the launch of the public site.

I tested one site DcRu-1423 in the test environment and everything seems to look okay. Do you know if or how we are supposed to use the languages field? It doesn't seem to work for search and it didn't seem to work for the SoS fields. Are there any other areas we should consider testing before adding the SoS's in prod?

**Comment by KatieMcEvoy** [comment]
Tested DcRu-1423 in PROD
Did not change the language but all characters seem to have worked.
will check in IMap April 19th 2024.

**Comment by KatieMcEvoy** [comment]
Complete. Will close after @emjohnst review.

**Comment by emjohnst** [comment]
Looks good!
