### ISSUE TITLE
Remove Broken Url Links

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#935]
A number of site records contain broken links.

- [x] Brett to determine how many broken url links there are
- [ ] Brett/Emerald determine if there is a way to programmatically remove them or if it should be manual
- [x]  Remove broken url links 

Note: records that have been submitted to the CRHP should be flagged as the broken link may be appearing on the Historic Places website for the record.

**Comment by bferguso** [comment]
CSV from script output sent by email

**Comment by KatieMcEvoy** [comment]
Broken links have been removed
