### ISSUE TITLE
Search Bar Improvements

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#938]
Improvements to help users navigate and use search interface

- [x] Change default display text of Map Search Bar to "Find an address..."
- [x] Better align search bar so the entire bar is in user view. Currently is cut-off (see image)

![Image](https://github.com/bcgov/BCHeritage/assets/139929541/f176d97b-23c0-424a-99b3-c8bb124d911a)

**Comment by bferguso** [comment]
I think the placement of the search box has been resolved in Arches core 7.5.2

**Comment by emjohnst** [comment]
@bferguso @jrods if the search bar is fixed, can we still update default text to display "Find an address" ?

**Comment by bferguso** [comment]
There is a bug in arches core that was making this "Search" rather than "Find an address". Applying a workaround to fix. Does it need to have the ellipsis at the end? The standard Arches core will not have that when the bug has been fixed.

**Comment by emjohnst** [comment]
@bferguso no it doesn't have to have elipses

**Comment by emjohnst** [comment]
Done in test
