### ISSUE TITLE
Landing Page Updates

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#944]
Updates to landing page

- [ ] Question - there seems to be a change in spacing and width between the sections between Prod and Test. Can we keep the original spacing in Prod? Perhaps we need to share screens to discuss this.
- [x] Update manual section: Title update: "Arches is designed to be intuitive" 
- [x] Update manual section: Text update: "Click on the thumbnails below to access the user guides to help you navigate the [Arches](https://www.archesproject.org/) interface.
- [x] Update manual section - add thumbnails for guides. Images attached (links forthcoming, please add thumbnails before links ready). Order of appearance: How to search, Basic Search, Advanced Search

- [x] When hovering over the table of contents sections in Test the effect is more pronounced than in Prod. Is there a reason for this or can it be reverted to the way it was in Prod?

- [x] Update Contact info section "For more information or to report any issues please contact the Heritage Branch at [heritage@gov.bc.ca](mailto:heritage@gov.bc.ca) or visit our [website](https://www2.gov.bc.ca/gov/content/governments/celebrating-british-columbia/historic-places).

- Add Territory Acknowledgement Statement under Contact section (do not add to table of contents) Text as follows: "The Heritage Branch acknowledges it carries out its work on the traditional territories of Indigenous nations throughout British Columbia. We pay our respects to the Elders, past and present, descendants and custodians of these lands. We honour the knowledge keepers and the continuing relationships with Indigenous peoples in BC that develop through our work together. The Heritage Branch is grateful to the Lkwungen-speaking people, today known as the Esquimalt and Songhees First Nations, on whose traditional territories we operate our main offices."

- [x] Under Local Government Section fix spacing between Actand
- [x] Under contact heritage branch fix spacing between .caor
- [x] Reorder Icon so it is PDF, Basic Video, Advanced Video
- [x] Under contact information - fix spelling of Lkwungen to Lekwungen
- [x] Under provincial historic places section - remove extra space after act

![Image](https://github.com/bcgov/BCHeritage/assets/139929541/dc2dbfd8-5800-4e62-90f1-12b2eceb52d9)
![Image](https://github.com/bcgov/BCHeritage/assets/139929541/9a377cb3-d3d1-448b-960d-4363cefe8f2b)
![Image](https://github.com/bcgov/BCHeritage/assets/139929541/96c196b5-a780-44db-a8b6-3f00e404de90)

![Image](https://github.com/bcgov/BCHeritage/assets/139929541/28ec0b36-53d1-4d43-b198-0909dcb5e10b)

**Comment by JessicaInTime** [comment]
@emjohnst I have a question regarding a couple of points:

> Question - can we put a placeholder for the video tutorial? Screenshot of homepage with updates
>
> Updates to PDF manual and text (forthcoming)

I'm not sure what these mean exactly, are these updates something that we are still waiting for?

**Comment by emjohnst** [comment]
@jrods @bferguso I've updated the ticket with the thumbnails discussed. Let me know if you need me to email thumbnail images.

**Comment by JessicaInTime** [comment]
@emjohnst thank you for the thumbnails, however would you be able to remove the text from them? As the text we can be added in the browser to prevent it looking distorted on different screen sizes

**Comment by emjohnst** [comment]
@jrods Okay, do you want the white box removed too?

**Comment by JessicaInTime** [comment]
@emjohnst the white box with bcrhp text? yes please

**Comment by emjohnst** [comment]
@jrods icons attached here
![advancedsearch](https://github.com/bcgov/BCHeritage/assets/139929541/05b61b7e-6881-4e47-8770-6de46a75c852)
![pdfmanual](https://github.com/bcgov/BCHeritage/assets/139929541/e67229c8-af9a-4aa4-b3cd-c24f0d03abf3)
![basicsearch](https://github.com/bcgov/BCHeritage/assets/139929541/78d93841-2db8-4988-a4b3-501009d1f420)

**Comment by emjohnst** [comment]
@jrods @bferguso Changes are looking good - I have a couple minor edits included here and I will put in body of ticket. 

- [x] Under Local Government Section fix spacing between Actand
- [x] Under contact heritage branch fix spacing between .caor
- [x] Reorder Icon so it is PDF, Basic Video, Advanced Video

Thanks!

![Image](https://github.com/bcgov/BCHeritage/assets/139929541/dd1bb6b8-c682-4fd6-a822-6c2492ce308d)
![Image](https://github.com/bcgov/BCHeritage/assets/139929541/5e3f567c-03b2-4f91-a507-c4d0d011dc53)
![Image](https://github.com/bcgov/BCHeritage/assets/139929541/81f074f6-3906-4209-862e-dd2b363cafe8)

**Comment by emjohnst** [comment]
@jrods @bferguso added a couple more edits our communications person caught, updated body of ticket. 


![Image](https://github.com/bcgov/BCHeritage/assets/139929541/22fe8100-6c2b-4370-89bf-d731a2cd58cf)

**Comment by emjohnst** [comment]
Done in test
