### ISSUE TITLE
Public Site CSV output

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#947]
For Testing, we have performed the following to compare the databc view before and after:
```
call refresh_materialized_views();
create table databc.before_947 as select * from databc.V_HISTORIC_ENVIRO_ONEROW_SITE order by borden_number;
```

The data export view is called `heritage_site.csv_export`

The views should be dropped after this issue goes to prod.

Public should have the ability to export reports of search results that include the following information.

Quotations indicate CSV column label

Date should also appear in this order:

- [x] "Borden Number"
- [x] "Site Name" - "Common Name" to align with DataBC view
- [x] "Site Name Type" - "Other Name" to align with DataBC view
- [x] "Street Address"
- [x] "City"
- [x] "Locality"
- [x] "Postal Code"
- [x] "Location Description"
- [x] "Registration Status"
- [x] "Registry Type"
- [x] "Recognition Government" - Government Name
- [x] "Recognition Type" - Legislative Act
- [x] "Reference Number"
- [x] "Recognition Start Date" - Designation or Protection Start Date
- [x] "Recognition End Date" - Designation or Protection End Date
- [x] "Architect/Builder Name" - As per below - this is `Architect/Designer`
- [x] "Architect/Builder Type" - As per below - this is `Builder`
- [x] "Architect/Builder Notes" - This includes nodes from both Architect and Builder rows
- [x] "Chronology Event" - Event - These 4 fields formatted into single field
- [ ] "Chronology Start Year" - Start Year
- [ ] "Chronology End Year" - End Year
- [ ] "Chronology Notes" - Notes
- [x] "SOS Type"
- [x] "SOS Description" - Description
- [x] SOS Document Location
- [x] Number of Resources - These 3 column consolidated into one in format `[Heritage Category] [Ownership[ ([Number of resources])`
- [ ] Heritage Category
- [ ] Ownership
- [x] Function Category - Changed to "Current Function"
- [x] Function Period - Changed to "Historic Function"
- [x] Heritage Theme

**Comment by JessicaInTime** [comment]
@emjohnst have some questions for you:

1. Based on the work that is used for databc, the database query is filtering Chronology Event kinds to be only Construction, should this still be the case for the CSV export or should all event kinds be included? As I’m familiar with construction and significant options
2. For the Architect / Builder Name, based on what I see in databc’s query, there are 2 separate but similar columns, Architect / Designer and Builder. What are you looking for here, since I’m not familiar with the data, but when querying those 2 columns, I see a combination of either both, one another, or none. Would you be able to provide more details?
3. For the Function Category and Period, would it be better to do the same thing that is done for databc with displaying the Current and Historic functions? Otherwise I'm a bit confused what should be the results, would you be able to expand on?

**Comment by JessicaInTime** [comment]
@emjohnst another question:
4. For the heritage class columns: contributing resource count, ownership, and heritage category, I'm seeing multiple entries per resource (1 or more), what should be done here? Is it expected to include all in a readable format?

<img width="1300" alt="image" src="https://github.com/bcgov/BCHeritage/assets/5874122/13f64398-7cc0-468a-9b76-71ec9c544812">

**Comment by emjohnst** [comment]
@jrods 
1. Yes include all events
2.  Continue to export as architect/designer one column and builder another column as with data bc export
3. Yes let's keep the same as data bc version, with one column of all historic functions and one column with all current functions.
4. I'm not sure the best approach - can we discuss at check-in tomorrow? Perhaps it would make more sense to have Many Rows versus a One Row approach but lets discuss.

**Comment by emjohnst** [comment]
@jrods As discussed, here are some options to transform the heritage class information into one string and one column for the csv:
Shortened heritage category: Archaeology, Building, Collection, Landscape, Structure. String to appear something like this: Landscape (Public (local), 1); Building (Private, 2)

In the DataBC csv we limited export to highest level of recognition, but here we want to include all recognition. There may need to be some work done to make these columns legible for multiple entries:  
"Recognition Government" - Government Name
 "Recognition Type" - Legislative Act
 "Reference Number"
 "Recognition Start Date" - Designation or Protection Start Date
 "Recognition End Date" - Designation or Protection End Date

**Comment by emjohnst** [comment]
Done in test
