### ISSUE TITLE
Simplify Recognition Type format on Details tab

### ISSUE THREAD

**Issue by JessicaInTime** [bcgov/BCHeritage#952]
From #887 mock-up: [Public.Site.Details.Page.Mock-up.pdf](https://github.com/bcgov/BCHeritage/files/14924514/Public.Site.Details.Page.Mock-up.pdf)

- [x] Fix Recognition Type as suggested in mock-up (above): [Leg Act Authority, Leg Act Recognition Type (for example:

Municipal, Heritage Designation)]

**Comment by JessicaInTime** [comment]
@emjohnst would you be able to provide more info on what needs to be address for the Recognition Type?

Currently it's clear what doesn't match up:
<img width="440" alt="Screenshot 2024-05-21 at 8 48 01 AM" src="https://github.com/bcgov/BCHeritage/assets/5874122/8cb50dcf-161f-4965-974b-829161aba689">
<img width="420" alt="Screenshot 2024-05-21 at 8 47 32 AM" src="https://github.com/bcgov/BCHeritage/assets/5874122/92d863cc-d77e-4918-919e-734670ca19bf">

But what should happen is only taking the following 2 fields:
<img width="480" alt="Screenshot 2024-05-21 at 9 07 19 AM" src="https://github.com/bcgov/BCHeritage/assets/5874122/37619b1f-ebed-4609-9a9b-6f9b22870a2a">

**Comment by emjohnst** [comment]
Hi @jrods! Yes, we would like to only display Authority and Recognition Type on the Details page. The Legal Instrument and Act Section are more for our internal use. The Details page will be the public page and its easier/faster to understand the heritage status of the site when the other fields are removed. In the example above, it should read Recognition Type: "Provincial, Designation"

**Comment by bferguso** [comment]
This is included in the 887 branch

**Comment by emjohnst** [comment]
Done in test
