### ISSUE TITLE
Server Issue 500

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#953]
Arches Prod is returning a "Server Issue 500" message when clicking on "Search Sites" or "Manage"

Jira ticket created: [[SD-112960] BCFMS and BCRHP applications are receiving server error messages - CSNR - JIRA (gov.bc.ca)](https://apps.nrs.gov.bc.ca/int/jira/projects/SD/queues/issue/SD-112960)

Could be a broader internal server issue affecting multiple applications.

**Comment by emjohnst** [comment]
![manage](https://github.com/bcgov/BCHeritage/assets/139929541/eea30a32-9d57-4dab-9306-1b1f2a5c1710)
![search](https://github.com/bcgov/BCHeritage/assets/139929541/811af31a-be3c-4a7c-854d-aacf423a97c7)

May be related to [PROD: FOR - Linux Approval Request - Apply Quarterly OS Patches to Prod Servers_27 servers_Reboot](https://bcgov.sharepoint.com/sites/WLRS-TEC/Lists/Infrastructure%20Bulletins/DispForm.aspx?ID=1151&e=R0I7Uk&xsdata=MDV8MDJ8fDczMmQ3ZGVkNTdiZTQ1OWU4MmQxMDhkYzc5ZDA4MDVkfDZmZGI1MjAwM2QwZDRhOGFiMDM2ZDM2ODVlMzU5YWRjfDB8MHw2Mzg1MTkxODM1OTM1MzgyNTd8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPamxpTVdOaU5EaGhMVFUyTldRdE5EZzRaQzA1WTJJMkxXTXlZakF5TW1WbVpXWTJaVjlsWXpnMFl6QmpZeTFqTm1JekxUUXhNelV0WVRNNVpTMWpOemRoWldRME5qVTFZemRBZFc1eExtZGliQzV6Y0dGalpYTXZiV1Z6YzJGblpYTXZNVGN4TmpNeU1UVTFPREk0TVE9PXxhYjE5NTA0ODdiNDM0ODdhODJkMTA4ZGM3OWQwODA1ZHxlMGYyNzA3NjFlZjY0MmVkYjlkYzJlYzYzMjkxNTIzNw%3D%3D&sdata=RHdjdlFXRmhIV0tFcGZMbFNBako0U0ZjTFFYWVhEb2ZsSjAzTmNMN3d3RT0%3D&ovuser=6fdb5200-3d0d-4a8a-b036-d3685e359adc%2CEmerald.JohnstoneBedell%40gov.bc.ca) Sonia is contacting infrastructure team about the issue.

**Comment by emjohnst** [comment]
Test and Delivery seem to be working.

**Comment by bferguso** [comment]
@emjohnst - it appears that the redis server didn't come back up after the reboot. I've started it and set the service to start automatically so this shouldn't happen again. I can't see the JIRA SD tickets - would you please close that one?
