### ISSUE TITLE
Add Recognition Type definition as tooltip

### ISSUE THREAD

**Issue by JessicaInTime** [bcgov/BCHeritage#959]
From #887 

- [x] Add hover definition to appear over Recognition Type - drawn from terminology definition

[Details Card Help Text.docx](https://github.com/bcgov/BCHeritage/files/15440701/Details.Card.Help.Text.docx)

**Comment by emjohnst** [comment]
@bferguso @jrods I have the definitions ready for the Recognition Type. Is that something I can add myself to the Notes section of the Reference Data Manager for the concepts? Would I have to add it to both test and prod? I also would like to clean up a couple recognition types, two I need to change and then 6 will be removed - what's the best way to remove them?

**Comment by emjohnst** [comment]
@bferguso @jrods In Delivery I've added notes to the Recognition Type concepts and labelled the notes as "definitions". This is the text to appear as hover/click from an icon beside the Recognition Type.

**Comment by bferguso** [comment]
This only works with hover right now, not with the typical bootstrap focus trigger, which doesn't make it accessible. In a meeting on 20 Jun with @emjohnst - we decided to not let that hold up the overall ticket and public website release. This should be fixed, and will be tracked as part of the tooltip issue identified in #939 as they may be related.

**Comment by emjohnst** [comment]
Done in test
