### ISSUE TITLE
Perform initial review of mobile deficiencies

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#960]
Perform review of mobile site deficiencies. List of deficiencies to be listed here.

landing page: (Done or otherwise low priortiy)

- [x] Ability to get to the search page from hamburger button
- [x] Alignment of "BC Register of Historic Places" in header (see fig. 1)
- [ ] Adjust size of widget images to fit mobile screen size or crop to mobile size (centre of images or I can provide cropped images if I am given a size) (fig 1) See #988 
- [x] Adjust size and spacing of Text that overlays images to fit on mobile screen - can cover whole image (fig 1)

**Comment by bferguso** [comment]
@emjohnst - Do you want to do this or would you like us to? Please assign accordingly.

**Comment by emjohnst** [comment]
@bferguso will do

**Comment by emjohnst** [comment]
@bferguso From Arches landing page on mobile device I am unable to expand the menu to select "search sites" to see what the search page is looking like. This would be a good first step before providing list of deficiencies.

**Comment by bferguso** [comment]
@emjohnst - that would be a good start! OK - we'll start there.

**Comment by emjohnst** [comment]
Done in test, created spin off tickets for post mvp 2 release
