### ISSUE TITLE
Huge Address Numbers Causing Sites to Not Load

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#983]
Keep 1 address and associated legal description for each of the following records and remove repeat addresses and their associated legal descriptions:
- [x] DiQh-68 
- [x] DgQk-66
- [x] DgQk-69
- [x] FhRm-15
- [x] DjQh-20
- [x] FbRl-18

- [x] Emerald to add internal remarks to records: "Removed excess legal description information that caused site to be slow to load. As a municipal site the authority of the legal address information rests with the municipality. Check Record Edit History for legal description information that was removed"

**Comment by bferguso** [comment]
@emjohnst - I've sent an excel spreadsheet with all the addresses for the above sites. Please choose one row for each site to keep and I'll create a script to remove the rest.

I've used the TEST database to generate the list - I'm assuming the list will be the same since you're unable to edit the sites due to the number of addresses. SQL used to generate the list:
```
select bn.resourceinstanceid                                "Site UUID",
       borden_number -> 'en' ->> 'value'                    "Borden Number",
       add.street_address -> 'en' ->> 'value'               "Street Address",
       add.city -> 'en' ->> 'value'                         "City",
       add.locality -> 'en' ->> 'value'                     "Locality",
       add.location_description -> 'en' ->> 'value'         "Location Description",
       add.tileid                                           "Address UUID",
       pid                                                  "PID",
       pin                                                  "PIN",
       add.legal_description -> 'en' ->> 'value'            "Legal Description",
       add.legal_address_internal_notes -> 'en' ->> 'value' "Legal Address Internal Notes",
       add.legal_description_uuid                           "Legal Description UUID"
from heritage_site.borden_number bn
         join (select pa.*,
                      ld.tileid legal_description_uuid,
                      ld.pid,
                      ld.pin,
                      ld.legal_description,
                      ld.legal_address_internal_notes
               from heritage_site.bc_property_address pa
                        join heritage_site.bc_property_legal_description ld
                             on pa.tileid = ld.bc_property_address) add
              on bn.resourceinstanceid = add.resourceinstanceid
where borden_number -> 'en' ->> 'value' in ('DiQh-68', 'DgQk-66', 'DgQk-69', 'FhRm-15', 'DjQh-20', 'FbRl-18')
order by borden_number -> 'en' ->> 'value';
```

**Comment by emjohnst** [comment]
@bferguso emailed spreadsheet back with highlighted rows. Rows selected for each site are as follows:
DgQk-66 – Row 1022
DgQk-69 – Row 1501
DiQh-68 – Row 3693
DjQh-20 – Row 5059
FbRl-18 – Row 5314
FhRm-15 – Row 5910

**Comment by emjohnst** [comment]
Emerald still needs to do this once Prod is available again
