### ISSUE TITLE
Update Landing Page Screenshots

### ISSUE THREAD

**Issue by emjohnst** [bcgov/BCHeritage#985]
Update the following images:

- [x] Replace figure 1 with figure 1 attached. 
- [x] Replace figure 1 text: " Figure 1: Interactive map of historic places in BC"
- [x] Replace figure 2 with figure 2 attached.
- [x] Replace figure 2 text: Figure 2: Filter search by local government. Showing map card pop-up for Nelson Street Grids.
- [x] Replace figure 3 with figure 3 attached
- [x] Replace figure 3 text: Figure 3: Grist Mill at Keremeos
- [x] Replace figure 4 with figure 4 attached.
- [x] Replace figure 4 text: Figure 4: National Historic Site search showing Fisgard Lighthouse details page.

![Image](https://github.com/bcgov/BCHeritage/assets/139929541/2760c4f5-7ecd-45d1-a17d-a10a8bd46a3e)
![Image](https://github.com/bcgov/BCHeritage/assets/139929541/857d0f9d-38c8-4441-aefd-8b2c5aad7bd3)
![Image](https://github.com/bcgov/BCHeritage/assets/139929541/69e6e14f-9eae-45f6-8e5b-dae78b3e876e)

 

![Image](https://github.com/bcgov/BCHeritage/assets/139929541/c31e7330-ad0e-458b-a05b-eb15e355cefb)

[CopyrightNotice.txt](https://github.com/user-attachments/files/16133927/CopyrightNotice.txt)

**Comment by JessicaInTime** [comment]
@emjohnst for storing these images, is it ok to have them in the public repository? In addition, would it be required to put a copyright readme along with the images in the repo?

**Comment by JessicaInTime** [comment]
@emjohnst at this time we have the 3 provide changes in place, and we will wait till the 4th is updated on the ticket.

**Comment by emjohnst** [comment]
@jrods I've added the final image and a copyright read me for the image repository. Thanks@

**Comment by bferguso** [comment]
@emjohnst - I think the copyright for the repo needs to be changed to specify the images. We're part of AGPL Affero so the source code is open source. 

@jrods  - I think we should put the copyright readme in the images directory, rather than in the root of the repo.

**Comment by emjohnst** [comment]
@jrods @bferguso the new images look great!

**Comment by emjohnst** [comment]
Done in test
