### ISSUE TITLE
Duplicated sites in DataBC one row view

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#987]
There are some sites that have multiple records in the databc view because they have multiple common names. How should we address these sites? If we were consistent with other attributes in the system we could create a semi-colon separated string if there are multiple common names for a site.
- [ ] Determine how this should be addressed
- [ ] Perform logic fix in view

**Comment by bferguso** [comment]
@emjohnst  - Please review and assign to me once a decision is made. We can discuss next week if you'd like clarification.

**Comment by bferguso** [comment]
These are the sites with multiple common names in TEST
site_id|borden_number|count
-----|-----------------|-------
1ebcabb9-dc4f-43a4-a755-31df9eaaefa0|DcRu-296|2
5083e55c-80a8-472d-a274-8ea472fbfd02|DdSe-23|2
f63fef29-8f09-46f6-917f-587daae20223|DdSe-25|2
d3d12141-0c5c-47c8-88c4-9bc91e830396|DeSf-13|3
3f36d4ca-6661-4ec8-bf8b-a52de2c0abd2|DgPm-22|2
1e2cfdcd-8642-4c1c-a25b-832aa369ce6a|DgPo-7|2
a690b637-3360-4c11-b882-3a2db47f2e70|DgSl-71|2
e3d54cf8-5521-4eb6-9618-ad0cf6351234|DhRr-925|2
734c64ca-f32f-4d18-bb24-791e0590ce85|DhRs-1393|2
f3e58b7c-5b80-4b5b-9214-538dfd2eb565|DiPs-1|2
b352fa6c-5dee-4079-a2e3-ae50fab5daf8|DiRf-1|2
e3bb1766-3a25-467d-8902-e62374b7362d|DiRi-85|2
861134db-fadb-43ea-ab34-0ea76aec4023|DjRt-17|3
fca68bb3-0534-46b9-9068-a62e3af0c4ce|DkQi-20|2
a8b2b82e-d985-4c2b-92b6-dd9de783733a|DlQi-18|3
cb2e4b29-0ad3-4a6d-b367-06c2c47834a7|EdSp-92|3
70772855-f6cd-42b0-8670-553162a1b9e4|EfQo-3|2
3ccacfb1-7ef5-4aaf-a7ab-ac06e41496c0|EfQp-2|2
8a16a21e-fc34-4448-91f8-92ef717253c4|EfRr-5|3
c5847079-ed54-47f2-938a-c5a1a21c79e6|EgSv-2|2
10fd132e-a928-454a-85e2-10d8918506b1|EhQj-3|2
9c17b229-a835-4dc8-8353-13111c8404a2|EhQn-1|2
4ae1fba2-ab48-4acf-adca-2042f09c3603|EiQc-3|2
5a11645b-70e5-4135-b26b-e4438e752c2e|GbTk-1|2

**Comment by emjohnst** [comment]
@bferguso I think having more than 1 common name is causing too many issues. In prod, I will manually edit the records so there is only 1 common name for a record. Do you want/need me to manually edit the common names in test environment as well?

**Comment by bferguso** [comment]
@emjohnst - It might be worth doing that as I believe the TEST data also flows through to DataBC so it could potentially cause problems downstream. We should also probably implement that as a business rule in one of the future releases.

**Comment by emjohnst** [comment]
Closing because changes made in Prod data.
