### ISSUE TITLE
Change Details view visibility  to be based on Guest role not on anonymous user

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#993]
~Users can create Guest accounts when authenticating against OIDC. Those accounts should also have Resource Exporter role.
Right now the sections that are visible on the Details page are determined by whether a user is anonymous or not. This should be changed to be based on wither a user has the Guest role or not.~

Any user with the "Guest" role, including anonymous, will see the external-facing view of the Details tab.

**Comment by emjohnst** [comment]
Done in test
