### ISSUE TITLE
OIDC changes

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#995]
- [x] Hide "Welcome, ..." section if not authenticated
- [ ] ~Brand login page, don't try to authenticate using OIDC if username doesn't exist in Arches.~
- [ ] ~Only allow IDIR on SSO page.~

Changed such that:
- Login redirects straight to OIDC login page
- Users can't self-register if OIDC authenticated
- Users that authenticate but are not registered in the system are redirected to an Unauthorized page.

**Comment by bferguso** [comment]
@jrods - Please update the login.htm and remove the Welcome on the spash screen if anonymous. - .5 days.

**Comment by emjohnst** [comment]
Done in test
