### ISSUE TITLE
Ask NRIDS to update reverse proxy configuration for new context root

### ISSUE THREAD

**Issue by bferguso** [bcgov/BCHeritage#998]
Need to ask NRIDS to update the reverse proxies to allow the public context root to be routed to the application servers. JIRA request is here: https://apps.nrs.gov.bc.ca/int/jira/projects/BCRHP/issues/BCRHP-116?filter=allopenissues

**Comment by emjohnst** [comment]
@bferguso is this complete?

**Comment by bferguso** [comment]
@emjohnst - yes, this is complete.
